### ISSUE TITLE
Broken link to the asciidoctor-pdf docs

### ISSUE THREAD

**Issue by tombentley** [asciidoctor/asciidoctor.org#1006]
On https://asciidoctor.org/docs/ there's a link to "Convert AsciiDoc to PDF with Asciidoctor" which seems to get redirected to https://asciidoctor.org/docs/asciidoctor-pdf/ which says `Unresolved directive in asciidoctor-pdf.adoc - include::https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor-pdf@v1.5.4/README.adoc[]`

**Comment by mojavelinux** [comment]
It looks like this was a temporary build fluke. I reran the build and the page is now back.
