### ISSUE TITLE
Can't find 'collapsible' documentation on docs.asciidoctor.org

### ISSUE THREAD

**Issue by oddhack** [asciidoctor/asciidoctor.org#1007]
Putting 'collapsible' into the searchbox on docs.asciidoctor.org just turns up references to the compound block processor extension and the What's New list, but no actual documentation. Is this supported at present? If so, can it be used with anything *other* than example blocks? Potentially quite useful for us if so.

N.b. discuss.asciidoctor.org appears to be down at the moment, or I'd have asked there.

**Comment by oddhack** [comment]
NM, I see this is a duplicate of https://github.com/asciidoctor/asciidoc-docs/issues/34

**Comment by mojavelinux** [comment]
Yep, the documentation is no longer stored in this repository.

> discuss.asciidoctor.org appears to be down at the moment, or I'd have asked there.

Nabble sprung a migration on us without much notice, so there are steps I need to do to get it back up. While we do plan to keep that running, the bulk of the community discussions have been moved to https://asciidoctor.zulipchat.com.
