### ISSUE TITLE
Document zulip chat site / preserve discuss history

### ISSUE THREAD

**Issue by oddhack** [asciidoctor/asciidoctor.org#1008]
Follows on #980. Apparently https://asciidoctor.zulipchat.com/ is now the preferred discussion / chat forum, but asciidoctor.org still has discuss.asciidoctor.org in the 'Discuss' menu item, and the 'Chat' and "Discussion list (Nabble)' items under 'Getting Help' on the site main page similarly appear out of date. The only way I found it was a pointer from Dan in a github issue.

Has / can the discuss.asciidoctor.org history been imported to zulipchat? I've repeatedly found answers over the years by trawling the archives there and it would be sad for that to be permanently lost either by disabling the site, or keeping its content isolated from from the latest-and-greatest thing which is apparently zulipchat, for the time being.

**Comment by mojavelinux** [comment]
> Has / can the discuss.asciidoctor.org history been imported to zulipchat?

No, it has not. And there isn't any path to do that. I am going to restore discuss.asciidoctor.org. As I said elsewhere, Nabble sprung a migration on us with virtually no notice and they are the ones who took the site offline. I have to take action to get it restored, but this was a terrible week for me to deal with something like that as I was saturated with other work.

discuss.asciidoctor.org will always be available (at least in read-only form), assuming Nabble continues to offer their service. If that situation changes, we'll address it then.

**Comment by mojavelinux** [comment]
This is closely related to https://github.com/asciidoctor/asciidoctor-docs-ui/issues/113, which will add similar links to the header of the docs site.

**Comment by mojavelinux** [comment]
> and the 'Chat' and "Discussion list (Nabble)' items under 'Getting Help' on the site main page similarly appear out of date

Oops, I forgot to update the home page when I released Asciidoctor 2.0.16. I just made that change. See https://asciidoctor.org/#getting-help

**Comment by mojavelinux** [comment]
I've change the topbar link to Chat instead of Discuss since that's the primary entry point into the community. The link to the discussion/mailing list will remain elsewhere if you need it. But the community chat has proved far more beneficial to the community (by leaps and bounds), so that's community channel we want to promote.

**Comment by mojavelinux** [comment]
I'm going to deal with discuss.asciidoctor.org in a separate issue. See #1009.

**Comment by oddhack** [comment]
Thanks!
