### ISSUE TITLE
Stop leading people into a potential trap at awestruct.org

### ISSUE THREAD

**Issue by ramalho** [asciidoctor/asciidoctor.org#1010]
Thank you for making **Asciidoctor**.

I appreciate you want to give credit to the awestruct project, but right now I think this is a disservice and may soon be a serious hazard to anyone interested in using **Asciidoctor**. The problem is that awestruct.org was hacked and the maintainer of awestruct has ignored this serious issue. See https://github.com/awestruct/awestruct.org/issues/74

Currently, the hacked site apparently only serves to boost the SEO of some random site. But nothing prevents the people who now control awestruct.org to link to a clone of the original awestruct/awestruct repo with malicious code that could have very serious consequences.

As long as the maintainer of awestruct does not address this grave situation, I think you should remove all references to the name "awestruct" from the **Asciidoctor** site. Right now, anyone interested in deploying a site with **Asciidoctor** and awestruct will find the hacked site as the first search result.

**Comment by mojavelinux** [comment]
Seems sensible to me.
