### ISSUE TITLE
docs: typo in Hard Line Breaks - paragarphs 

### ISSUE THREAD

**Issue by bubbasnmp** [asciidoctor/asciidoctor.org#1012]
https://docs.asciidoctor.org/asciidoc/latest/blocks/hard-line-breaks/

All of the line breaks in **paragarphs**

**Comment by mojavelinux** [comment]
Would you be willing to submit a fix? To do so, click "Edit this Page", make the change, then press the "Commit changes" button.

**Comment by bubbasnmp** [comment]
Well that wasn't too painful. Done.  
[Typo - paragarphs #103](https://github.com/asciidoctor/asciidoc-docs/pull/103/commits)

**Comment by mojavelinux** [comment]
Thanks!
