### ISSUE TITLE
creating table xrefs that leverage the autogenerated table numbers

### ISSUE THREAD

**Issue by ernest-bruce** [asciidoctor/asciidoctor.org#1025]
AsciiDoctor appears not to support the creation of xrefs that instead of a regular anchor use the autogenerated table caption + table number

that is, using a table ID (similar to a bibliography·item ID [[[reference,1]]] but without the custom number) i would like to code something like
    <<my_table>> shows ...
and the produced xref text to be “Table 1 shows ...” where Table 1 is a link to the table but without me having to maintain the table numbers as i add/remove tables

**Comment by mojavelinux** [comment]
Please ask questions in the project chat at https://chat.asciidoctor.org as stated on the [support policy page](https://docs.asciidoctor.org/about/support/#chat). This is not the place to ask them. Thanks.
