### ISSUE TITLE
Combining cells in the table header

### ISSUE THREAD

**Issue by SemenLimorenko** [asciidoctor/asciidoctor.org#1034]
Good time of day!

Faced with the need to develop documentation using AsciiDoctor. I sort of figured out the tables, but I can't beat combining cells in the table header:

> .Table name
[cols="1,1,1,1,1", hrows=2]
|====
.2+|United cell 1
 2+|United cell in row
.2+|United cell 2
.2+|United cell 3
|Call 1
|Cell 2
|
|
|
|
|
|
|====

As a result, the boundary between Cell 2 and United cell 2 disappears:

![image](https://github.com/asciidoctor/asciidoctor.org/assets/159278418/a713cde1-4fbb-4b05-9dad-af85556faef3)

Independent search for a solution did not bring results, I ask for help.

**Comment by mojavelinux** [comment]
Please direct questions about usage to the project chat at https://chat.asciidoctor.org. See https://docs.asciidoctor.org/about/get-help/ Thanks!
