### ISSUE TITLE
How do I block inline passthroughs?

### ISSUE THREAD

**Issue by Sherry520** [asciidoctor/asciidoctor.org#1036]
The contents are as follows
```
[cols="1,2",options="header"]
|==============================
|Notepad++ (Windows 64-bit) |`git config --global core.editor "'C:\Program Files\Notepad++\notepad++.exe' -multiInst -notabbar -nosession -noPlugin"` (Also see note below)
|==============================
```
The software name `Notepad++` will turn to "Notepad" in PDF. 

I have tried to add `\` befor `+`, but it will print as :

![image](https://github.com/user-attachments/assets/5e37b06a-cf50-4657-9828-f103b4eff50b)

**Comment by Sherry520** [comment]
It worked when I changed the code as follows:
```
|Notepad++ (Windows 64-bit) |`git config --global core.editor "'C:\Program Files\Notepad\++\notepad++.exe' -multiInst -notabbar -nosession -noPlugin"` (Also see note below)
```
But I still don't understand.

**Comment by mojavelinux** [comment]
Please direct questions regarding usage of Asciidoctor to the project chat. See https://docs.asciidoctor.org/about/get-help/ to learn more about this policy.
