### ISSUE TITLE
AsciiDoc vs. Markdown

### ISSUE THREAD

**Issue by DarkTyger** [asciidoctor/asciidoctor.org#1037]
Re: https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/#comparison-by-example

> AsciiDoc uses the same number of markup characters or less when compared to Markdown in nearly all cases.

Here are the results from my comparison:

```
$ grep "M: +1" compare.txt | wc -l
8
$ grep "A: +1" compare.txt | wc -l
7
```

Here's the comparison text I used (note the disqualifications and changes; I didn't include items of the same length):

```
M: **bold**
A: *bold*
A: +1

M: `m`onospace
A: ``m``onospace
M: +1

M: `http://localhost:8080`
A: `+http://localhost:8080+`
M: +1

M: `/issue/{id}`
A: `+/issue/{id}+`
M: +1

M: [Asciidoctor](https://asciidoctor.org)
A: https://asciidoctor.org[Asciidoctor]
A: +1

M: [user guide](user-guide.html)
A: link:user-guide.html[user guide]
M: +1

M: [get the PDF]({% raw %}{{ site.url }}{% endraw %}/assets/mydoc.pdf)
^^^ does anybody use that syntax for relative files?

M: [get the PDF](/assets/mydoc.pdf)
A: link:{site-url}/assets/mydoc.pdf[get the PDF]
M: +1

M: See [Usage](#_usage).
A: See <<_usage>>.
A: +1

M: <h2 id="usage">Usage</h2>
A: [#usage] == Usage
A: +1

M: ![Logo](/images/logo.png)
A: image:/images/logo.png[Logo]
M: +1

A: image:logo.png[Logo]???
A: disqualified for missing images directory

M: ![Alt](logo.png "Logo")
A: image::logo.png[Logo]???
A: disqualified for missing alt text that differs from link text

M: > Quoted text. >  > Another paragraph in quote.
A: ____ Quoted text.  Another paragraph in quote.  ____
M: +1

M:     $ gem install asciidoctor
A:  $ gem install asciidoctor
A: +1

M: ```java public class ```
A: [source,java] ---- public class ---
M: +1

M: 1. first 1. second 1. third
A: . first . second . third
A: +1

M: Go to the [home page][home]. [home]: https://example.org
A: :home: https://example.org Go to the {home}[home page].
A: +1
```

I wouldn't say AsciiDoc is shorter in nearly all cases. Also, if that's the strongest argument to use AsciiDoc, it's not compelling. Consider first fixing the comparison so that it is fair (and technically accurate with _common_ real-world usages) and then move the length comparison to the bottom of the list (or strike it altogether). IMO, AsciiDoc's best selling feature is cross-references and citations, not whether you save a couple keystrokes here and there.

Other issues:

* **Ordered lists.** Numbered lists can be `1. 1. 1.` and the computer will auto-increment.
* **Quotations.** Typographic quotes can be accomplished using post-processing without needing a special syntax. The algorithm in [KeenQuotes](https://whitemagicsoftware.com/keenquotes/) solves the quote curling problem in nearly all cases.
* **Admonitions.** Pandoc supports annotations in Markdown, as does flexmark-java. Annotations are more flexible than admonitions because admonitions are canned; whereas, annotations are user-defined.
* **Document header.** I fundamentally disagree with adding formatting instructions into plain text documents. To me, the point of writing in plain text is to be independent of any formatting. (If I wanted to put formatting into my text document, I'd hand-bomb HTML.)
* **Custom CSS.** CSS? In a plain text document? This mixes presentation and content as well as loosely couples an assumption about the presentation medium (HTML). Annotations are powerful because they allow semantic descriptions of the content allowing the presentation logic to vary independently.
* **Sidebars and block titles.** These imply presentation. Markdown annotations provide the ability to create asides and block titles.
* **Includes.** R Markdown provides file transclusion. Fair point that it isn't bundled, though.
* **Tables.** While perhaps not in the CommonMark spec, basic ASCII tables are widely supported natively by almost all Markdown implementations. It is misleading at best to claim otherwise. Furthermore, the `<table>` syntax is available in all Markdown implementations and was part of Gruber's [original specification](https://daringfireball.net/projects/markdown/syntax#html).

**Comment by mojavelinux** [comment]
Please don't use the issue tracker to rant. If you want to share opinions, you are welcome to do so in the project chat at https://chat.asciidoctor.org.
