### ISSUE TITLE
URL containing double dash leads to corrupted URLs

### ISSUE THREAD

**Issue by sdavids** [asciidoctor/asciidoctor.org#1038]
I am unsure if this is a feature or a bug…

```shell
$ mkdir /tmp/test && cd "$_"
$ echo 'Single' >s-ingle.txt
$ echo 'Double' >d--ouble.txt
$ echo 'Triple' >t---riple.txt
$ cat << 'EOF' >test.adoc
= Test

https://plugins.jetbrains.com/plugin/7495--ignore

https://plugins.jetbrains.com/plugin/7495--ignore[]

https://plugins.jetbrains.com/plugin/7495--ignore[.ignore]

https://git-scm.com/docs/git-init#Documentation/git-init.txt-code--initial-branchcodeemltbranch-namegtem

https://git-scm.com/docs/git-init#Documentation/git-init.txt-code--initial-branchcodeemltbranch-namegtem[]

https://git-scm.com/docs/git-init#Documentation/git-init.txt-code--initial-branchcodeemltbranch-namegtem[default branch]

https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---shortltlengthgt

https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---shortltlengthgt[]

https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---shortltlengthgt[short]

link:s-ingle.txt[]

link:d--ouble.txt[]

link:t---riple.txt[]

xref:s-ingle.txt[]

xref:d--ouble.txt[]

xref:t---riple.txt[]

EOF
$ docker run -it -u $(id -u):$(id -g) -v $PWD:/documents/ asciidoctor/docker-asciidoctor:1.77.0 asciidoctor test.adoc
```

⇒ `test.html`

---

The first two triplets will render broken links the last triplet has working links.

The first triplet is a regular link; the second triplet is a link which should jump to the anchor.

`xref:` and `link:` also have the issue with `--`.

---

I think this an undesired interaction with [Text replacements](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-replacements).

If one escapes the m-dash (`--` ⇒ `\--`):

`https://plugins.jetbrains.com/plugin/7495--ignore` ⇒ `https://plugins.jetbrains.com/plugin/7495\--ignore`

then the links will work.

This is not intuitive and if it is desired behavior then it should be mentioned:

- [Troubleshooting Complex URLs](https://docs.asciidoctor.org/asciidoc/latest/macros/complex-urls/)

or someplace along the lines "Text replacements happen before URL handling".

**Comment by mojavelinux** [comment]
This is as designed.

Please note that this is not the correct repository to be reporting issues
with the software. This repository is for the website build only.

If you want to discuss the language in general, you can do so in the
project chat at https://chat.asciidoctor.org

**Comment by sdavids** [comment]
https://docs.asciidoctor.org/asciidoc/latest/macros/complex-urls/

> A URL may not display correctly when it contains characters such as underscores (`_`) or carets (`^`).

⇓

> A URL may not display correctly when it contains https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#text-replacements[text replacements] or characters such as underscores (`_`) or carets (`^`).

**Comment by mojavelinux** [comment]
If you want to propose this change, please click Edit the Page and submit a
merge request.
