### ISSUE TITLE
Document the safe mode levels and the features they affect

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#125]
Add a section that documents each safe mode level and identify which features are affected by the setting.

I'm thinking of laying out the definitions for each safe mode as a labeled list and using a matrix (table) to identify which features are affected by each safe mode.

**Comment by jaredmorgs** [comment]
This has been documented at http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely and can be safely closed.

**Comment by mojavelinux** [comment]
:+1:
