### ISSUE TITLE
Rework block title, metadata, and delimiters in the user manual

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#156]
The block title, metadata and delimited block sections don't flow well within the structure of the user manual. A lot of the information is also repeated (or should be) within the expanded sections for each block type.

Therefore, it might make more sense to:
- Provide a brief introduction to blocks and substitutions in the terms and concepts part
- Link from the brief introduction to the expanded block sections
- Provide the summary table in an appendix
- Make sure each expanded block section explains and/or provides an example of:
  - definition of block type
  - paragraph and delimited syntax
  - substitutions
  - title
  - attributes
- Move the masquerading information to the specific sections it applies to (i.e. sidebar and open blocks.

**Comment by jaredmorgs** [comment]
http://asciidoctor.org/docs/user-manual/#blocks suggest this is still an open issue requiring work.

**Comment by mojavelinux** [comment]
I agree. We at least need a basic description of a block here. Hopefully, that should be pretty straightforward.

MDN has a nice resource dedicated to this topic.

https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements

Although the mapping between AsciiDoc and HTML isn't one-to-one, the idea of block vs inline content still applies.

What we want to say about blocks are the following:

* discrete, contiguous line-oriented elements in the document structure
* should be offset by other blocks by surrounding blank lines (though not always required)
* in some cases can have block children
* consists of the following types: document (the document as a whole is the root block), section, delimited block, block macro, list and table

Each of these types gets handled slightly differently, but they all share similar properties, like have block-level attributes.

**Comment by mojavelinux** [comment]
I've done a lot of work in the new docs to make this clearer. See https://docs.asciidoctor.org/asciidoc/latest/blocks/ If there is still something that's not clear, open a new issue in that repository and we can discuss how to solve it.
