### ISSUE TITLE
Improve output overview section in user manual

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#158]
The [output section](http://asciidoctor.org/docs/user-manual/#output-formats) in the user manual needs to provide better descriptions of the outputs and link to the expanded sections for using each output.

Also, remove the AsciiDoc output information.

**Comment by jaredmorgs** [comment]
This is an easy fix. 

Add links to each item in http://asciidoctor.org/docs/user-manual/#selecting-an-output-format to all the sub-sections. 

Working out what extra info to provide on each item may be a little bit more challenging, but even if we link first and worry about content later, that will be a good easy-win improvement.

**Comment by mojavelinux** [comment]
manpage is now a built-in converter (not an add-on).

epub3 is missing.

I'd demote deckjs here because there are many other converters worth mentioning before that one. And that should be in a dedicated section about creating presentation slides.

**Comment by mojavelinux** [comment]
This issue has been resolved in the new documentation site. See https://docs.asciidoctor.org/asciidoctor/latest/convert/, to which the link in the description resolves.
