### ISSUE TITLE
Add expand-include pre-processor script to include section of user manual

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#159]
Make [this script](http://discuss.asciidoctor.org/Output-single-adoc-file-from-includes-td808.html) and its description into a sidebar within the include section of the user manual.

**Comment by jaredmorgs** [comment]
The post where action is identified is here: http://discuss.asciidoctor.org/Output-single-adoc-file-from-includes-tp808p1157.html

@mojavelinux suggested that a new attribute `:preprocess_only => true` could be a good addition to do away with all this in the API for users: 

[source,ruby]
--
require 'asciidoctor'

source_file = ARGV[0]
if !source_file
  warn 'You must provide a source file'
  exit 1
end
output_file = source_file.sub(/\.adoc$/, '-preprocessed.adoc')
source = File.read source_file
doc = Asciidoctor.load_file ARGV[0], :safe => :safe, :parse_header_only => true
reader = Asciidoctor::PreprocessorReader.new doc, source
preprocessed_source = reader.read.gsub(/^include::/, '\\include::')
File.open(output_file, 'w') {|f| f.write preprocessed_source }
--

**Comment by mojavelinux** [comment]
There's actually a script for this in the extensions lab. See https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb. It's not perfect, but it gets you most of the way there.

**Comment by mojavelinux** [comment]
We've decide to publish is as separate project / RubyGem instead. See https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/126

**Comment by mojavelinux** [comment]
The asciidoc-coalescer.rb script has been redesigned and published as the [asciidoctor-reducer](https://github.com/asciidoctor/asciidoctor-reducer). It has also been released to RubyGems.org as a gem named **asciidoctor-reducer**. You can find installation instructions in the README for that project.
