### ISSUE TITLE
Document encoding attribute

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#160]
By default, Asciidoctor sets a document's encoding to UTF-8.
The `encoding` attribute can be used to override the input and output character set of the document.

 `-a encoding=` or `:encoding:`

However, the other encodings are pretty much un-tested at this point in Asciidoctor.
If the header contains non-UTF-8 characters then encoding must be set prior to the characters in the heading or on the command line.
When outputting to HTML you can set the `lang` attribute to the appropriate language, for reporting in the header.
By default, `lang` is set to `en`.

Further references:

* [Ruby CLDR](https://github.com/twitter/twitter-cldr-rb)
* [Unicode CLDR Project](http://cldr.unicode.org/)
* [Unicode](http://en.wikipedia.org/wiki/Unicode)
* [UTF-8](http://en.wikipedia.org/wiki/UTF-8)
* [ASCII](http://en.wikipedia.org/wiki/ASCII)

**Comment by jaredmorgs** [comment]
Good detail to convert into a docs addition.

There is mention of :encoding: in http://asciidoctor.org/docs/user-manual/#asciidoctor-vs-asciidoc but that is the only mention of this attribute. 

Looking at the methods guide, this attribute is described in the Headers area. Any comment about not putting a section into this area?

What advantages would there be to setting encoding other than UTF-8?

**Comment by mojavelinux** [comment]
We've changed are stance on this. We only accept UTF-8 (or UTF-16) now because it's just not reasonable in a globalize world to work any other way. So I think we should just kill this issue.

**Comment by jaredmorgs** [comment]
Agreed. Let's kill it with fire.

On Tue, 26 Jan 2016 at 11:03 Dan Allen <notifications@github.com> wrote:

> We've changed are stance on this. We only accept UTF-8 (or UTF-16) now
> because it's just not reasonable in a globalize world to work any other
> way. So I think we should just kill this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/160#issuecomment-174753569>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Long live UTF-8!
