### ISSUE TITLE
Add section that details how to setup third-party deck.js extensions

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#198]
The instructions in the deck.js guide for how to setup third-party extensions (not included in the main deck.js repository) are very fuzzy. Add a dedication section that goes through the instructions for setting up a third-party extension step-by-step.

**Comment by jaredmorgs** [comment]
There doesn't seem to be any suggested guidance on how to do this so I guess I'll set a NEEDINFO on this one @mojavelinux . Perhaps Bespoke.js will supercede this? :wink:

**Comment by mojavelinux** [comment]
Bespoke definitely supersedes this. Bespoke should be our focus as it is the present and future. (Reveal to a lesser degree only due to its popularity and more mature converter).

**Comment by mojavelinux** [comment]
We don't want to emphasize deck.js anymore. And the docs for using the reveal.js converter for Asciidoctor are strong. See https://docs.asciidoctor.org/reveal.js-converter/latest/ So I think we're covered. Any improvements should be directed to that project.
