### ISSUE TITLE
Use new Google Analytics script

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#216]
Upgrade the master template to use the new Google Analytics JavaScript code, as documented here:

https://developers.google.com/analytics/devguides/collection/analyticsjs/

**Comment by jaredmorgs** [comment]
This is pretty old now. Has it been done @mojavelinux ?

**Comment by mojavelinux** [comment]
PR sent!

I decided to use our own copy of the script so we have maximum control over it.

**Comment by mojavelinux** [comment]
Resolved by https://github.com/asciidoctor/asciidoctor.org/commit/338a7c85c99063bab3c99af8b203a6d0e981a398.
