### ISSUE TITLE
Change comments on posts to use Discourse

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#218]
Once we have a discourse forum setup, switch the comments on blog posts to use Discourse instead of Disqus.

This setup is documented in the following posts:

* http://eviltrout.com/2014/01/22/embedding-discourse.html
* http://blog.bigdinosaur.org/working-on-a-new-comment-system/
* https://github.com/trident523/js-discourseBestOf
* https://meta.discourse.org/t/discourse-plugin-for-static-site-generators-like-jekyll-or-octopress/7965/117

**Comment by jaredmorgs** [comment]
I have seen the work to date in #304 but it seems like the effort ran out of steam. The last thing I read was about the Nabble to Discourse migrator script.

**Comment by mojavelinux** [comment]
We don't really get that many comments on the blog, so I honestly don't think this is worth the investment (even if/when we do switch to Discourse for the discussion list).
