### ISSUE TITLE
Add links to groovy and spring-docs/guides to what-is-asciidoctor

### ISSUE THREAD

**Issue by jexp** [asciidoctor/asciidoctor.org#236]

**Comment by jaredmorgs** [comment]
https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/what-is-asciidoctor.adoc is the source file in question. 

Questions:

* Should we refer to #270 here and close off this issue?
* Should we give props to all awesome Asciidoctor docs implementations in one place for maintainability?

**Comment by mojavelinux** [comment]
Yes and yes.

**Comment by jaredmorgs** [comment]
Time to close.
