### ISSUE TITLE
Document the conditional preprocessor directives

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#283]
Document the three conditional preprocessor directives:

* ifdef
* ifndef
* ifeval

as well as the cooresponding closing directive, endif.

For example:

```
ifdef::env-github[]
Hello, GitHub visitor!
endif::[]
```

If there are a large amount of lines between the start directive, we should recommend using the (optional) long-hand form for the end:

```
ifdef::env-github[]
many
many
lines
....
many
many
lines
endif::env-github[]
```

Note that there is no long-hand form for the end of `ifeval`.

**Comment by mojavelinux** [comment]
Here's the relevant section from the AsciiDoc User Guide: http://www.methods.co.nz/asciidoc/userguide.html#_conditional_inclusion_macros

Note that the AsciiDoc User Guide refers to these as macros, but they are not really macros because they get applied by the line reader, not the parser. That's why we call them directives.

**Comment by jaredmorgs** [comment]
Claimed. (Can't assign to myself).

**Comment by jaredmorgs** [comment]
OK. This is a start. See PR. Looking for fact checking before we talk about including the examples in an included file. ;)

**Comment by mojavelinux** [comment]
Thanks @jaredmorgs!

It's probably worth explaining the expression used in the `ifeval` directive in some detail since it can be a bit difficult to understand and differs from the AsciiDoc Python implementation.

---

I'd start by saying that the expression is not evaluated by the language interpreter (which may allay concerns of it being an attack vector). Rather, the expression is evaluated using a custom interpreter that has very restricted (and thus safe) computation rules.

=== Anatomy

The expression consists of a left-hand value and a right-hand value with an operator in between.
Here are a few examples:

* `2 > 1`
* `"{backend}" == "html5"`
* `{sectnumlevels} == 3`

=== Values

Each expression value may reference the value of an AsciiDoc attribute using the attribute reference syntax (e.g., `{backend}`).
Attribute references are resolved (aka substituted) first.
Once attributes references have been resolved, each value is coerced to a recognized type.

The following values types are recognized:

* number (integer or floating-point)
* quoted string (enclosed in either single or double quotes)
* boolean (literal value of `true` or `false`)

If a value is enclosed in quotes, the characters between the quotes are preserved and coerced to a string.
If a value is not enclosed in quotes, it's subject to the following type coercion rules:

* an empty value becomes nil (aka null)
* a value of `true` or `false` becomes a boolean
* a value of only repeating whitespace becomes a single whitespace string
* a value containing a period becomes a floating-point number
* any other value is coerced to an integer value


=== Operators

The value on each side is compared using the operator to derive an outcome.

* `==` - checks if the two values are equal
* `!=` - checks if the two values are not equal
* `<=` - checks whether the left-hand side is less than or equal to the right-hand side
* `>=` - checks whether the left-hand side is greater than or equal to the right-hand side
* `<` - checks whether the left-hand side is less than the right-hand side
* `>` - checks whether the left-hand side is greater than the right-hand side

The operators follow the same rules as operators in Ruby.

**Comment by jaredmorgs** [comment]
This is fantastic detail. I'll work on incorporating all this over the next few days. This Conditionals topic is going to be rock solid and detailed.

**Comment by mojavelinux** [comment]
:cake: & :ice_cream: !

I'd probably point out two additional facts. First, you can use multiple attribute references in a single value.

```
"{docname}{outfilesuffix}"
```

Second, when using attribute references, we strongly recommended that you enclose the value in quotes (because you are usually dealing with a string and you want it to remain that way).

**Comment by jaredmorgs** [comment]
I think we're getting close to "done" with this issue. I've incorporated all feedback to date.

**Comment by mojavelinux** [comment]
Thanks @jaredmorgs! This is a huge improvement to the user manual!
