### ISSUE TITLE
The referenced filename in the user guide for the footer docinfo file is incorrect

### ISSUE THREAD

**Issue by bleathem** [asciidoctor/asciidoctor.org#296]
The user guide says to use a filename of the format `<docname>-footer.xml`:

> If you want to add content to the footer of a specific document, put the content in the file <docname>-footer.html (for HTML output) or <docname>-footer.xml (for DocBook output), where <docname> is the name of the document without the AsciiDoc extension. Then, set the attribute docinfo in the source document.

However in practice it seems as though the filename should still have the _docinfo_ term, as in `<docname>-docinfo-footer.xml`.

**Comment by jaredmorgs** [comment]
Issue can be closed.
