### ISSUE TITLE
Document the subtitle functionality

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#297]
Asciidoctor recognizes a subtitle in the primary level-0 heading. If the primary title contains at least one colon, Asciidoctor treats the text after the final colon as a subtitle.

```
= Title: Subtitle
```

In this example:

* primary title = Title
* subtitle = Subtitle

Note that the subtitle is not *displayed* in the html5 backend. It is displayed in the docbook and epub3 backends. Support for subtitle display is planned for the pdf backend (so just say for now that it supports it).

Asciidoctor also provides an API for extracting the title and subtitle. See the following line for information: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L601

**Comment by shahryareiv** [comment]
IMHO, this should be expanded to  level-1 headings (i.e. chapters) in book format. This is specially needed when chapters are independent papers (quite common in academic books).

**Comment by mojavelinux** [comment]
Good suggestion, @shahryareiv. Could you file a new issue in the Asciidoctor core repository? That's where the code would need to be changed.

https://github.com/asciidoctor/asciidoctor/issues

**Comment by SandMann1** [comment]
Is title partitioning in the plans for HTML5 backend?

**Comment by mojavelinux** [comment]
I don't see why not. There isn't an open issue about it yet, though. We'd have to sort out how to style it in the default stylesheet, of course. In the meantime, it is something you could implemented with a custom Slim template for the document node.

**Comment by ysb33r** [comment]
> I don't see why not. There isn't an open issue about it yet, though. We'd have to sort out how to style it in the default stylesheet, of course. In the meantime, it is something you could implemented with a custom Slim template for the document node.

How is it seen in the AST? I can only see a `title` / `doctitle` on the document node. Is custom parsing required ?

**Comment by ysb33r** [comment]
To answer my own question I see there is a `Title`  class in the Ruby code (and in asciidoctorj this is accessable via `structureddoctitle`).

**Comment by mojavelinux** [comment]
> Is custom parsing required ?

For titles other than the document title, you'd need to use custom parsing. Ideally, it should be possible to reuse the Title interface to parse a title. This is possible in the Ruby code, but not currently in AsciidoctorJ. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L39-L70.

**Comment by mojavelinux** [comment]
Documented thanks to @jaredmorgs!
