### ISSUE TITLE
Clearly document that delimited block boundaries must have equal lengths

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#307]
In the delimited blocks section, clearly document that the boundaries of a delimited block must have equal lengths. In other words, the starting boundary line must exactly match the ending boundary line.

Illegal:

```
------
listing
----
```

Legal:

```
----
listing
----
```

We should also add a warning that if a boundary is not matched, then the remainder of the document will be included inside the block (i.e., the block will not end until the document ends).

**Comment by jaredmorgs** [comment]
I think this might already be captured in http://asciidoctor.org/docs/user-manual/#delimiter-lines

**Comment by mojavelinux** [comment]
I agree.

Maybe we should also add this to the FAQ. I think it should be part of 1. http://asciidoctor.org/docs/faq/#troubleshooting
