### ISSUE TITLE
Document what contexts and content_model are available

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#323]
Tracking the following issue: https://github.com/asciidoctor/asciidoctor-documentation/issues/30

**Comment by jaredmorgs** [comment]
All the info is definitely clearly documented in the linked issue. But where should it go in the User Guide?

**Comment by mojavelinux** [comment]
For now, I think it should be a new section after the [Extension Points](http://asciidoctor.org/docs/user-manual/#extension-points) section titled "Document Model" (or something like that). We need to describe the AST that extensions have to work with and this is a good starting place for that information.

**Comment by mojavelinux** [comment]
The following sections can then build on this information knowing it has been laid out.

**Comment by jaredmorgs** [comment]
Next Action:

- Create a new section called Extension Points.
- Put in a link to this bug like the other Discussion trackers.
- Flesh out the details later once we get a chance.

On Tue, 26 Jan 2016 at 19:48 Dan Allen <notifications@github.com> wrote:

> The following sections can then build on this information knowing it has
> been laid out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/323#issuecomment-174932310>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
I corrected your list (changed the name of the new section)

**Comment by mojavelinux** [comment]
If you give me a space to type about Document Model, I can fill in a whole bunch of details :)

**Comment by jaredmorgs** [comment]
I'll create an include and let you go for broke. Will do this sometime this
week.

On Wed, 27 Jan 2016 at 13:30 Dan Allen <notifications@github.com> wrote:

> If you give me a space to type about Document Model, I can fill in a whole
> bunch of details :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/323#issuecomment-175371307>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
I want to add that this content is crucial, particularly for extension writers. Without this information, it can be very hard to understand the Asciidoctor document model (and generally how Asciidoctor perceives the content). So we definitely want to dedicate attention to this.

**Comment by jaredmorgs** [comment]
Noted. Will see if I can start it this week.

On Thu, 28 Jan 2016, 05:20 Dan Allen <notifications@github.com> wrote:

> I want to add that this content is crucial, particularly for extension
> writers. Without this information, it can be very hard to understand the
> Asciidoctor document model (and generally how Asciidoctor perceives the
> content). So we definitely want to dedicate attention to this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/323#issuecomment-175807753>
> .
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
This is ready for you to elaborate on in documentation form @mojavelinux

**Comment by mojavelinux** [comment]
Yep, I gotcha. Ball is in my court.

**Comment by wimdeblauwe** [comment]
Any updates on this. I have a feeling it might help my question at http://discuss.asciidoctor.org/My-first-AsciidoctorJ-extension-undefined-method-include-for-nil-NilClass-tp5736p5739.html

**Comment by mojavelinux** [comment]
@graphitefriction This likely needs to be moved to asciidoc-docs, then addressed relatively early in the language specification process. It's a little tricky since this topic straddles the language and the document model / API.

**Comment by mojavelinux** [comment]
The canonical location for this issue is now https://github.com/asciidoctor/asciidoc-docs/issues/57. Please direct this discussion to that issue.
