### ISSUE TITLE
Make PDF of user manual, quick reference and writer's guide available

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#328]
Make a PDF of the user manual, quick reference and writer's guide available on the website. Automate the creation of the PDF as part of the production build process.

**Comment by jaredmorgs** [comment]
:+1:

**Comment by mojavelinux** [comment]
If we can get the user manual and syntax quick reference to build with Asciidoctor PDF, this is easy. The PDF that is currently linked from the site was generated with fopub. I'd rather not mess with that beast.

...or perhaps I should say that we should just generate the user manual and quick reference with Asciidoctor PDF and deal with any problems as they come.

Generating the PDF is as simple as adding a step to the Awestruct pipeline to generate the file and shove it into _site. I can probably take this one, but I won't get to it until my next go around on Asciidoctor PDF.

**Comment by jaredmorgs** [comment]
OK. I'll leave this one with you Dan. Using asciidoctor-pdf as part of the
Awestruct build is definitely the way to go.

Let the robots do the work.

On Tue, 26 Jan 2016 at 19:25 Dan Allen <notifications@github.com> wrote:

> If we can get the user manual and syntax quick reference to build with
> Asciidoctor PDF, this is easy. The PDF that is currently linked from the
> site was generated with fopub. I'd rather not mess with that beast.
>
> ...or perhaps I should say that we should just generate the user manual
> and quick reference with Asciidoctor PDF and deal with any problems as they
> come.
>
> Generating the PDF is as simple as adding a step to the Awestruct pipeline
> to generate the file and shove it into _site. I can probably take this one,
> but I won't get to it until my next go around on Asciidoctor PDF.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/328#issuecomment-174920880>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
This will actually be a very important test case for Asciidoctor PDF, so it's well worth the exercise.

**Comment by mojavelinux** [comment]
We can almost generate the writer's guide. What's currently missing is the parsing of the `<u>` element.

**Comment by mojavelinux** [comment]
I'm happy to say that the upcoming release of Asciidoctor PDF (1.5.0.alpha.15) will include support for AsciiDoc table cells. We are one step closer to being able to make this PDF.
