### ISSUE TITLE
Document cell specifier for repeating cell contents

### ISSUE THREAD

**Issue by mrhaki** [asciidoctor/asciidoctor.org#332]
Asciidoc allows for repeating cells using the cell specifier <span>*. This also works for Asciidoctor but is not yet documented.

See also http://www.methods.co.nz/asciidoc/userguide.html#X84

**Comment by rockyallen** [comment]
Close this? It appears in http://asciidoctor.org/docs/user-manual/#cell

**Comment by mojavelinux** [comment]
Agreed.
