### ISSUE TITLE
Write differences between AsciiDoc and Markdown documentation

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#34]
How do the two syntaxes differ?
Partners with the Asciidoctor and AsciiDoc differences
May go under The Basics category

**Comment by timofonic** [comment]
Any news? :D

**Comment by jaredmorgs** [comment]
This issue has been open for about three years now. I wonder what we need to do to wrap up this issue.

Perhaps we need to take what we have and look at incorporating it into the #435 issue.

**Comment by mojavelinux** [comment]
This issue and #435 are basically the same issue. This issue has actually served as a useful landing page in the interim for consolidating the discussions pertaining to the differences. The next step is to summarize that information.

Given the popularity of Markdown and, therefore, the likeliness someone is migrating from it, I'd say this is an important section / resource.

**Comment by mojavelinux** [comment]
The first draft is in thanks to @andya9!

**Comment by IbnSaeed** [comment]
where is the first draft ?

**Comment by mojavelinux** [comment]
See http://asciidoctor.org/docs/user-manual/#compared-to-markdown
