### ISSUE TITLE
The syntax quick reference guide doesn't explain how to escape URL's that contain a [ character

### ISSUE THREAD

**Issue by ge0ffrey** [asciidoctor/asciidoctor.org#343]
I want to place a link to
  http://d.hatena.ne.jp/tokobayashi/searchdiary?word=[OptaPlanner]
with the title
  Kobayashi's blog

However, with or without backslash escaping, it doesn't work:

    http://d.hatena.ne.jp/tokobayashi/searchdiary?word=\[OptaPlanner\][Kobayashi's blog]

It never renders properly. The syntax guide reference should explain how to escape url's (as it differs from escaping text which is  a section in that doc).

**Comment by mojavelinux** [comment]
This will definitely be a good addition to the quick reference.

In this case, I would strongly recommend to URL encode the square brackets.
Another option is to surround the URL in +, then add an explicit link:
prefix to force it to be a link.

**Comment by mojavelinux** [comment]
I've added an example to the syntax quick reference and also corrected the example about how to deal with spaces in a URL as well.
