### ISSUE TITLE
Tux images in ex-image.adoc are not available

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor.org#358]
I was just checking the user manual on the site, and noticed that the tux images used as examples in the `Include images by full URL` are not available any more :disappointed:.

Some other example should be used instead in the file https://raw.githubusercontent.com/asciidoctor/asciidoctor.org/master/docs/_includes/ex-image.adoc

**Comment by mojavelinux** [comment]
Let's use the one from wikimedia commons. That will be a stable URL.

**Comment by mojavelinux** [comment]
Fixed by 10ca69d1ba754243d9b09f1e5bb5bede0dca2bd9.
