### ISSUE TITLE
Add reference table for attributes that must be defined in the header

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#369]
Add a reference table that lists the attributes that must be defined in the header (aka preamble) of the document in order to take effect.

These attributes include:

* source-highlighter
* icons
* ...

People are often confused about where an attribute has to be defined. If they find it in this list, it makes the point much clearer.

**Comment by jaredmorgs** [comment]
Is there a way of finding out which attributes must be header attributes. Some references in the code?

I know from first hand experience that knowing which attributes must be applied in the header are a bit of black magic. 

(basically anything except :sectnums: right)?

**Comment by mojavelinux** [comment]
This is now resolved that to the work of @rockyallen. See http://asciidoctor.org/docs/user-manual/#builtin-attributes.

It turns out, this was a pretty enlightening exercise even for me. Prior to this table being created, I probably couldn't even have provided an accurate answer. Now, you don't need me or my guesses.

This table shed some light on several gray areas where an attribute should be defined in the header but may still work if it isn't. We don't have to worry about that anymore either, because if we say it should be in the header, then that's not just a requirement, but a best practice.

**Comment by jaredmorgs** [comment]
Such awesome work by @rockyallen. Legend!

On Tue, 1 Mar 2016, 17:20 Dan Allen <notifications@github.com> wrote:

> Closed #369 <https://github.com/asciidoctor/asciidoctor.org/issues/369>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/369#event-572607841>
> .
>
-- 

Sent from Mobile.
