### ISSUE TITLE
Table count in other language than English

### ISSUE THREAD

**Issue by iketanijus** [asciidoctor/asciidoctor.org#374]
Hello,
I've been using asciidoctor a lot and by far it's been an amazing experience! I write most of the documents in Lithaunian language. However, I've stumbled on a problem of Table counting. For eg. if I create a table with title:

.Failinių sistemų apžvalga
[cols="5*", options="header"]

And then reder the document:
Table 1. Failinių sistemų apžvalga	

I would like it to count tables in my language like this:
Lentelė 1. Failinių sistemų apžvalga	

Did a lot of searching, but no avail. Perhaps, there is an attribute I could define. Like I do with toc-title:
:toc-title: Turinys

So my Table Of Contents is shown as Turinys.

Best regards,
Egidijus M.

**Comment by mojavelinux** [comment]
What you are looking for is the attribute `table-caption`. We don't yet have out-of-the-box language files, but we have all the hooks in place to substitute language-specific keywords. All blocks that support titles (such as the table block) follow the pattern `<blockname>-caption`.

```
:table-caption: Lentelė

.Failinių sistemų apžvalga
|===
|a |b
|===
```

We should add a new section to the user manual about i18n support that explains this feature. Let's follow up with a separate issue to track that improvement.

**Comment by iketanijus** [comment]
That worked perfectly. Cheers! 

i18n support would be really nice too. I'll try to volunteer for this.
