### ISSUE TITLE
Document the reftext attribute

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#380]
The reftext can be used as an alternate to a title for assigning a label that is used at the local of a xref.

Consider the following case:

```
[[tiger-image]]
.Image of a tiger
image::tiger.png[]

See <<tiger-image>>.
```

The xref link to the image will appear as `Image of a tiger`. Instead of assigning a title to the image, the label can be assigned using the reftext attribute:

```
[[tiger-image,Image of a tiger]]
image::tiger.png[]

See <<tiger-image>>.
```

Of course, the label can always be overridden by using an explicit label on the xref itself.

```
See <<tiger-image,image of a scary tiger>>.
```

This point should be made in the xref section.

**Comment by jmini** [comment]
This was the next thing on my documentation improvement list.

I discovered this feature by reading this post from Emmanuel Bernard on the mailing list: [Asciidoc vs markdown](http://discuss.asciidoctor.org/Asciidoc-vs-markdown-miniidoc-td269.html).

My thinking so far:

In the **AsciiDoc Syntax Quick Reference** the [links](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#links) section could contains an example of `reftext`. After "Inline anchors" we could have an example "Inline anchors with reftext attribute".

In the **Asciidoctor User Manual** the Chapter [29. Internal cross references](http://asciidoctor.org/docs/user-manual/#xref) could be rewored.

From:

    29. Internal cross references
        29.1. Inter-document cross references

To:

    29. Cross references
        29.1. Defining cross references
        29.2. Internal cross references
        29.3. Inter-document cross references

Several places speaking about defining cross references for specific items:

* [Images](http://asciidoctor.org/docs/user-manual/#images)
* [Blocks > Metadata](http://asciidoctor.org/docs/user-manual/#metadata-2) 
* [Sections](http://asciidoctor.org/docs/user-manual/#sections) 

They could point in addition to this new `19.1` section (that correspond to all the possibilities when defining cross references)

**Comment by mojavelinux** [comment]
Agreed. I like the changes you are proposing. I especially like the reworking of section 29 because the heading is definitely too specific right now. Cross references is definitely the topic...and this new structure gives us room to address the topic properly.

**Comment by jmini** [comment]
I have proposed a fix for this in **pull request #390**.

**Comment by mojavelinux** [comment]
Thanks @jmini! This is on my list to review...hopefully in the next few days.

**Comment by graphitefriction** [comment]
@mojavelinux I'm closing this issue as PR #390 and PR #401 handle the bulk of these concerns. However, I am going to spawn another issue about custom reftextlabels. I think the fact that you can define it both in the ID and the cross reference and the resulting inheritance rules gets a little lost.

**Comment by mojavelinux** [comment]
Excellent!

Let's be sure to explain the search priority. When determining the label to put at the location of the cross reference, it searches for text in the following order:

1. The explicit text specified on the cross reference itself
2. The value of the reftext on the object to which the cross reference points
3. The title of the object to which the cross reference points

(It may be useful to note that DocBook calls the reftext the xreflabel. They are one and the same).
