### ISSUE TITLE
Document the unit of measure for height and width of images

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#381]
Document what unit of measure is used for height and width of images. The answer is CSS pixels, the same as defined in HTML5.

It would also be good to document how this affects PDF generation. Basically, the scaledwidth attribute can be used to scale the image to a certain width of the PDF page. Otherwise, it is up to the PDF conversion code to interpret how to translate CSS pixels into an appropriate size in the PDF.

**Comment by mojavelinux** [comment]
For more information, see this thread:

http://discuss.asciidoctor.org/Unit-of-measure-for-image-dimensions-td3040.html

**Comment by mojavelinux** [comment]
Keep in mind we are rethinking how image dimensions are controlled in Asciidoctor PDF, so we'll need to make sure we document those changes.

**Comment by jaredmorgs** [comment]
We need an Easy-Fix label for a lot of these docs issues, @mojavelinux 

It would be good for new contributors to get them hooked.

**Comment by mojavelinux** [comment]
I created the same "simple-fix". Let's see how that plays. We can revise it as needed.

**Comment by rockyallen** [comment]
This is how I think it should work:

https://github.com/rockyallen/asciidoctoressays/blob/master/imagesizing/imagesizing.pdf

although my experiments aren't working out yet!

If this is what you wanted I will turn it into a PR.

**Comment by mojavelinux** [comment]
We have to be very careful here since the capabilities vary by converter.

The value of the width and height attributes are always assumed to be pixels (px). Those are currently the only dimension attributes recognized by the HTML converter.

The pdfwidth is an override intended for Asciidoctor PDF. It allows the width to be specified using units. If units are not provided, the value is assumed to be points (pt). The units that are accepted are documented in the theming guide. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#measurement-units. Also see https://github.com/asciidoctor/asciidoctor-pdf#image-scaling.

When using pdfwidth, a percentage value is a width relative to the content area. A vw value is relative to the page width. (The percentage is not relative to the original image size).

The scaledwidth is intended for use with the DocBook toolchain. Technically, it accepts a value with units like pdfwidth. (Again, the percentage is not relative to the original image size, but rather the width of the page).

The Asciidoctor PDF converter currently makes the assumption that the value of the scaledwidth attribute a percentage. That may need to be fixed.

**Comment by mojavelinux** [comment]
Note that scaledwidth does not support viewport units (vw).

pdfwidth is intended to be a replacement for scaledwidth. However, the DocBook converter does not recognize pdfwidth, so if you are using the DocBook toolchain, you'll still need to use scaledwidth.
