### ISSUE TITLE
Document sourcemap and catalog_assets options

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#382]
There are two options to extract additional information into the AST during parsing.
- sourcemap: Captures the file and line information for each section to aid with creating a document outline view in an editor
- catalog_assets: Captures all the links and images found in a document for building reference information. Note that many of these assets are cataloged during the convert phase due to how inline parsing is currently handled in Asciidoctor.

**Comment by mojavelinux** [comment]
Note that these options are passed to the options array of the API.

```
Asciidoctor.convert content, source_map: true, catalog_assets: true
```

The options can be used independently.

**Comment by jaredmorgs** [comment]
Are these options only applicable to the Asciidoctor.convert content scope?

**Comment by mojavelinux** [comment]
These options are only relevant when using the Asciidoctor API. They apply to both the `load` and `convert` method. They are mostly intended for use in tools (like an editor) or for document analysis.

**Comment by mojavelinux** [comment]
These are now documented on the API options page. https://docs.asciidoctor.org/asciidoctor/latest/api/options/

I do think it may be worth dedicating a page to each topic to explain how the option is used in practice. Open these as new issues here: https://github.com/asciidoctor/asciidoctor/issues
