### ISSUE TITLE
Document the sectnumlevels attribute

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#383]
The `sectnumlevels` attribute controls the depth of section numbering (both at the section title and in the outline). The default value is 3.

**Comment by wolandscat** [comment]
Would be good if this was added to the user manual - I just spent 20 mins tracking this feature down ;-)

**Comment by mojavelinux** [comment]
@jaredmorgs If you're looking for a priority doc fix to tackle, this would be a good one.

(In general, when you see an issue labeled [next](https://github.com/asciidoctor/asciidoctor.org/labels/next), that's usually something that's sorely needed but not to difficult to address. I suppose you could read it as "might as well do next").

**Comment by jaredmorgs** [comment]
Roger that. Now I've got my website sorted I can do some PR work.

Next = low hanging fruit.

On Sat, 16 Jan 2016, 08:17 Dan Allen <notifications@github.com> wrote:

> @jaredmorgs <https://github.com/jaredmorgs> If you're looking for a
> priority doc fix to tackle, this would be a good one.
>
> (In general, when you see an issue labeled next
> <https://github.com/asciidoctor/asciidoctor.org/labels/next>, that's
> usually something that's sorely needed but not to difficult to address. I
> suppose you could read it as "might as well do next").
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/383#issuecomment-172111171>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
\o/

If you have any questions, just fire away.

**Comment by jaredmorgs** [comment]
Some of this was already in the guide commented out. For the stuff that wasn't I added extra detail.

**Comment by mojavelinux** [comment]
Thanks!

**Comment by jaredmorgs** [comment]
Apart from the PR merge hell I just endured for 15 minutes, I think the feedback you gave is incorporated and ready to check again.

**Comment by mojavelinux** [comment]
Merged!
