### ISSUE TITLE
Add list of extensions and extension descriptions to documentation

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#384]
This issue was spawned from PR: https://github.com/asciidoctor/asciidoctor.org/pull/372

Name: Asciidoctor Screenshot
Description: Automate the inclusion of dynamically-generated screenshots into your documentation.
Runtime: AsciidoctorJ
URL: http://fix.github.io/asciidoctor-screenshot/

Name: Asciidoctor Gherkin
Description: Include Gherkin feature files in AsciiDoc in the form of sections, paragraphs, lists and tables.
Runtime: AsciidoctorJ
URL: https://github.com/domgold/asciidoctor-gherkin-extension

Name: Markup Document Builder
Description: This project is a document builder for markup documents, including AsciiDoc.
Runtime: AsciidoctorJ
URL: https://github.com/RobWin/markup-document-builder

The Markup Document Builder might end up being an infrastructure component rather than an extension.

Name: Asciidoctor Diagram
Description: A set of extensions for Asciidoctor that allow you to embed diagrams written using the PlantUML, Graphviz, ditaa, or Shaape syntax inside your AsciiDoc documents. 
Runtime: Asciidoctor
URL: https://github.com/asciidoctor/asciidoctor-diagram and/or http://asciidoctor.org/docs/asciidoctor-diagram/

Name: Asciidoctor LaTeX
Description: Asciidoc-LaTeX makes it possible to render documents written in AsciiDoc to LaTeX or HTML. It also defines an extended mathematical syntax for the AsciiDoc markup language that closely parallels LaTeX.
Runtime: Asciidoctor
URL: https://github.com/asciidoctor/asciidoctor-latex

Asciidoctor LaTeX has it's foot both in the extension world and the converter world, so I think it will end up showing up in both places (assuming we have a converters page or section in the future).

The extension lab should be highlighted here as well. I would put it under "other" because it's more of a playground.

Name: Extension Lab
Description: A playground for new and experimental extensions. Used to test the capabilities of the extension mechanism.
Runtime: Asciidoctor
URL: https://github.com/asciidoctor/asciidoctor-extensions-lab

Possible sorting structure:

* Split the page into "official" extensions and "third-party" extensions
* Official extensions are simply extensions that are inside the Asciidoctor organization on GitHub and managed as part of Asciidoctor. 
* Third-party extensions are those that are developed outside of the Asciidoctor GitHub organization. 
* It's always possible that an extension from the third-party list becomes an official extension (or vice-versa), so we don't want to make a big deal about the distinction. It's more about where to look.
* It's important to emphasize that "extensions" in this context are extensions to the AsciiDoc syntax or processor. 
* This differs from extensions for other tools, like the Atom extension. 
* The focus here is extensions in the context of the AsciiDoc content.

**Comment by mojavelinux** [comment]
I think it might also be helpful to have a complete index of the components in the Asciidoctor ecosystem, whether they are extensions are not. I've created an initial list and posted it on Google+.

https://plus.google.com/114112334290393746697/posts/C1QLRBynXTB

**Comment by jirutka** [comment]
DocTest is missing on the list. :(

**Comment by mojavelinux** [comment]
Zonk! What was I thinking?!? (actually, I didn't think it wasn't pertinent for what was being asked in the contract :)) But I'll definitely add it to the G+ post.
