### ISSUE TITLE
Document how to split an attribute value over multiple lines

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#387]
Document how to split the value of an attribute entry over multiple lines. As of 1.5.0, you end the line in a `\` to extend the value to the next line. Prior to 1.5.0, you used a `+`, though that still works too.

```
:name: first part \
second part
```

Note that the endlines are removed unless a `+` surrounded by spaces appears before the trailing backslash.

```
:poem: Roses are red, + \
Java is black.
```

**Comment by jaredmorgs** [comment]
http://asciidoctor.org/docs/user-manual/#attributes-2 seems like a good section for this. I know this came up recently for me, so it is one I want to hit sooner.

In fact, assign this one to me @mojavelinux. I'll just get it done (already created an issue branch in my fork).

**Comment by mojavelinux** [comment]
The correct section is http://asciidoctor.org/docs/user-manual/#setting-attributes-on-a-document.

**Comment by mojavelinux** [comment]
Note that we should only document the two forms shown in the issue description. The first example is the primary form. The second example is an edge case. (Of course, feel free to use additional examples, but stick to those two forms).

**Comment by jaredmorgs** [comment]
PR ready for review :D

On Tue, 26 Jan 2016 at 19:33 Dan Allen <notifications@github.com> wrote:

> Note that we should only document the two forms shown in the issue
> description. The first example is the primary form. The second example is
> an edge case. (Of course, feel free to use additional examples, but stick
> to those two forms).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/387#issuecomment-174924360>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Thanks @jaredmorgs!
