### ISSUE TITLE
callout in tables are not working

### ISSUE THREAD

**Issue by bladnor** [asciidoctor/asciidoctor.org#394]
Even if a table column ist prefixed with an 'a' like "a| I would like to use callouts here <1> ", the callout is not rendered like in code blocks. How can I make this work or is this not (yet) supported?

**Comment by mojavelinux** [comment]
Asciidoctor only supports callout numbers at the end of lines in a source block or at the beginning of items in a callout list. This is unrelated to AsciiDoc-style table cells. That's just how Asciidoctor works globally.

You've filed this issue in the Asciidoctor website. Did you mean to file the issue in Asciidoctor core? https://github.com/asciidoctor/asciidoctor. If so, you might be interested in this related issue: https://github.com/asciidoctor/asciidoctor/issues/1077

**Comment by bladnor** [comment]
Yes, I meant the core. Sorry for picking the wrong place. I would like to use callouts not only in source blocks but also in other blocks like a table block. Do you see a chance to implement that?

**Comment by mojavelinux** [comment]
As I mentioned in the referenced issue, we are considering it. However, there are a lot of other priorities before it. That said, it's possible to implement this using an extension (extensions provide solutions to a lot of needs, as designed). I'd recommend using a Treeprocessor, though there are other ways to solve it. Extensions also help us try out an improvement and flesh out all the requirements before bringing it into core.

>  Sorry for picking the wrong place.

No problem. I just wanted to clarify.

**Comment by jaredmorgs** [comment]
Close, @mojavelinux ?

**Comment by mojavelinux** [comment]
I think this is covered by https://github.com/asciidoctor/asciidoctor/issues/1077, so I think we should close the issue here.
