### ISSUE TITLE
Create a wireframe for the Backers page

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#396]
Pull content from bountysource supporters pages

**Comment by graphitefriction** [comment]
Wireframe 1 for backers page

![backer_mock_1](https://cloud.githubusercontent.com/assets/1124042/8259609/07f3366a-167b-11e5-9753-fb08d08b7ca7.png)

**Comment by graphitefriction** [comment]
Questions: Should backers be listed in alphabetical order or some other ordering scheme?

Once a column reaches 5 names in length, start a new column.

How do we want to represent backers who give one-time contributions?

**Comment by mojavelinux** [comment]
> Should backers be listed in alphabetical order or some other ordering scheme?

I think we should randomize the entries within a category. We can use some slim magic to make this happen.

> Once a column reaches 5 names in length, start a new column.

We also might be able to use some responsive CSS to get it to fit within a fixed height / width.

> How do we want to represent backers who give one-time contributions?

I think we should pro-rate the contribution over a year and fit them into the appropriate category. The Q&A category is for $5 _and under_ per month.

**Comment by mojavelinux** [comment]
I wonder if we should start with columns and add rows as needed. That way, we use the space on the page more efficiently. In other words, 5 across, then start a new row.

**Comment by graphitefriction** [comment]
Wireframe 2 per @mojavelinux adjustments (form rows first vs columns)

![backer-2](https://cloud.githubusercontent.com/assets/1124042/8344188/43a3de16-1a9b-11e5-9c5b-81da6237bd76.png)

**Comment by mojavelinux** [comment]
:+1:

**Comment by graphitefriction** [comment]
We have enough information and a satisfactory layout to take this to the next step (prototyping). I'll set up a staging area/repo and kick it off.

**Comment by mojavelinux** [comment]
The page is now up. We don't yet have a campaign video, but everything else is implemented.

http://asciidoctor.org/supporters/
