### ISSUE TITLE
Document the outfilesuffix and how it's used for relative links on GitHub

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#398]
See https://github.com/asciidoctor/asciidoctor/issues/417#issuecomment-36426214

**Comment by DanielSWolf** [comment]
It seems to me that the linked issue has seen a number of revisions, so I'm not sure what the final syntax is. The [official documentation](https://github.com/asciidoctor/asciidoctor/wiki/How-to-link-to-a-relative-AsciiDoc-document) seems to be outdated. I'd appreciate it if you could find the time to document the this.

**Comment by mojavelinux** [comment]
This is now documented here: https://asciidoctor.org/docs/user-manual/#navigating-between-source-files

If, after reading that, it's still not clear, please open a new issue so we can address it.
