### ISSUE TITLE
Document the webfonts attribute

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#410]
When the default stylesheet is in use, the webfonts attribute can be used to:
1. Change the value of the `family` query string parameter when linking to Google Web Fonts (the default is "Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700")
2. Disable the use of webfonts (e.g., `:webfonts!:`)

This doesn't affect how the webfonts are referenced by the stylesheet, only how they are declared in the page.

**Comment by mojavelinux** [comment]
This attribute is intended to be rather low-level to give the user an "out" so that it's possible to load the web fonts using a custom strategy in a docinfo file.

**Comment by jaredmorgs** [comment]
So this would go somewhere into the http://asciidoctor.org/docs/user-manual/#docinfo-file section?

**Comment by mojavelinux** [comment]
Nope, I think it should go in the section [Styling the HTML with CSS](http://asciidoctor.org/docs/user-manual/#styling-the-html-with-css). It makes the most sense under the configuration for the HTML backend, which is where this section lives.

**Comment by jaredmorgs** [comment]
No problem.

I'm trying to ease the path of contribution for bugs like this because they
are potential low hanging fruit ripe for picking by eager contributors.

Having an idea of where to position content will really fast track
contribution potential for folks.

On Fri, 11 Dec 2015, 16:01 Dan Allen <notifications@github.com> wrote:

> Nope, I think it should go in the section Styling the HTML with CSS
> <http://asciidoctor.org/docs/user-manual/#styling-the-html-with-css>. It
> makes the most sense under the configuration for the HTML backend, which is
> where this section lives.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/410#issuecomment-163848629>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
I really appreciate that! These are great questions.

**Comment by mojavelinux** [comment]
Thanks!

**Comment by mojavelinux** [comment]
This attribute is now mentioned in the table of built-in document attributes. It still needs to be explained in the section on HTML styling.

**Comment by oncletom** [comment]
Do you reckon there would be a way to customize the `webfonts` attribute to include an Emoji font as a fallback or something without having to create our own theme? Like `Noto Sans` and `Noto Sans Emoji`.

**Comment by mojavelinux** [comment]
It's not necessary to create a new theme just to include some overrides. You can just use [docinfo](http://asciidoctor.org/docs/user-manual/#docinfo-file) for that. We want to leave the default stylesheet as a static resource. If any replacements were to be done, we'd want to focus improving the stylesheet factory (or similar) to make it easier to create and customize a stylesheet.

**Comment by mojavelinux** [comment]
This is documented here: https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/#disable-or-modify-the-web-fonts and listed in the attributes reference here: https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-reference/#general-content-and-formatting-attributes
