### ISSUE TITLE
Add to Who is Using Asciidoctor

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor.org#414]
Could you add

[Noteshare.io](http:/www.noteshare.io), an online platform for creating lecture notes, course materials, and ["notebooks"](http://www.noteshare.io/tour) of all kinds. Supports mathematical notation via [Asciidoctor-LaTeX](http://math.noteshare.io/titlepage/asciidoctor-latex-manual)

Thanks!
Jim

**Comment by mojavelinux** [comment]
Absolutely! In fact, it's already on the list.

https://github.com/asciidoctor/asciidoctor.org/issues/270

If you'd like to write a short summary (~ 150 - 250 words) of it in a comment on that issue, we'll be sure to include it in the first draft of the page...especially as a featured entry!

**Comment by jxxcarlson** [comment]
Attached!  In Asciidoc format.  I'd like to discuss the last 
paragraph with you at some point -- still thinking
about what is a reasonable business model.

== Noteshare.io

http://www.noteshare.io[Noteshare.io]
is an online platform for editing,
managing, and distributing Asciidoc
content (http://www.noteshare.io/tour["notebooks"]).
A split-view editor
with the source text on the left and the
rendered text on the right makes it easy
to compose text.
Rendered content
may be public or private.  In the first case,
the latest version is available on the user's site,
`screen_name.my.noteshare.io`, as soon as the
update button is pushed.  A search feature
helps users to manage their own content
and to find the public content of others.
Content is not captive to the system -- it may be
downloaded as
a compressed archive which includes
uploaded images and other media.

Users may form groups to share text privately
or for collaborative writing.  Sections of a document
may be checked out so that other group members
cannot accidentally overwrite edits.
Mathematical notation is supported
via the 
http://math.noteshare.io/titlepage/asciidoctor-latex-manual[Asciidoctor-LaTeX]
extension.  Inline formulas are in the form `+$ a^2 + b^2 = c^2 $+`,
displayed formulas use double dollar signs, and there is an
implementation of LaTeX environments.

Noteshare will eventually become a paid service (at a _very_
reasonable annual rate), but all users in the rollout period
will be grandfathered in as free forever.

**Comment by mojavelinux** [comment]
That's great. I'm going to move the comment to #270 and close this issue.

**Comment by mojavelinux** [comment]
Regarding the last paragraph, my advice is to put the existing users into the same basic "plan" that new users get...kind of a preview of the service. That way, you don't have different users getting different privileges (which seems fine now, but I think equality is a more virtuous goal). The idea of a free plan should be to allow users to see how it works, but kind of hands off in terms of service. No support, no promises of uptime, etc. Nothing that takes time for you to address individually. It's (nearly) free for you to run a server / application, so you let them use it for free. The paid plan is all about service. Backups, uptime, support, customizations / tailoring, and so forth. When you combine that with open source software, I think you create a totally fair, respected and valued business.

**Comment by mojavelinux** [comment]
In other words, the free plan isn't really a plan, it's more of a showroom (aka demo room). It's there so that they can see the service is real and so they can learn whether it is what they are looking for. They could just clone the repo and run it locally, but this just saves them time (and gets them interested with less effort on their part).
