### ISSUE TITLE
Allow nested checklist

### ISSUE THREAD

**Issue by cinhtau** [asciidoctor/asciidoctor.org#416]
You can write checklist like that:

```
- [x] Hardware
- [x] System
- [x] Network
- [x] Database
- [x] Application
```

It gives me this:

- [ ] Hardware
- [ ] System
- [ ] Network
- [ ] Database
- [ ] Application

What if I want to indent or nest network or database to illustrate that it belongs to System. I tried this:

```
- [ ] Hardware
- [ ] System
-- [ ] Network
-- [ ] Database
- [ ] Application
```
but the rendering didn't work.

**Comment by mojavelinux** [comment]
Could you open this the Asciidoctor core issue tracker instead?

https://github.com/asciidoctor/asciidoctor/issues

Thanks!

**Comment by cinhtau** [comment]
Moved to https://github.com/asciidoctor/asciidoctor/issues/1491

**Comment by mojavelinux** [comment]
Thanks!
