### ISSUE TITLE
Document how to override built-in CSS to achieve a custom look

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#422]
There are three ways to override the built-in CSS to achieve a custom look:
1. use docinfo to add additional styles
2. set the path to a custom stylesheet using the `stylesheet` attribute
3. set a path to a hybrid stylesheet using the `stylesheet` attribute

(1) and (2) are partially covered in user manual already, but (3) isn't mentioned. Using (3), you'd create a stylesheet that uses the `@import` directive in CSS to import a base stylesheet then put your own rules below it.

```
@import(asciidoctor.css)
/* your rules here */
```

You can get the asciidoctor.css file by running the following command:

```
echo 'text' | asciidoctor -o tmp.html -a linkcss -a copycss -
```

You could also use the Asciidoctor API to get the asciidoctor.css file:

```
require 'asciidoctor'
Asciidoctor::Stylesheets.instance.write_primary_stylesheet '.'
```

We probably want a section on theming the Asciidoctor HTML output that is separate from using the stylesheet factory. These concerns are mixed right now.

**Comment by jonbullock** [comment]
:+1:

**Comment by Svish** [comment]
Re (3) it should also be documented how to still get the base stylesheet generated/downloaded/outputted when using (in my case) Maven, or similar.

**Comment by obfischer** [comment]
@Svish This would be great. Currently I have to copy `asciidoctor.css` to my project. IMHO `-a copycss` should also copy `asciidoctor.css`.

**Comment by geekq** [comment]
@mojavelinux The "hybrid" css is exactly what I needed. To get it working I had to do slightly different things though.

1. Fix the import statement:

```css
/* File: mywiki.css */
@import 'asciidoctor.css';

/* my rules here */
```

2. Copy original asciidoctor.css manually into the target directory. `-a copycss` didn't do it for me.

3. Provide the name of my css file to the `stylesheet` parameter:

```bash
asciidoctor -r asciidoctor-diagram -a linkcss -a stylesheet=mywiki.css -D publish *.adoc
```

**Comment by MarkusMit** [comment]
I'm currently also struggling with this "hybrid" css. 
`copycss` should be able to handle directories, not only a single file.
![grafik](https://user-images.githubusercontent.com/4478581/59114504-95c66000-8947-11e9-8303-3a6baccafb0f.png)

Took me a while until I figured out that I got this error because I specified a directory instead of a file with `copycss`:
```
org.jruby.exceptions.SystemCallError: (EACCES) Permission denied - <PATH-TO-CSS-FOLDER>
    at org.jruby.RubyIO.read (org/jruby/RubyIO.java:3770)
    at RUBY.read_asset (uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_node.rb:517)
    at RUBY.convert (uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1562)
    at RUBY.convert_file (uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595)
    at org.jruby.RubyIO.open (org/jruby/RubyIO.java:1157)
    at RUBY.convert_file (uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595)
```

--
Also, when embedding CSS (`linkcss=false`), only the custom-css file is embedded, the `@import "asciidoctor.css";` directive is ignored, and therefore the base-stylings are missing.

**Comment by mojavelinux** [comment]
This proposed information can now be found here: https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/#customize-the-default-stylesheet

**Comment by obfischer** [comment]
Thank you very much. Some little text and so much impact!
