### ISSUE TITLE
Documentation on Footer docinfo files needs updating

### ISSUE THREAD

**Issue by noble-grant** [asciidoctor/asciidoctor.org#424]
Section 50.3, Footer docinfo files, in the Asciidoctor User Manual, states that content in the docinfo file is added to the html footer. But as of the change for issue 1503, the docinfo footer content is now placed below the footer div.

**Comment by mojavelinux** [comment]
Thanks for reporting! Would you like to try to update the content?

**Comment by noble-grant** [comment]
I’ll give it a shot! ☺

**Comment by mojavelinux** [comment]
:+1:

**Comment by noble-grant** [comment]
Updated content. See issue 425.

**Comment by mojavelinux** [comment]
Thanks @noble-grant! It's revisions like these that keep the documentation strong and current!

**Comment by jaredmorgs** [comment]
This appears to be incorporated in the documentation @mojavelinux. I'm closing this off.

**Comment by mojavelinux** [comment]
:+1:
