### ISSUE TITLE
To encourage collaboration, enable "Propose a Change" button for each Doc node.

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#429]
= Background 

For the last year, I've been reading through the AsciiDoctor user guide and have noticed some TODO sections that, well, never get done. ;)

I'm not in a position to contribute financially to OpenDevise, however I would love to provide value in docs commits to make the User Experience as stellar as the Asciidoctor framework is.

= Challenge

One thing I've noticed looking at the /docs repo is that as a new contributor it is pretty difficult to find your way to the source file you need to edit. 

For example, if I wanted to tackle http://asciidoctor.org/docs/user-manual/#compared-to-asciidoc, how would I find my way to either:
- the parent file that contains the heading
- the placeholder file that I could edit

= Proposal

The simplest way to get around this issue is to put "Suggest a Fix" buttons/links into each `.adoc` topic which when clicked creates a fork of the file in the contributors' GitHub repo. 

This would remove the need to do the following:

. Find the Asciidoctor docs repo (which in itself isn't totally clear, unless I'm missing something)
. Find the file to edit.
. Fork the file into a patch.
. Make the change.

Instead making the process:

. Click the +Suggest a Fix+ link.
. Make the change.

= Implementation

While it would arguably take longer to do, adding this as a core part of Asciidoctor itself would be _really_ cool. 

One idea that popped into my head was that a config parameter could be specified with the root GitHub/GitLab/Stash/Bitbucket repo name, which is then injected into each file in the book at build time. 

Something like :clone-uri: or :contribute-config:

Or if you are only writing ad-hoc files that still require this functionality, you could add the parameter to each file.

**Comment by jaredmorgs** [comment]
For the record, the Read the Docs site does it like this:

https://github.com/snide/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/breadcrumbs.html

I wonder if we could adapt this into our ecosystem?

**Comment by mojavelinux** [comment]
The docs now have an "Edit this Page" link on every page that guides you through a workflow to contribute a change. This functionality is provided by Antora. Antora does not yet provide this feature for includes, though most of the pages are now individual files with a handful of includes.

If we want a more fine-grained edit link, it will first need to be added to Antora. We are relying on Antora as our framework for docs.
