### ISSUE TITLE
Create a table of all recognized attributes and the accepted values

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#43]
Create a table that catalogs all the attributes recognized by Asciidoctor and the acceptable values. Include a description of each attribute, where it can be specified (cli, document, etc) and under what circumstances.

**Comment by jaredmorgs** [comment]
Looks like @graphitefriction's work on this was the genesis of the Asciidoctor User Guide!

Next question is how would we correlate the full list of attributes available and start a running table of them?

I would say it might be time to trawl the code and highlight which files contain the full set of attributes.

If we can get a full list, then trawl the docs code for long-form explanations, this should allow us to link directly to all related sections.

And fill in the gaps for those attributes that are not covered. So a great cross-checking task to boot.

We could supply a one line description of the attribute then link off to a See <<Section_Name>> for complete attribute usage.

If done right, it could essentially become and Index Appendix.

**Comment by mojavelinux** [comment]
Indeed it was. The lack of a consolidated list of attributes was the driving motivation for writing the Asciidoctor User Manual.

I'd argue that the user manual now covers most of the attributes and that we should follow-up with more specific issues about what to do with that information now that it's in the user manual. The issue we face is that the current table has the wrong focus and scope. It's more of a information dump than an informative guide. But again, I think we should make that the focus of another issue. Perhaps #480 and #481.

**Comment by rockyallen** [comment]
Can this be closed now?

**Comment by mojavelinux** [comment]
Indeed! For those looking for it, see [Appendix A: Catalog of AsciiDoc Attributes](http://asciidoctor.org/docs/user-manual/#attribute-catalog)

Thanks for all your hard work to make this happen!
