### ISSUE TITLE
[docs] Mention asciidoctor-pdf in the PDF section

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#430]
http://asciidoctor.org/docs/user-manual/#pdfs could do with a mention of the http://asciidoctor.org/docs/convert-asciidoc-to-pdf/ option, rather than just the fo version.

This content is contained in the https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc#67-pdfs file.

**Comment by mojavelinux** [comment]
I agree. This section was written before Asciidoctor PDF existed. But now, it's (becoming) the recommended option for PDF creation in the Asciidoctor ecosystem.

**Comment by jaredmorgs** [comment]
I've got a PR I'm about to submit for this. But first, Lunch!

**Comment by mojavelinux** [comment]
Nice!!

**Comment by mojavelinux** [comment]
We may want to consider suggesting an HTML-to-PDF as a strategy for making a PDF. First, it's possible to simply Print to PDF, which uses the print styles that are bundled with the default stylesheet.

Another option is to use a tool that automates this process, such as WeasyPrint. The following thread on the AsciiDoc Python mailinglist describes the use of WeasyPrint.

https://groups.google.com/forum/#!msg/asciidoc/nI5g3j7eNbg/AzjkLSQ-BgAJ

I think a brief mention in the user manual might at least raise awareness that such solutions exist. We'll continue to focus on Asciidoctor PDF as our recommended path, but it's important to keep an eye on other strategies.
