### ISSUE TITLE
[docs] Section Pending "Call To Arms"

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#432]
I think it might be a good idea to persuade readers to consider contributing to the TODO sections.

"Section Pending" suggests the content is under development, whereas it may not be. 

I'm going create a branch that links to individual tickets where we users can discuss scope of the sections and reach a collaborative decision. Tracking them in GitHub issues will keep the information flow transparent, and will allow users to submit PRs against the issue to track progress.

**Comment by mojavelinux** [comment]
Great idea! This also ensures that there is a reference from the issue tracker leading back to those empty sections so that when we are doing project management on the repository we don't forget about them!

**Comment by jaredmorgs** [comment]
https://github.com/asciidoctor/asciidoctor.org/pull/467 contains the fix for this.

**Comment by jaredmorgs** [comment]
This issue is complete.

**Comment by mojavelinux** [comment]
Excellent! Nice work.
