### ISSUE TITLE
"Introduction To Asciidoctor" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#433]
http://asciidoctor.org/docs/user-manual/#introduction-to-asciidoctor is currently available to create content for. 

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc is where this heading is located.

**Comment by mojavelinux** [comment]
At last, there is an introduction page for Asciidoctor. See https://docs.asciidoctor.org/asciidoctor/latest/
