### ISSUE TITLE
"Syntax Quick Start" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#441]
http://asciidoctor.org/docs/user-manual/#syntax-quick-start is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by apj68** [comment]
Hi. . . I'm not sure what was intended here but seems like I'm always running to the document for some quick reminders so I did this section.  I've never contributed and don't know the project that well so if this isn't what you had in mind let me know and I can revise.

[syntax-quickstart.txt](https://github.com/asciidoctor/asciidoctor.org/files/509722/syntax-quickstart.txt)

**Comment by mojavelinux** [comment]
That could be very useful material for this issue as well: https://github.com/asciidoctor/asciidoctor/issues/1573.

Do you find the syntax quick reference useful? http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

**Comment by apj68** [comment]
Ah, ok, that's a great quick reference!  So it leaves me wondering what the purpose of this section is supposed to be.  I'm assuming some subset of the syntax useful for "getting started" but it begs to question -- how broad should that subset be?  Should I just massage the syntax covered in 1573 into this getting started section or is there already a sense of another subset representing the scope of the 
"getting started" syntax?

**Comment by mojavelinux** [comment]
There are now three resources available that provide a quick start / reference for the syntax:

* https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
* https://github.com/asciidoctor/asciidoctor/blob/HEAD/data/reference/syntax.adoc (available via `asciidoctor --help syntax`)
* https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/#comparison-by-example

I'm confident that information covers the original request. As a follow-up, I am going to document the `--help syntax` CLI option more thoroughly as it's hard to find in the docs.
