### ISSUE TITLE
"Attribute conventions" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#444]
http://asciidoctor.org/docs/user-manual/#attribute-conventions is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by jaredmorgs** [comment]
Perhaps describe the difference between in-document attributes and command-line attributes. I know some sections in the guide talk about command-line attributes and sometimes the difference between command-line and in-document attributes can be a little confusing to new folks.

**Comment by mojavelinux** [comment]
That distinction is definitely information we want to centralize and refer
to whenever we speak of assigning attributes. It should save a lot of
redundant explanations.

**Comment by mojavelinux** [comment]
We should probably mention the allowed characters for attributes (or perhaps that needs a dedicated section). The answer is that an attribute:

* must be at least one character
* the first character must be a word character (A-Z, a-z, 0-9 and _); basic latin letters only
* it can have any number of word or hyphen characters following the first character

**Comment by rockyallen** [comment]
As a 'new folk' I definitely do get confused with attributes, possibly because *everything* seems to be an 'attribute'. I would like to have a go at clarifying it - perhaps starting by turning the introductory list in section 13 into a definition list. Is this a good issue to hang those PRs on?

**Comment by jaredmorgs** [comment]
I seem to remember a few other issues that trusted to this as well,
@rockyallen. Including a few ideas about how to structure an attribute
reference.

See if you can find them in the issue tracker. A search for 'attribute'
should surface them.

On Thu, 18 Feb 2016, 08:54 rockyallen <notifications@github.com> wrote:

> As a 'new folk' I definitely do get confused with attributes, possibly
> because *everything* seems to be an 'attribute'. I would like to have a
> go at clarifying it - perhaps starting by turning the introductory list in
> section 13 into a definition list. Is this a good issue to hang those PRs
> on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/444#issuecomment-185446606>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
I'm thrilled that you are taking this on @rockyallen!

When we set out to create the Asciidoctor user manual, one of our key objectives was to make attributes more clear. That's because, in our view, it's the Achilles' heel of the AsciiDoc User Guide. Unfortunately, we haven't yet achieved that objective. But with your help, I'm sure we can do it!

**Comment by mojavelinux** [comment]
Attributes are now introduced here: https://docs.asciidoctor.org/asciidoc/latest/key-concepts/#attributes. That's followed up with detailed pages on document attributes and element attributes starting here: https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes/ and here: https://docs.asciidoctor.org/asciidoc/latest/attributes/element-attributes/

There's still some information to be filled in (look for TBD), I'd rather handle those as discrete issues.
