### ISSUE TITLE
"Basic Document Anatomy" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#445]
http://asciidoctor.org/docs/user-manual/#basic-document-anatomy is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by jaredmorgs** [comment]
I wonder if talking about the differences between an Article and Book could be a good start here. There are other sections in the guide that could potentially be referenced or included in this section. Or, perhaps, paraphrased as a quick reference for new folks.

**Comment by mojavelinux** [comment]
An overview of the document anatomy can now be found here: https://docs.asciidoctor.org/asciidoc/latest/document-structure/ From there, it links to the document types (doctypes) page.
