### ISSUE TITLE
"Ordered Lists Summary" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#446]
http://asciidoctor.org/docs/user-manual/#summary-2 is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by jaredmorgs** [comment]
Perhaps relate this back to how Asciidoctor adds value over other commonly-used authoring tools like MS word (and even Markdown) with relation to the amount of control you have over how ordered list content is controlled by the user.

**Comment by mojavelinux** [comment]
Ordered lists now have a dedicated page in the new docs. See https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/
