### ISSUE TITLE
"Custom Backends" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#451]
http://asciidoctor.org/docs/user-manual/#custom-backends is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by mojavelinux** [comment]
This is probably really a duplicate of #452.

**Comment by jaredmorgs** [comment]
I think you're right, Dan. Develop content on #452 and remove the note for this issue at the same time.
