### ISSUE TITLE
"Creating a backend" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#452]
http://asciidoctor.org/docs/user-manual/#creating-a-backend is currently available to create content for.

Use Issue #80 as the canonical tracker for this issue, which already has a great content starting point outlined by @mojavelinux 

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by mojavelinux** [comment]
I'm on the hook for this one.

**Comment by mojavelinux** [comment]
Also a duplicate of #408.

**Comment by jaredmorgs** [comment]
For the record, #80 is the canonical source of planning for this ticket, and I've updated this issue accordingly. 

Continue all discussion on Issue #80 please. This issue remains open until Issue #80 is resolved, at which point the admonition in the user-manual.adoc can be deleted.

**Comment by mojavelinux** [comment]
This issue has been fused into https://github.com/asciidoctor/asciidoctor/issues/3948.
