### ISSUE TITLE
"Java" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#455]
http://asciidoctor.org/docs/user-manual/#java is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by mojavelinux** [comment]
For now, this should point to the AsciidoctorJ README and upcoming user manual. See https://github.com/asciidoctor/asciidoctorj/blob/master/README.adoc

**Comment by LightGuard** [comment]
We're linking to this issue from the main documentation, we should probably point them to the asciidoctorj readme instead.

**Comment by mojavelinux** [comment]
This link now resolves to the main documentation for AsciidoctorJ.
