### ISSUE TITLE
"Gradle" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#456]
http://asciidoctor.org/docs/user-manual/#gradle is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by mojavelinux** [comment]
For now, this should point to the Asciidoctor Gradle README at https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/development/README.adoc.

**Comment by jaredmorgs** [comment]
Sorry for spamming your email tonight, @mojavelinux ;)

**Comment by mojavelinux** [comment]
Thank you for getting these tracking issues filed!

**Comment by mojavelinux** [comment]
The Gradle plugin now has its own documentation, which can be found by following the link in the description. This content is currently in the process of being migrated to the new docs site. Once it is, the link will redirect to that location instead.
