### ISSUE TITLE
"Maven" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#457]
http://asciidoctor.org/docs/user-manual/#maven is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by mojavelinux** [comment]
For now this should link to the README for the Asciidoctor Maven Plugin at https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/README.adoc

**Comment by rockyallen** [comment]
Should there be a section for Ant integration as well?

**Comment by mojavelinux** [comment]
Absolutely. Can you file a separate issue?

**Comment by jaredmorgs** [comment]
@rockyallen ping me once you do and I'll do a quick change to the user
guide and add in the tracker issue so other folks know where to file
suggestions.

On Wed, 27 Jan 2016 at 07:17 Dan Allen <notifications@github.com> wrote:

> Absolutely. Can you file a separate issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/457#issuecomment-175233701>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
The Maven tools now has its own documentation, which can be found by following the link in the description.
