### ISSUE TITLE
"Yard" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#460]
http://asciidoctor.org/docs/user-manual/#yard is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by mojavelinux** [comment]
I don't think we're going to pursue documentation about YARD. While it's true that YARD supports AsciiDoc content files, it's very unlikely that users will be looking for that information in our docs. Or, if they are looking, let's wait until a specific request is made.

Here's the information about AsciiDoc support in YARD for reference: https://www.rubydoc.info/gems/yard/file/docs/WhatsNew.md#added-asciidoc-markup-type-support-0-8-6
