### ISSUE TITLE
"Rdoc" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#461]
http://asciidoctor.org/docs/user-manual/#rdoc is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by mojavelinux** [comment]
As with YARD, I don't think we're going to document this integration in the Asciidoctor docs. Let's at least wait until someone requests it.
