### ISSUE TITLE
"Migrate from AsciiDoc to Asciidoctor" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#463]
http://asciidoctor.org/docs/user-manual/#migrate-from-asciidoc-to-asciidoctor is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by jaredmorgs** [comment]
Pretty sure I saw something about compatibility with asciidoc that could be used to add to this section.

**Comment by mojavelinux** [comment]
I think we should drop this section. I don't want to draw attention to AsciiDoc Python, and I don't want to make it seem like Asciidoctor isn't AsciiDoc. This guide is about how to write AsciiDoc and convert it with Asciidoctor. I really don't want to put other ideas in people's heads.

**Comment by jaredmorgs** [comment]
So comment it out or completely expunge it from the guide, Dan?

On Sun, 3 Jan 2016 at 10:50 Dan Allen <notifications@github.com> wrote:

> I think we should drop this section. I don't want to draw attention to
> AsciiDoc Python, and I don't want to make it seem like Asciidoctor isn't
> AsciiDoc. This guide is about how to write AsciiDoc and convert it with
> Asciidoctor. I really don't want to put other ideas in people's heads.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/463#issuecomment-168447236>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Expunge.

Keep in mind that a lot of this sections that are pending were just proposed in a rough outline. It's not unlikely that we will decide that some don't belong, like this one.

**Comment by jaredmorgs** [comment]
PR submitted.

On Sun, 3 Jan 2016 at 17:08 Dan Allen <notifications@github.com> wrote:

> Expunge.
>
> Keep in mind that a lot of this sections that are pending were just
> proposed in a rough outline. It's not unlikely that we will decide that
> some don't belong, like this one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/463#issuecomment-168469519>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Thanks! Merged!
