### ISSUE TITLE
"Additional Help" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#464]
http://asciidoctor.org/docs/user-manual/#additional-help is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by jaredmorgs** [comment]
So do we repeat the Getting Help admonition info in the first page of this guide in this topic.

I would think that having the Getting Help info up the top of the guide would be a good move. Burying it down at this level makes it hard to discover.

**Comment by mojavelinux** [comment]
Honestly, I think we should drop this section until we know why it exists. We don't really have a need for it right now (unless you know of one).

**Comment by jaredmorgs** [comment]
I'd agree. Should I just comment it out?

On Sun, 3 Jan 2016 at 10:48 Dan Allen <notifications@github.com> wrote:

> Honestly, I think we should drop this section until we know why it exists.
> We don't really have a need for it right now (unless you know of one).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/464#issuecomment-168447195>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Purge.

**Comment by jaredmorgs** [comment]
PR sent.

On Sun, 3 Jan 2016 at 17:08 Dan Allen <notifications@github.com> wrote:

> Purge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/464#issuecomment-168469524>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Thanks! Merged!
