### ISSUE TITLE
"Glossary" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#465]
http://asciidoctor.org/docs/user-manual/#user-glossary is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by mojavelinux** [comment]
I've added definitions for the following types of attributes:

* document attribute
* header attribute
* block attribute
* macro attribute

I also clarified in the other definitions when we're talking about a document attribute.

**Comment by mojavelinux** [comment]
The glossary is now documented. See https://docs.asciidoctor.org/asciidoc/latest/sections/glossary/
