### ISSUE TITLE
"Unordered Lists Summary" Content Discussion

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#466]
http://asciidoctor.org/docs/user-manual/#summary is currently available to create content for.

Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc

**Comment by jaredmorgs** [comment]
I think the big thing with unordered list functions like check boxes is that users can easily make PDF forms that allow interactivity (to a degree). I think mentioning some potential use cases of checkboxes might inspire readers to use Asciidoctor for task they might have used other services for in the past. 

I know that I made a simple printed survey form to hand out after a training course, for example.

**Comment by ysb33r** [comment]
> While it would seem as though the number of asterisks represents the nesting level, that’s not how depth is determined. A new level is created for each unique marker encountered. However, it’s much more intuitive to follow the convention that the number of asterisks equals the level of nesting. 

This is not very clear. Does this mean that

```
* Level 1
*** Level 2
```

and 

```
* Level 1
- Level 2
```

are both valid ways to get to a second level list?

**Comment by mojavelinux** [comment]
Yes, that is correct. However, the first would go against the recommend style guidelines because it is misleading.

I tend to use the second form a lot if I'm writing a basic list with some clarifications details:

```
* something to note
  - a clarifying details about this note
  - another detail about this note
* something else to note
```

**Comment by mojavelinux** [comment]
Essentially, each unique combination represents a new level. Another way to put it, markers of the same pattern share the same level of nesting.

**Comment by ysb33r** [comment]
Right. Got you. It might be worthwhile these examples as clarifications in the documentation.

**Comment by mojavelinux** [comment]
This information is now captured on the following page in the new docs site. https://docs.asciidoctor.org/asciidoc/latest/lists/unordered/
