### ISSUE TITLE
Document how to specify Apache DocumentRoot relative stylesheet paths

### ISSUE THREAD

**Issue by davidfavor** [asciidoctor/asciidoctor.org#472]
Maybe I'm missing something simple. If there's a way to easily do the following let me know.

There seems to be no incantation to specify external .css file(s) common across an entire website.

The behavior of asciidoctor seems to either error out for incorrect file paths or to copy .css files, so there might be 100s of duplicated files across a large static site.

Neither of these approaches work well using asciidoctor to generate large sites, which link to common .css files, so when any .css modification is made in one place, all *.html files reference this change.

Be nice if there was something like "-a css=file1,file2,file3..." where the emitted HTML is...

```
<link rel="stylesheet" href="/file1.css">
<link rel="stylesheet" href="/file2.css">
<link rel="stylesheet" href="/file3.css">
```

With no checking if these files exist, so paths can be DocumentRoot relative.

Currently I just run asciidoctor output through a filter to accomplish this + be great if there was built rather than hacked into the emitted asciidoctor output.

Thanks for your consideration of this enhancement.

**Comment by mojavelinux** [comment]
The behavior you are looking for is activated using the following three attributes:

* stylesheet - to specify the path to the stylesheet
* linkcss - to specify you want to link to rather than embed the stylesheet
* copycss! - to specify you don't want Asciidoctor to attempt to copy the stylesheet

Therefore, you'd pass the following flag:

```
-a stylesheet=/styles.css -a linkcss -a copycss!
```

If you want to include more than one stylesheet, then you should use the CSS `@import` directive to do this. Thus, in your `styles.css` document, you'd put:

```css
@import "/file1.css";
@import "/file2.css";
@import "/file3.css";
```

This would probably be something worth adding to the user manual.

**Comment by mojavelinux** [comment]
Of course, you can also used docinfo to specify stylesheets instead of using the stylesheet attribute.

```
asciidoctor -a docinfo=private-head -a stylesheet! document.adoc
```

Your document-docinfo.html file would look like:

```html
<link rel="stylesheet" href="/file1.css">
<link rel="stylesheet" href="/file2.css">
<link rel="stylesheet" href="/file3.css">
```

**Comment by mojavelinux** [comment]
Btw, nice to hear from you again, @davidfavor!

**Comment by mojavelinux** [comment]
@jaredmorgs I think this needs to be a new section under http://asciidoctor.org/docs/user-manual/#html. Perhaps "Applying custom stylesheets".

There is a section about applying a custom stylesheet in the stylesheet factory section, but perhaps that can refer back to this new section. This task is independent of whether you are using the stylesheet factory or not. The bottom line is, we have ways to specify how to embed or link to a CSS file, both built-in and via docinfo, and we should make that explicit.

**Comment by mojavelinux** [comment]
And of course the tip about using `@import` in a master CSS file is an important one that is not currently covered.

**Comment by mojavelinux** [comment]
This is covered on the following page in the new docs: https://docs.asciidoctor.org/asciidoctor/latest/html-backend/custom-stylesheet/
