### ISSUE TITLE
Favicon not showing for Chrome Tabs

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#475]
![Docs Site Pinned With No Favicon](https://cloud.githubusercontent.com/assets/952793/12225091/dfd9093c-b84d-11e5-8797-fd41f314dda2.png)

Would it be possible to add a Favicon to the asciidoctor.org site so when you pin tabs you get an idea about what each tab has. Just the Asciidoctor icon would be great for now (I know it is a candidate for re-design).

**Comment by mojavelinux** [comment]
I haven't put it in there because I don't really want to propagate the proposal as a sanctioned icon. We really need to resolve that issue so that we do have one, and one to which we have rights. So the focus should be on solving the design issue. At this point, I'm open to contracting out the work or facilitating a competition.

**Comment by jaredmorgs** [comment]
Sound good to me. Getting an identity for Asciidoctor is a big step in
being able to promote it consistenty.

Also, I want a Asciidoctor shirt. ;)

On Mon, 11 Jan 2016 at 10:33 Dan Allen <notifications@github.com> wrote:

> I haven't put it in there because I don't really want to propagate the
> proposal as a sanctioned icon. We really need to resolve that issue so that
> we do have one, and one to which we have rights. So the focus should be on
> solving the design issue. At this point, I'm open to contracting out the
> work or facilitating a competition.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/475#issuecomment-170409988>
> .
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
And on the subject of outsourcing vs competition, I'd go with competition
first.

Getting community involved seems like a great fit. I know asking graphic
designers to design a "free" logo is often met with resistance, but a
competition could be a great way of offering some value to the work.

On Mon, 11 Jan 2016 at 11:05 Jared Morgan <jaredleonmorgan@gmail.com> wrote:

> Sound good to me. Getting an identity for Asciidoctor is a big step in
> being able to promote it consistenty.
>
> Also, I want a Asciidoctor shirt. ;)
>
> On Mon, 11 Jan 2016 at 10:33 Dan Allen <notifications@github.com> wrote:
>
>> I haven't put it in there because I don't really want to propagate the
>> proposal as a sanctioned icon. We really need to resolve that issue so that
>> we do have one, and one to which we have rights. So the focus should be on
>> solving the design issue. At this point, I'm open to contracting out the
>> work or facilitating a competition.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/asciidoctor/asciidoctor.org/issues/475#issuecomment-170409988>
>> .
>>
> --
>
> Sent from Mobile.
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
This has long since been resolved. And we're quite proud of our snazzy logo.
