### ISSUE TITLE
Document SVG embedding options for HTML5 converter

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#476]
Document the SVG embedding options for the HTML5 converter.
- _no option_ (default)
- interactive
- inline

Note that when using inline, there are several requirements that must be met in order for the SVG to work properly when included inside an HTML5 document.
- the primary SVG elements (e.g., `<svg>`) cannot have a namespace
- ideally the SVG should be optimized to minimize the content being put into the HTML document

When using inline or interactive, the following requirements must be satisified:
- the `viewBox` attribute must be defined on the `<svg>` element for scaling to work properly

When using the inline option, if you specify a width or height in the image macro in AsciiDoc, the width and height attributes on the `<svg>` element will be removed.

For more details, see https://github.com/asciidoctor/asciidoctor/issues/1301.

**Comment by mojavelinux** [comment]
Here's most of the raw material on this subject:

https://github.com/asciidoctor/asciidoctor-bespoke#inserting-svgs

(The Bespoke.js converter supports the same insertion methods as the built-in HTML converter).

**Comment by krOoze** [comment]
I can't figure out how to make it work for SVG image icons. `icon:myicon[opts=inline]` does not seem to work. Also how to add the option to admonition icons?

**Comment by mojavelinux** [comment]
The correct syntax would be:

```
image:myicon.svg[opts=inline]
```

The icon macro is something separate.
