### ISSUE TITLE
Icons not rendering

### ISSUE THREAD

**Issue by gristel** [asciidoctor/asciidoctor.org#498]
As you have probably already noticed, the NOTE: admonition icon does not render on the icon-intro.adoc page here.
The same problem occurs on gitbook.
Is there any way to fix this?

Thanks!

**Comment by mojavelinux** [comment]
Icons do not render when viewing a AsciiDoc file directly on GitHub. Please file an issue in https://github.com/github/markup to request that support as there's nothing we can do about it otherwise. If you have an issue with gitbook, you should file it in that appropriate repository.
