### ISSUE TITLE
Use attribute name instead of attribute reference in table of predefined attributes

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#513]
Currently, the table of predefined attributes for character replacement shows the attribute reference (e.g., `{lt}`) instead of the attribute name (e.g., `lt`). This differs from the other attribute tables. I think we should be consistent and only show the attribute name.

cc: @rockyallen

**Comment by rockyallen** [comment]
Agreed. Please assign to me.

**Comment by rockyallen** [comment]
See PR #514

**Comment by marcekowalski** [comment]
How do I do I unsubscribe from this list?

Marc E. Kowalski, Ph.D.
(650)387-6973
m.e.kowalski@ieee.org

**Comment by mojavelinux** [comment]
It's not a list but rather a notification system. You can disable notifications here:

* https://github.com/settings/notifications

(you are likely "watching" the repository, which is the notification setting you'll want to adjust).

You can unwatch repositories from this page:

* https://github.com/watching

**Comment by mojavelinux** [comment]
Resolved by 36a1af65a039df7fecb67bc675fadd8c36a60230.
