### ISSUE TITLE
Migrate blog to HubPress

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#520]
To make the blog easier to maintain, more user-friendly for contributing authors, and to support our own ecosystem, I think we should migrate the blog to HubPress.io.

This change involves the following steps:
- setup up HubPress in the Asciidoctor organization (blog.asciidoctor.org)
- customize the stylesheet to fit with the theme of the project (or define a new theme)
- import existing posts (attempt to save comments if possible)
- add a DNS record to point to blog.asciidoctor.org running on GitHub Pages
- update links on asciidoctor.org (or add redirects)

We'll run the blog out of a separate repository and redirect http://asciidoctor.org/news to blog.asciidoctor.org (or news.asciidoctor.org).

**Comment by mojavelinux** [comment]
cc: @anthonny @jaredmorgs 

Time permitting, I'm ready to make this change now. The blog has been experiencing a lull for awhile, so there's nothing getting in the way. I would like to use the development version (either now or when it's ready).

**Comment by jaredmorgs** [comment]
Let me know if you want a hand. Considering the posts are in Asciidoctor
format already, migration should be trivial.

Just need to specify some custom HubPress attributes to control post dates.
Anthonny is cooking up multi user support, so that will help with
federating posts between defined writers.

On Mon, 29 Feb 2016, 10:51 Dan Allen <notifications@github.com> wrote:

> cc: @anthonny <https://github.com/anthonny> @jaredmorgs
> <https://github.com/jaredmorgs>
>
> Time permitting, I'm ready to make this change now. The blog has been
> experiencing a lull for awhile, so there's nothing getting in the way. I
> would like to use the development version (either now or when it's ready).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/520#issuecomment-189981990>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
> Anthonny is cooking up multi user support

That is going to be the killer feature and precisely why this will be the perfect solution for us.

**Comment by jaredmorgs** [comment]
Making HubPress an orchestrator will be a huge advantage as well.

On Mon, 29 Feb 2016, 11:11 Dan Allen <notifications@github.com> wrote:

> Anthonny is cooking up multi user support
>
> That is going to be the killer feature and precisely why this will be the
> perfect solution for us.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/520#issuecomment-189986771>
> .
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
Is this something we can begin to do now, @anthonny ? Or is the new version
not ready for proper blogging yet?

On Mon, 29 Feb 2016, 11:12 Jared Morgan <jaredleonmorgan@gmail.com> wrote:

> Making HubPress an orchestrator will be a huge advantage as well.
>
> On Mon, 29 Feb 2016, 11:11 Dan Allen <notifications@github.com> wrote:
>
>> Anthonny is cooking up multi user support
>>
>> That is going to be the killer feature and precisely why this will be the
>> perfect solution for us.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/asciidoctor/asciidoctor.org/issues/520#issuecomment-189986771>
>> .
>>
> --
>
> Sent from Mobile.
>
-- 

Sent from Mobile.

**Comment by anthonny** [comment]
I think we must wait for the next release and @jaredmorgs you know that it will be soon :smile: 
But we can already work on the repository structure and theme.
@mojavelinux we can already fix the domain and create the DNS record, so when the blog will be ready, we won't have to wait.

**Comment by anthonny** [comment]
> I think we must wait for the next release

Finally not sure :smile: , we can already work on the current version, upgrade when the next version will be available and then communicate.

> setup up HubPress in the Asciidoctor organization (blog.asciidoctor.org)
   blog.asciidoctor.org (or news.asciidoctor.org)

@mojavelinux blog or news ? :)

**Comment by marco-m** [comment]
Hello any news ?
