### ISSUE TITLE
Move social links to the footer

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.org#521]
I think we should move "social" links to the footer:

![footer](https://cloud.githubusercontent.com/assets/333276/13397313/a91a02b6-def9-11e5-8ee2-91b819565ead.png)

**Comment by jaredmorgs** [comment]
That's a logical place for them. :+1:

On Tue, 1 Mar 2016, 00:35 Guillaume Grossetie <notifications@github.com>
wrote:

> I think we should move "social" links to the footer:
>
> [image: footer]
> <https://cloud.githubusercontent.com/assets/333276/13397313/a91a02b6-def9-11e5-8ee2-91b819565ead.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/521>.
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
I agree. We may need to work a bit on making it look cleaner. Perhaps split it into two columns, one for development and one for social/media. wdyt?

Any references you can provide to sites you think do it well would be helpful. However, we can add it first then refine it in subsequent commits.

While we're at it, we should switch the Freenode chat to Gitter since that's where we are chatting these days.

**Comment by Mogztter** [comment]
Here's a few references (but this is a very common practice):

![airbnb](https://cloud.githubusercontent.com/assets/333276/13426872/b4a4f2d2-dfb0-11e5-9e3f-49a8524d8f5a.JPG)
![redhat](https://cloud.githubusercontent.com/assets/333276/13426875/b4a54336-dfb0-11e5-909f-e0e136448d4b.JPG)
![jetbrains](https://cloud.githubusercontent.com/assets/333276/13426873/b4a4fb74-dfb0-11e5-8ff7-4069f7339d37.JPG)
![groovy](https://cloud.githubusercontent.com/assets/333276/13426874/b4a529fa-dfb0-11e5-8d8f-00b6bf3ce897.JPG)

If we only use an icon we could put everything on one line. But in our case I don't think this is the best approach, simply because Nabble and IRC icon are not common enough. GitHub, Twitter and Google+ (and maybe Gitter) are good candidate though.

> Perhaps split it into two columns, one for development and one for social/media

Download badge and GitHub are development and the rest social/media ?

**Comment by Mogztter** [comment]
@mojavelinux @jaredmorgs I've just created a pull request so we can make some adjustments before merging

**Comment by jaredmorgs** [comment]
OK I'll check it out tomorrow evening unless Dan beats me to it. 👍

On Sun, 6 Mar 2016, 08:32 Guillaume Grossetie <notifications@github.com>
wrote:

> @mojavelinux <https://github.com/mojavelinux> @jaredmorgs
> <https://github.com/jaredmorgs> I've just created a pull request so we
> can make some adjustments before merging
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/521#issuecomment-192753004>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
I think we've got something that looks reasonable now.
