### ISSUE TITLE
Document how to create a manpage from AsciiDoc

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#538]
Asciidoctor has a built-in converter for creating a Linux manual page (manpage). However, it requires that the AsciiDoc source adhere to a specific structure. Explain the parts of that structure and the various options for customizing the manpage output.

**Comment by rockyallen** [comment]
Suggested changes:

Section 15 DocTypes
---------------------------
1. Explain there is now a manpage backend as well (preferred to doctype)
2. Refer forward to Section 71 Man pages

Section 71 Man pages
----------------------------
1. Introduction blurs manpage for linux (.roff format) and manpage lookalike (.html/.pdf); Clarify. 
2. Link to linux man/roff documentation: http://man7.org/linux/man-pages/man7/roff.7.html
3. Provide example command lines for:

* roff
* html
* pdf

4. Expand on the function of the attributes-use asciidoc manual for source material http://www.methods.co.nz/asciidoc/userguide.html#X1
5. Possibly repeat the manpage part of table A.2
6. Possibly include annotated example(s)

Table A.2  Built in attributes
-----------------------------------
Make "Metadata for manpage output." more specific.

Does this sound right?

**Comment by mojavelinux** [comment]
When converting a man page, the doctype is always required to be set to `manpage`. It's just that when doctype is `manpage`, a new backend keyword becomes available, which is also named `manpage`. It's fine to use all the other converters as well when the doctype is `manpage`.

To put it another way, the manpage doctype opens up a new converter option (aka backend), manpage.

So the doctype is never ignored.

The native PDF support has never been tested with the manpage doctype. I'm sure it will convert, it just may not match the output of the docbook to fopub/a2x pipeline.

> Possibly repeat the manpage part of table A.2

We'll need to figure out how best to use parts of those tables (or link directly to a subsection) to avoid duplication.

Other than that, :+1:

**Comment by rockyallen** [comment]
Closed by commit #567 ?

**Comment by mojavelinux** [comment]
Indeed. Thanks for catching this!

Btw, did you see that I updated the example with a little bit of fun? http://asciidoctor.org/docs/user-manual/#man-pages
