### ISSUE TITLE
Use consistent capitalization for section titles in user manual

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#539]
The user manual uses a mix of title and sentence capitalization for section titles. We need to pick one and be consistent.

**Comment by mojavelinux** [comment]
The trend in software documentation appears to be to use title capitalization. @jaredmorgs, @rockyallen what do you think?

**Comment by jaredmorgs** [comment]
I'd suggest Title Case is the way to go for headings. It's easy to make it
consistent, and looks good in the TOC.

Do we want to adopt the same standard for Captions, etc as well. Or leave
those as sentence case?

On Wed, 9 Mar 2016, 15:29 Dan Allen <notifications@github.com> wrote:

> The trend in software documentation appears to be to use title
> capitalization. @jaredmorgs <https://github.com/jaredmorgs>, @rockyallen
> <https://github.com/rockyallen> what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/539#issuecomment-194119825>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
I like sentence capitalization for captions. I'm in agreement with you about the section titles.

**Comment by jaredmorgs** [comment]
I agree we should leave captions as sentence case.

On Wed, 9 Mar 2016, 16:35 Dan Allen <notifications@github.com> wrote:

> I like sentence capitalization for captions. I'm in agreement with you
> about the section titles.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/539#issuecomment-194139827>
> .
>
-- 

Sent from Mobile.
