### ISSUE TITLE
Use terminology for attributes consistently

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#545]
* Add new terms to glossary: Environment, User defined, built-in, predefined

In section 13.0 (list)
* Add Environment 
* Use Predefined instead of intrinsic
* Add built-in
* Add user defined? (and a corresponding glossary entry, no other detail needed)
* Remove attribute entry? It is not a category, it is the syntax for setting and unsetting  any sort of attribute from inside the document.
* In 13.3 remove the word intrinsic entirely; in this context it means no more than the default value of the predefined attributes.
* Rename 13.5 to Environment Attributes

Do a search to catch any other uses

**Comment by mojavelinux** [comment]
:+1:

For clarity, I'm including the glossary entries we had in the other issue:

* **built-in** - reserved attributes used to control processing, integrations, styling and i18n
* **environment** - dynamic attributes that pertain to or give information about the runtime environment
* **predefined** - convenience attributes intended primarily for content replacements
* **user-defined** - attributes defined by the content author for storing reusable or centrally managed content

> Remove attribute entry? It is not a category, it is the syntax for setting and unsetting any sort of attribute from inside the document.

Correct. Except it's for setting or unsetting document (aka document-scoped) attributes.

**Comment by mojavelinux** [comment]
This change is really going to bring a ton of clarity to the user manual. I'd even go so far to say that changes like this put us well on our way towards defining/drafting the UniDoc specification.

**Comment by jaredmorgs** [comment]
This will be awesome!

On Sun, 13 Mar 2016, 19:23 Dan Allen <notifications@github.com> wrote:

> This change is really going to bring a ton of clarity to the user manual.
> I'd even go so far to say that changes like this put us well on our way
> towards defining/drafting the UniDoc specification.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/545#issuecomment-195920028>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Thanks @rockyallen! This is an important step forward.

Upon reading through the Attributes section again, I think there's still some confusion between document attributes and element attributes. We should make this distinction very clear.

In general, Asciidoctor uses attributes as a way to store and deliver metadata. Document attributes are available everywhere and are used to control behavior of the document (they have a broad scope). Element attributes are specifically for controlling an individual element and are scoped to that element. Unlike document attributes, element attributes *cannot* be referenced using an attribute reference (though, that could change in UniDoc).

Element here refers to a node or a directive. A node is a paragraph, a delimited block, a block macro, an inline macro or a span of formatted text. (maybe that needs to go in the glossary).

So I think we need a new issue that has a focus of making a clear distinction between document attributes and element attributes.
