### ISSUE TITLE
Document the importance of the graphic format file extension when embedding images. [core]

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#551]
asciidoctor/asciidoctor#1455 contains a suggestion that will help users embed images correctly and avoid validator errors when they process their content.

_Next Actions_
- review the content/suggestions in asciidoctor/asciidoctor#1455.
- add a note to the images section about the importance of the graphic file extension.

**Comment by mojavelinux** [comment]
The format attribute on image macros is now documented here: https://docs.asciidoctor.org/asciidoc/latest/macros/image-format/
