### ISSUE TITLE
Document how to accommodate pipes in table cell contents. [core]

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor.org#552]
asciidoctor/asciidoctor#1421 suggests a way to work around an issue with content containing the pipe `|` symbol in table cells.

A common case where this is a problem is when you are trying to include `grep` statements in cells as examples, and the pipe confuses the processor into thinking the content after the pipe is intended as a new cell.

Defining a custom cell separator will permit content containing pipe symbols to be processed correctly.

Next Actions:
- review the content/suggestions in asciidoctor/asciidoctor#1559.
- incorporate the cited example into a new section of the Tables section
- maybe document in http://asciidoctor.org/docs/user-manual/#summary-tables.

**Comment by mojavelinux** [comment]
The advice here is plain and simple. The pipe getting in the way? Just pick another character. An excellent choice is the broken vertical bar. It does require a special key combination to type (`¦`), but it keeps the overall appearance very similar.

There's not a clear place where this fits in. Perhaps a new subsection above "DSV and CSV Data Formats" named "Customizing the Cell Separator" (we can always move it around later). Note that this only applies for PSV, though it transitions nicely into DSV and CSV, which also use different separator characters.

(NOTE: the separator attribute is already documented in the summary table).

**Comment by mojavelinux** [comment]
This information is now covered in the following section: https://docs.asciidoctor.org/asciidoc/latest/tables/data-format/#escape-the-cell-separator

If you have an idea of how to improve the explanation, please click "Edit this Page" in the upper right and submit a proposed change.
