### ISSUE TITLE
Clarify difference between document attributes and element attributes

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#558]
...there's still some confusion between document attributes and element attributes. We should make this distinction very clear.

In general, Asciidoctor uses attributes as a way to store and deliver metadata. Document attributes are available everywhere and are used to control behavior of the document (they have a broad scope). Element attributes are specifically for controlling an individual element and are scoped to that element. Unlike document attributes, element attributes cannot be referenced using an attribute reference (though, that could change in UniDoc).

Element here refers to a node or a directive. A node is a paragraph, a delimited block, a block macro, an inline macro or a span of formatted text. (maybe that needs to go in the glossary).

**Comment by mojavelinux** [comment]
I'm confident this information is now covered in the new docs site, mostly notably in this section: https://docs.asciidoctor.org/asciidoc/latest/key-concepts/#attributes If you think information is still missing, I encourage you to click "Edit this Page" and make a suggestion (or edit the content locally and submit an MR to that location).
