### ISSUE TITLE
Create a catalog of options

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#562]
As a parallel to the catalog of (document) attributes, the user manual should also have a catalog of options. Options are used to control how the processor itself is configured (as opposed to the content). Options handle the following tasks:

* Specify the converter to use
* Set the safe mode
* Require additional libraries
* Control the path from which libraries and other resources are loaded
* Tune the verbosity of messages
* Set the input and output files or directories
* Set the base directory

Most options are available when using both the CLI and the API, though each interface also has unique options.

**Comment by mojavelinux** [comment]
Here's a first cut at the list. API options start with a colon. CLI options start with a hyphen.

Shared:

* :attributes, -a, --attribute (sets document attributes from the CLI or API)
* :base_dir, -B, --base-dir
* :header_footer, -s, --no-header-footer (API and CLI have inverted default values)
* :safe, -S, --safe-mode
* :to_file, -o, --out-file
* :to_dir, -D, --destination-dir
* :timings, -t, --timings
* :template_dir, -T, --template-dir
* :template_engine, -E, --template-engine
* :eruby, -e, --eruby
* :backend, -b, --backend
* :doctype, -d, --doctype


API:

* :mkdirs
* :parse
* :template_cache
* :template_engine_options
* :converter
* :sourcemap
* :catalog_assets
* :extensions
* :extensions_registry

CLI:

* -h, --help
* -V, -v (if only argument), --version
* -v, --verbose
* --trace
* -q, --quiet
* -r, --require
* -I, --load-path
* -n, --section-numbers

**Comment by andya9** [comment]
Would it be possible to just call the cli options from the man page?

**Comment by rockyallen** [comment]
I don't think the CLI and API should be treated together, if that is what you are suggesting. The users for each section are completely different. Perhaps include the man page as annex B, and add a separate table for API options in a new section 86?

**Comment by mojavelinux** [comment]
I agree. These are separate audiences. I do think that it's useful to draw a correlation between the CLI and API options that are shared, but that's really just an insight, not an instruction.

I don't think we need to include the whole man page. We just need the sections up to and including the options. (How to actually do that remains a challenge since it doesn't have any include tags). Either way, yes, the man page should be an appendix.

I think the API options should either be another appendix (i.e., "Appendix B: API Options") or a new section under the part "Using Asciidoctor's API". We should link to this section from 3.2, "Using the Ruby API."

**Comment by rockyallen** [comment]
Comments addressed.
Links added from CLI and API.
Noticed missing cell in built-in attributes table; does not affect output but generated warnings

**Comment by mojavelinux** [comment]
> Noticed missing cell in built-in attributes table; does not affect output but generated warnings

I just fixed that in master. Thanks for pointing that out.

**Comment by mojavelinux** [comment]
The first draft is now published! If you see anything that needs to be immediately updated, feel free to follow-up here. Otherwise, let's track changes an improvements in dedicated issues.

Thanks @rockyallen!
