### ISSUE TITLE
Unicode admonition icons

### ISSUE THREAD

**Issue by sanmai-NL** [asciidoctor/asciidoctor.org#571]
In addition to the current [Font Awesome](https://fortawesome.github.io/Font-Awesome/) based icons, I propose that Unicode character icons be supported.

The Font Awesome icons do not render in documents hosted on GitHub or on my local filesystem. Based on experience outside the AsciiDoctor context, using Font Awesome adds bloat.

Unicode icons are sometimes also rendered with nice colors in browsers, and are probably easy to support.

**Comment by mojavelinux** [comment]
As it turns out, this is already supported. I've using something similar on GitHub. You simply set the caption attribute for each admonition to any text you want.

For example:

```
= Document Title
:tip-caption: 💡

TIP: You can set an admonition icon to any Unicode character or sequence of characters using the caption attributes.
```

You can use a passthrough to add styles to it:

```
:tip-caption: pass:[<span style="font-size: 2em">💡</span>]
```

We've been discussing how to enable alternate strategies for font-based icons in the following issue: https://github.com/asciidoctor/asciidoctor/issues/539

**Comment by mojavelinux** [comment]
I'd also like to see if we can allow SVG icons instead of font-based icons.

**Comment by sanmai-NL** [comment]
Great, thanks for pointing it out! Is this in a manual somewhere?

For anyone who's interested, here a possible way to use Unicode glyphs.

```
:caution-caption: ☠
:important-caption: ❗
:note-caption: 🛈
:tip-caption: 💡
:warning-caption: ⚠

CAUTION: Caution.

IMPORTANT: Important.

NOTE: Note.

TIP: Tip.

WARNING: Warning.
```

Currently, GitHub (or my present browser, Chrome 49.0.2623.112 64-bit?) seems to not detect the `CAUTION`, `NOTE` and `WARNING` glyphs and render them with colors, even though the same code points were used as for the GitHub emoji syntax (e.g., :warning:). Would it be possible to harmonize the Unicode glyphs used for admonitions, based on a single AsciiDoctor configuration option in the document header? This would prevent people from accidentally choosing all kinds of different glyphs, hurting AsciiDoctor document usability across GitHub in terms of consistent visual communication.

**Comment by mojavelinux** [comment]
> Great, thanks for pointing it out! Is this in a manual somewhere?

Not yet. I only figured it out myself last week :)

> Would it be possible to harmonize the code points used for admonitions. This would prevent people from accidentally choosing all kinds of different ones, hurting AsciiDoctor document usability across GitHub in terms of consistent visual communication.

Possibly. I think we're still in the age of discovery at the moment. Figuring out what works, what doesn't. Once it becomes very clear what we want (and how it will work), then we can start working towards a solution. Very likely, we'll use something like `:icons: glyph`.

As for what GitHub is currently doing, I have no idea. That's kind of the crazy state of emoji at the moment. You get wildly different results depending on where you use these glyphs. I'm sure things will start to settle over the next year as they become more widely adopted.

**Comment by mojavelinux** [comment]
I've documented this trick in the admonition icons section in the user manual.
