### ISSUE TITLE
Add icontype to built-in attribute table

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#580]
From the manual:

"The file resolution strategy when using image-based icons is the same used to locate images for the admonition icons. The file extension is set using the icontype attribute, which defaults to PNG (png)."

Links to #inline-icons

The relationship between inline icons and admonition icons is not obvious. Do 'icons' and 'icontype' apply to both? Is it not possible to use built-in icons for admonitions, but font icons for inlines?

**Comment by mojavelinux** [comment]
Nice catch!

> "which defaults to PNG (png)."

We should just say "defaults to png" and leave it at that.

> The relationship between inline icons and admonition icons is not obvious.

Admonition icons are simply inline icons with a predetermined name. The name is the name of the admonition type in lower case. (e.g., tip).

> Do 'icons' and 'icontype' apply to both?

Yes, both pass through the icon_uri helper method, which gives the same treatment to both. The icon_uri is only used with the `icons` document attribute is set to an empty value.

>  Is it not possible to use built-in icons for admonitions, but font icons for inlines?

Currently, the processor only supports a single icon strategy at a time. The way to work around this is to toggle the `icons` attribute midstream in the document (i.e, toggling it on and off), but that is not recommended.

**Comment by rockyallen** [comment]
See PR #581

**Comment by mojavelinux** [comment]
Merged as 154d1353a497b3e0bb55c00217e4dd7cac3a8c68. Thanks!
