### ISSUE TITLE
/news page is in French

### ISSUE THREAD

**Issue by sanmai-NL** [asciidoctor/asciidoctor.org#594]
The page http://asciidoctor.org/news/ displays a lengthy French-spoken blog post. I think it surprises users that the ‘news’ page of an English-spoken website contains this content. I suggest that your put this on a French-spoken edition of the website/blog or link to it with a summary in English. I was more looking for release announcements BTW.

**Comment by mojavelinux** [comment]
If you want release announcements, you can follow the release tag: http://asciidoctor.org/news/tag/release/

I agree that the French post can be surprising to non-French speakers. However, many of the users in our ecosystem do speak French and this post is there to reach out to them. We are an equal opportunity community, so I don't want to shove the French posts off into a corner.

One idea would be to hide the post in JavaScript if the browser does not list French as one of the accept languages.

**Comment by mojavelinux** [comment]
Proposal implemented.

**Comment by sanmai-NL** [comment]
Thanks, great! Very good to tailor your content to the preferred language of the user.
