### ISSUE TITLE
Include Directive rendered as link on github

### ISSUE THREAD

**Issue by viveksachdeva** [asciidoctor/asciidoctor.org#596]
Example Page:
https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/asciidoc-syntax-quick-reference.adoc

Here,
include::{includedir}/ex-text.adoc[tags=b-para]
is rendered as a link to the page above rather than including the content of the document.

Am I missing something here?

**Comment by mojavelinux** [comment]
GitHub does not support the include directive for security reasons. Instead, it converts the include to a link (as the result of running Asciidoctor in secure mode). I mention this in the following post http://asciidoctor.org/news/2014/02/04/github-asciidoctor-0.1.4-upgrade-5-things-to-know/#3-swap-an-include-for-a-link

**Comment by mojavelinux** [comment]
We can't control what GitHub does. Please direct further comments to this issue: https://github.com/github/markup/issues/1095
