### ISSUE TITLE
Enhanced CSS styling

### ISSUE THREAD

**Issue by darshandsoni** [asciidoctor/asciidoctor.org#597]
Asciidoctor makes it very easy to change the default look by including a stylesheet. But many users would not be familiar with this / don't want to get into CSS. This repository explains how styling works, allows users to browse through some popular stylesheets and has an API to allow them to test it out before using it in their documentation.
Check out [asciidoctor-skins](https://github.com/darshandsoni/asciidoctor-skins)
- [x] Reword description to avoid criticising the default stylesheet - it fulfills it's purpose well and this repo simply gives users more choice, should they want it.
- [ ] Catalog this as a suggestion on the [docs page](http://asciidoctor.org/docs/#get-started-with-asciidoctor).
- [ ] Decide whether to update the [stylesheet factory](http://asciidoctor.org/docs/produce-custom-themes-using-asciidoctor-stylesheet-factory/) or create a new page about this.

**Comment by darshandsoni** [comment]
@mojavelinux I have added a note within the stylesheet factory page, instead of creating a new one. My rationale is that anyone who is interested in a custom theme would go there first and can then find a choice of what they want. Creating a separate page about it would not really be necessary as the repository itself also gives a description. In addition, I wouldn't want to impose a burden on the asciidoctor team to update the docs, any readme updates can happen on the repository itself. What do you think?

**Comment by mojavelinux** [comment]
The documentation now recommends the Asciidoctor Skins project for anyone interested in themes for the Asciidoctor HTML output. See https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/#are-there-different-themes

If you'd like to propose additional information to share on that page (or a neighboring page), click the "Edit this Page" button and submit your proposal.
