### ISSUE TITLE
Is there a way to spread footnotes over several lines? If so please add it to the docs

### ISSUE THREAD

**Issue by fusion809** [asciidoctor/asciidoctor.org#599]
Hi,

I was wondering if there's a way to spread footnotes out, separating separate key points using new, line-separated, paragraphs. I have tried adding the `<br/>` and `\n` codes from HTML / JS, in the hope that this code will be left unrendered by asciidoctor and just passed on to the final HTML rendering of my asciidoc file, but it wasn't. So how does one insert new lines into footnotes? If this ability does exist, I would recommend that it be added to the documentation.

Thanks for your time,
Brenton

**Comment by mojavelinux** [comment]
This is kind of going outside of what a footnote was designed for. However, it is possible. Here's how you'd need to write it.

```
Text.footnote:[pass:a,p[This footnote +
spans multiple lines. +
{blank} +
Here's another forced paragraph.]]
```

The "a,p" is shorthand for "attributes, post_replacements".

**Comment by mojavelinux** [comment]
For general questions about Asciidoctor, I'd prefer that you use the discussion list at discuss.asciidoctor.org. Thanks!

**Comment by lurch** [comment]
See also https://discuss.asciidoctor.org/footnotes-with-paragraph-breaks-td4130.html

**Comment by mojavelinux** [comment]
Good find. Let's leave it at that reference.
