### ISSUE TITLE
Document new docinfo values and docinfodir

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#604]
Document the new docinfo attribute values and explain how to control which directory is searched using the docinfodir attribute.

Refer to the following issues:
- https://github.com/asciidoctor/asciidoctor/issues/511
- https://github.com/asciidoctor/asciidoctor/issues/1510

The documentation for the docinfo1 and docinfo2 attributes should be removed.

**Comment by rockyallen** [comment]
See PR #626.
I haven't removed the old attributes entirely, because this is the first time many users have seen the new ones. Instead I have moved them into a note about transitioning.

**Comment by mojavelinux** [comment]
:+1:
