### ISSUE TITLE
rename 'mysample.adoc' to 'sample.adoc'

### ISSUE THREAD

**Issue by edusantana** [asciidoctor/asciidoctor.org#606]
When we are reading [Produce Custom Themes Using the Asciidoctor Stylesheet Factory](http://asciidoctor.org/docs/produce-custom-themes-using-asciidoctor-stylesheet-factory/) we have instructions to create a file `sample.adoc`. Latter on, at [Apply a custom theme section](http://asciidoctor.org/docs/produce-custom-themes-using-asciidoctor-stylesheet-factory/#apply-a-custom-theme) we are asked to use a custom theme with the file `mysample.adoc`.

Since we have being copying and pasting commands, it would be better to use only `sample.adoc`.

I can create a PR, but I don't understand the instruction to *set the stylesheet* yet:

    Alternatively, let’s set the stylesheet attribute in the header of mysample.adoc.

    link:mysample-stylesheet.adoc[]

**Comment by mojavelinux** [comment]
The files seem to have gotten out of sync. We'll have to stick with mysample.adoc since that's what all the screenshots use.

I've sent PR https://github.com/asciidoctor/asciidoctor.org/pull/607 to address the issue.
