### ISSUE TITLE
Some attributes must me set from command line

### ISSUE THREAD

**Issue by edusantana** [asciidoctor/asciidoctor.org#608]
There are some attributes that must be set from command line:

File **off-line.adoc**:

```
== Links off-line
:linkattrs:
:nofooter:
:linkcss:
:iconfont-remote!:
:stylesdir: css
:stylesheet: asciidoctor2.css
:icons: font

Content here.
```

If I run:

    asciidoctor off-line.adoc

The expected intent was to include css/asciidoctor2.css as: `<link rel="stylesheet" href="css/asciidoctor2.css">`

But I end up with a embedded style:

```
<style>
/* Asciidoctor default stylesheet | MIT License | http://asciidoctor.org */ 
(...)
</style>
```

But it I run 

    asciidoctor -a stylesheet=asciidoctor2.css -a stylesdir=css -a linkcss off-line.adoc

It works!

I think it's related to https://github.com/asciidoctor/asciidoctor.org/issues/578

**Comment by mojavelinux** [comment]
The only attributes the must be specified from the commandline or via the API are the "secure attributes", which are identified in this table: http://asciidoctor.org/docs/user-manual/#builtin-attributes

The problem you are having is that you are trying to set header-only attributes outside of the document header. A document header either starts with a doctitle:

```
= Links off-line
:linkattrs:
:nofooter:
:linkcss:
:iconfont-remote!:
:stylesdir: css
:stylesheet: asciidoctor2.css
:icons: font

Content here.
```

or a list of attribute entries:

```
:linkattrs:
:nofooter:
:linkcss:
:iconfont-remote!:
:stylesdir: css
:stylesheet: asciidoctor2.css
:icons: font

== Links off-line

Content here.
```

**Comment by mojavelinux** [comment]
A second-level heading is not a valid document header.
