### ISSUE TITLE
Create default start header for Docs

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#61]
It's time to iterate over all the published Docs Headers and create a default header that can be pasted in as a good starting point when a new guide is created.
This will minimize the need to come up with link names that are used repeatedly and make sure each guide has the right attributes for the website stylesheet.

Below are just a few examples of how different the attribute lists are from Doc to Doc: 

Example 1 (Header from Quick Ref):
:awestruct-layout: base
:awestruct-javascripts: [view-result]
:description: This guide is a quick reference for the common formatting markup and document elements in the AsciiDoc syntax.
:keywords: AsciiDoc, Asciidoctor, syntax, reference, cheatsheet
:imagesdir: ../images
:toc:
:toc-placement!:
ifndef::awestruct[]
:idprefix:
:idseparator: -
endif::awestruct[]
:result: role="result"
:linkattrs:

Example 2 (Header from MacOSX Guide)
:awestruct-layout: base
:toc:
:toolchain: link:

Example 3: (Header from How do I render....)
:awestruct-layout: base
:toc:

Examples of the variety of link naming schemes:

Example 1: (Header links from How do I render...)
:toolchain: link:/docs/install-toolchain
:buildref: http://github.com/asciidoctor/asciidoctor-stylesheet-factory/blob/master/README.adoc
:factoryrepo: http://github.com/asciidoctor/asciidoctor-stylesheet-factory
:factoryshowcase: http://themes.asciidoctor.org/
:customthemeref: http://github.com/asciidoctor/asciidoctor-stylesheet-factory/blob/master/README.adoc#create-a-new-theme
:yelp: http://live.gnome.org/Yelp
:publican: http://fedorahosted.org/publican
:a2x: http://asciidoc.org/a2x.1.html
:backendrepo: http://github.com/asciidoctor/asciidoctor-backends
:backendissue: http://github.com/asciidoctor/asciidoctor-backends/issues
:mailinglist: http://discuss.asciidoctor.org/
:userguide: http://asciidoc.org/userguide.html

Example 2: (Header links from Writers Guide)
:asciidoc-ref: http://asciidoc.org
:asciidoc-dl-ref: http://sourceforge.net/projects/asciidoc/files/latest/download
:asciidoc-editor-ref: http://asciidoc.org/#_editor_support
:asciidoc-faq-ref: http://asciidoc.org/faq.html
:asciidoc-guide-ref: http://asciidoc.org/userguide.html
:asciidoc-install-ref: http://asciidoc.org/INSTALL.html
:asciidoc-list-ref: http://groups.google.com/group/asciidoc
:asciidoctor-ref: link:/
:asciidoctor-gem-ref: https://rubygems.org/gems/asciidoctor
:deckjs-ref: http://imakewebthings.com/deck.js
:editing-ref: link:/docs/editing-asciidoc-with-live-preview/
:gist-ref: http://gist.github.com
:publican-ref: https://fedorahosted.org/publican
:quick-ref: link:/docs/asciidoc-quick-reference/
:what-asciidoc-ref: link:/docs/what-is-asciidoc-why-use-it

**Comment by jaredmorgs** [comment]
Any next actions that we can record here to get momentum happening again @graphitefriction ?

**Comment by mojavelinux** [comment]
I think this issue is now largely solved by Antora. Creating a new page is as simple as defining a page title. Pages inherit document attributes from the component descriptor and the playbook. And there are no need for linking attributes as those are now handled by Antora's resource ID system of referencing.
