### ISSUE TITLE
Highlight the difference between block and inline images in quick reference

### ISSUE THREAD

**Issue by EikeRethmeier** [asciidoctor/asciidoctor.org#617]
Please add a hint in
[http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#images](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#images)
that inline images are written with one colon only. That's something which me and co-workers overlooked and so did not recognize this difference.
I saw that you already highlighted this difference in the normal user manual at [http://asciidoctor.org/docs/user-manual/#images](http://asciidoctor.org/docs/user-manual/#images) via 

> (notice there is only one colon).

 Would be cool if you add this in the quick reference, too.

**Comment by mojavelinux** [comment]
I absolutely agree. I've proposed a patch.
