### ISSUE TITLE
"Variable" should be attribute in attribute section

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#630]
http://asciidoctor.org/docs/user-manual/#assigning-document-variables-inline
is currently 

"13.6. Assigning Document Variables Inline
Document variables can be assigned using the following syntax:
{set:<attrname>[!][:<value>]}
This is important for being able to assign document attributes in places where attribute entry lines are not normally processed, such as in a table cell."

I assume this is an error rather than an attempt to define another attribute class.

**Comment by mojavelinux** [comment]
Yep.
