### ISSUE TITLE
Fix for issue #602 reversed has not worked

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#633]
file:///home/rocky/git/asciidoctor.org/docs/user-manual.html#ordered-lists
It looks fine when I generate the docs at home, but is not reversed on the website

**Comment by mojavelinux** [comment]
That's because the website is not running Asciidoctor 1.5.5. It will need to be upgraded. Let's close this issue an open one specifically for that change. See #634.
