### ISSUE TITLE
Reader#restoreLines(lines) causes Drop-Line on include::{var}file.ad[]

### ISSUE THREAD

**Issue by mmews-n4** [asciidoctor/asciidoctor.org#636]
The problem is triggered only when using a `Preprocessor`, and calling `restoreLines(List<String>)` in the process method: Any include directive that contains a variable (e.g.: `include::{var}file.ad[]` is omitted. 

The command line says:
`WARNING: dropping line containing reference to missing attribute: var`

Example adoc file (assuming an `otherFile.adoc` exists):
```
= My Title
:var: dir/
include::{var}otherFile.adoc[]
End of file.
```

The triggering source line for this behaviour is (reader.rb line 813):
`if (target = @document.sub_attributes raw_target, :attribute_missing => 'drop-line').empty?`

This behaviour is odd since the variable can be resolved when no preprocessor calls the method `restoreLines`.

**Comment by mojavelinux** [comment]
Did you mean to file this issue in core? This repository is for the documentation.

https://github.com/asciidoctor/asciidoctor/issues

**Comment by mmews-n4** [comment]
Thanks for your comment! I opened an issue in core (see https://github.com/asciidoctor/asciidoctor/issues/1962) and close this one here.

**Comment by mojavelinux** [comment]
Thanks! I'll investigate!
