### ISSUE TITLE
Provide clarification for constrained and unconstrained quotes

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#64]
Add the following clarification to the writer's guide and quick reference (if it fits).

> Constrained means "around a word". Unconstrained means "anywhere".

**Comment by jaredmorgs** [comment]
So has the inline parser improved to better handle constrained quotes?

I don't see any mention of the concept of constrained or unconstrained quotes in http://asciidoctor.org/docs/user-manual/#quotes so I feel this should make it's way into a PR for action by someone.

**Comment by mojavelinux** [comment]
We have to move forward documenting how it works today. That should help inform the design for the future since the current behavior will be well specified.

What we are looking for in this issue is a clearer meaning for the terms "constrained" and "unconstrained". It's a bit more complex than it seems on the surface (due to edge cases) and one of the reasons people come looking for information in the manual.

**Comment by jaredmorgs** [comment]
Totally stealing this one from you Dan.

**Comment by mojavelinux** [comment]
By all means!

One way to help users tell when they need constrained vs unconstrained is to pose a litmus test sort of question. We'd say "Is there a letter, number, underscore directly outside the formatting marks (on either side), a semi-colon directly before the starting formatting mark or a space directly inside of the formatting mark?" If so, you need to switch to unconstrained (double formatting marks).

Then we can give some positive and negative examples for each of these situations.

For example:

```
Sara__h__
```

(^ in this case, unconstrained is needed because of the "a" on the left).

```
**B**old
```

(^ in this case, unconstrained is needed because of the "o" on the right)

```
&endash;**2016**
```

(^ in this case, unconstrained is needed because of the "\&endash;" on the left)

```
*2016*&endash;
```

(^ in this case, unconstrained is not needed because `&` is not a letter, number, underscore)

```
*9*-to-*5*
```

(^ in this case, unconstrained is not needed because hyphen is not a letter, number underscore or semi-colon).

```
** bold **
```

(^ in this case, unconstrained is needed because there are spaces directly inside the formatting marks)

These examples might work best in a table.

**Comment by jaredmorgs** [comment]
I'll add these to the PR I've logged.

On Wed, 3 Feb 2016, 09:36 Dan Allen <notifications@github.com> wrote:

> By all means!
>
> One way to help users tell when they need constrained vs unconstrained is
> to pose a litmus test sort of question. We'd say "Is there a letter,
> number, underscore directly outside the formatting marks (on either side),
> a semi-colon directly before the starting formatting mark or a space
> directly inside of the formatting mark?" If so, you need to switch to
> unconstrained (double formatting marks).
>
> Then we can give some positive and negative examples for each of these
> situations.
>
> For example:
>
> Sara__h__
>
> (^ in this case, unconstrained is needed because of the "a" on the left).
>
> **B**old
>
> (^ in this case, unconstrained is needed because of the "o" on the right)
>
> &endash;**2016**
>
> (^ in this case, unconstrained is needed because of the "&endash;" on the
> left)
>
> *2016*&endash;
>
> (^ in this case, unconstrained is not needed because & is not a letter,
> number, underscore)
>
> *9*-to-*5*
>
> (^ in this case, unconstrained is not needed because hyphen is not a
> letter, number underscore or semi-colon).
>
> ** bold **
>
> (^ in this case, unconstrained is needed because there are spaces directly
> inside the formatting marks)
>
> These examples might work best in a table.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/64#issuecomment-178886230>
> .
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
OK. PR Done.

On Wed, 3 Feb 2016 at 11:44 Jared Morgan <jaredleonmorgan@gmail.com> wrote:

> I'll add these to the PR I've logged.
>
> On Wed, 3 Feb 2016, 09:36 Dan Allen <notifications@github.com> wrote:
>
>> By all means!
>>
>> One way to help users tell when they need constrained vs unconstrained is
>> to pose a litmus test sort of question. We'd say "Is there a letter,
>> number, underscore directly outside the formatting marks (on either side),
>> a semi-colon directly before the starting formatting mark or a space
>> directly inside of the formatting mark?" If so, you need to switch to
>> unconstrained (double formatting marks).
>>
>> Then we can give some positive and negative examples for each of these
>> situations.
>>
>> For example:
>>
>> Sara__h__
>>
>> (^ in this case, unconstrained is needed because of the "a" on the left).
>>
>> **B**old
>>
>> (^ in this case, unconstrained is needed because of the "o" on the right)
>>
>> &endash;**2016**
>>
>> (^ in this case, unconstrained is needed because of the "&endash;" on the
>> left)
>>
>> *2016*&endash;
>>
>> (^ in this case, unconstrained is not needed because & is not a letter,
>> number, underscore)
>>
>> *9*-to-*5*
>>
>> (^ in this case, unconstrained is not needed because hyphen is not a
>> letter, number underscore or semi-colon).
>>
>> ** bold **
>>
>> (^ in this case, unconstrained is needed because there are spaces
>> directly inside the formatting marks)
>>
>> These examples might work best in a table.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/asciidoctor/asciidoctor.org/issues/64#issuecomment-178886230>
>> .
>>
> --
>
> Sent from Mobile.
>
-- 

Sent from Mobile.

**Comment by jaredmorgs** [comment]
This is ready for review @mojavelinux
