### ISSUE TITLE
Semantic: Should we rename all occurrences of "backend" to "converter"

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.org#644]
I think converter is easier to understand than backend and this will avoid confusion.

**Comment by rockyallen** [comment]
Interesting idea, but:
1. Converter is too general-for example docbookrx describes itself as a converter. Asciidoctor could reasonably be described as a converter for asciidoc to html. Output format or just output is closer.
2. Isn't it too late anyway? --backend is in all the clis and probably many user scripts. You would have to document and maintain the synonyms forever.

**Comment by Mogztter** [comment]
> Output format or just output is closer.

:+1:

`Input > Processor (Asciidoctor) > Ouput`

> You would have to document and maintain the synonyms forever.

This is really sad... I want to cry :cry: 
Joke aside, I think we should at least, make sure that we are not using "backend" when we mean "converter".
For instance: http://asciidoctor.org/docs/user-manual/#creating-a-backend
Here I think we should be using "converter", because we want to create a "converter" (and use it as a backend).

But still the two notion are confusing... :unamused:

**Comment by mojavelinux** [comment]
I've defined the difference in an FAQ.

https://asciidoctor.org/docs/faq/#converter-vs-backend

We should update the docs accordingly.

**Comment by mojavelinux** [comment]
I believe this distinction is now clearly covered on the following page: https://docs.asciidoctor.org/asciidoctor/latest/converters

(That information may move around as we restructure that area of the docs, but the information will be preserved).

Going forward, we should mindful of the difference between a backend and a converter. The converter is the software component. The backend is the identifier for that component or a moniker for the output format. If you notice the terms being used incorrectly, please submit a patch to fix it.
