### ISSUE TITLE
White space before plus sign for line break

### ISSUE THREAD

**Issue by gfinocchiaro** [asciidoctor/asciidoctor.org#661]
In section "21.1 Line Break", it is not explicitly written that a space is required before the plus sign, otherwise line break won't work.

**Comment by mojavelinux** [comment]
You are absolutely correct. This needs to be better explained. Are you interested in proposing revised text (via a PR)?

**Comment by gfinocchiaro** [comment]
Yes, sure. Could you please show me which project I have to fork to make the PR? Thanks

**Comment by mojavelinux** [comment]
It's this project. Here's the file: https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/para-line-break.adoc

**Comment by gfinocchiaro** [comment]
Thanks! I asked that because I didn't find doc files in the project.
