### ISSUE TITLE
Table example missing view result option

### ISSUE THREAD

**Issue by janicecmt** [asciidoctor/asciidoctor.org#664]
The table example titled "Table with three columns, a header, and two rows of content" in the Syntax Guide is missing a view result link.

I took a look at the guide source to see if this was something I could quickly add then submit as a PR but I couldn't figure out how to do it (sorry!)

NOTE: I originally filed this as an issue in the asciidoctor repo - sorry - most of the other projects I've worked on or used the most that have more than one repo only allow public issues on one of them and I keep forgetting that you have more than one place for issues.

**Comment by mojavelinux** [comment]
Thanks for reporting! Since I'm familiar with the code, I could see what needed to be fixed. As it turns out, the callout list was breaking the "view result" logic. The code just needed to account for that scenario.
