### ISSUE TITLE
How to use list continuations for previous content

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor.org#668]
I would like to use a list continuation to refer to _previous_ content.

Consider the following example:

```
How many phones do you have?::
I have:
* Sony Xperia ?
* A blackberry from 1999
* A Samsung J???
+
Only the Xperia is usable.
```

I would like the phrase, `Only the Xperia is usable.` to be inline with the phrase `I have:` but the `+` list continuation character brings it in-line with the bulleted items not the phrase `I have:`. Is it possible to refer to the "earlier/higher hierarchy"?

**Comment by danyill** [comment]
Easier than I thought and documented on I think what is required is a non-literal continuation:

```
Non-literal continuation.
+
----
any block can be

included in list
----
+
```

This is, in fact well covered at http://www.methods.co.nz/asciidoc/userguide.html#X15

And I see it is also in the user manual http://asciidoctor.org/docs/user-manual/#complex-list-content

I'll close this. My bad.

**Comment by mojavelinux** [comment]
There's an even more idiomatic way of writing it. You just leave a blank link before the list continuation line. That blank line effectively "backs out" of the nested list.

```
How many phones do you have?::
I have:
* Sony Xperia ?
* A blackberry from 1999
* A Samsung J???

+
Only the Xperia is usable.
```

However, I tend to prefer using the delimited blocks because the intention is more clear (and it's a bit more reliable):

```
How many phones do you have?::
I have:
+
--
* Sony Xperia ?
* A blackberry from 1999
* A Samsung J???
---
+
Only the Xperia is usable.
```
