### ISSUE TITLE
Document table-number attribute etc

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#672]
They are document attributes that automatically created, and used to number formal tables (figures, listings).
They should probably be left alone, although you can override them to them alter the sequence (or is this a hack to be warned against?). Either way they should be listed so you don't accidentally clobber them.
Closest category is "Environment" attributes.

**Comment by mojavelinux** [comment]
I think it's fair to document these. We should make it clear though that they're created automatically and thus should be treated as "reserved" attribute names.

It's possible to refer to the number inside the content of the block...though we haven't fully committed to supporting this pattern of usage.

```
.Descriptive title
====
This is example {example-number}.
====
```

**Comment by rockyallen** [comment]
Updated as requested
