### ISSUE TITLE
Document xref label for bibliography

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#691]
Ref
https://github.com/asciidoctor/asciidoctor/issues/1562

**Comment by rockyallen** [comment]
Biblio entries have to be in an unnumbered list with role=bibliography.
Annoyingly this does not autonumber:
* [[[prog,{counter:bib}]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
  From Journeyman to Master. Addison-Wesley. 1999.
because <<prog>> renders as [{counter:bib}].

Use [[[prog,3]]] xxxx to get <<prog>> = [3]

Mention biblio project
Docbook mapping = to a bibliomixed, so you lose the quality formating of docbook.

**Comment by mojavelinux** [comment]
> Biblio entries have to be in an unnumbered list with role=bibliography.

Actually, it's a block style (also called a block name), not a role.

You have to put the bibliography style on the enclosing section. The bibliography style on the list is optional in Asciidoctor as it gets inherited from the section.

Technically, putting a bibliography style on the list and not the section is non-conforming, though it doesn't result in broken output. It's just not going to be styled correctly.

So the rule is: put the bibliography style on the section. Also put it on the list if you want, but it is not required.

**Comment by mojavelinux** [comment]
> Annoyingly this does not autonumber:

The design in Asciidoctor was to have textual labels. I think it's reasonable that we could have a switch to would automatically convert to numbered labeled. As of Asciidoctor 1.5.6, this is now feasible.

**Comment by mojavelinux** [comment]
> Docbook mapping = to a bibliomixed, so you lose the quality formating of docbook.

I'm open to suggestions, but I can't really see any other container that would support the richness that the AsciiDoc syntax affords.

**Comment by mojavelinux** [comment]
I made some updates. See how you like the result:

http://asciidoctor.org/docs/user-manual/#user-biblio

**Comment by rockyallen** [comment]
Looks good, thanks.
Re "Docbook mapping = to a bibliomixed, so you lose the quality formating of docbook."
I (wrongly) assumed that the reference would be parsed into title, author, date etc so you could output a biblioentry with sub-elements. Docbook has really good formatting for this element.
But bibliomisc is the right one if you treat the reference as a single string, and it is probably impractical to parse it anyway.

**Comment by mojavelinux** [comment]
> But bibliomisc is the right one if you treat the reference as a single string, and it is probably impractical to parse it anyway.

Yep, that's where we are now.

Eventually, I see us integrating asciidoctor-bibtex (or something like it) into core. But that would be part of the next step in the evolution of the feature.

**Comment by mojavelinux** [comment]
In other words, the way it is now was to have compliance with AsciiDoc Python. But Asciidoctor is all about evolution. Now it's time to start enhancing features such as this one.
