### ISSUE TITLE
Document new warning message

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#692]
WARNING: bib.adoc: id assigned to bibliography anchor already in use: prag

**Comment by mojavelinux** [comment]
We should also emphasize that this warning is only displayed in verbose mode. The reason for this is that we can't yet be 100% sure we aren't reporting a false positive.

**Comment by mojavelinux** [comment]
Actually, I was thinking about a different warning. I was thinking about the new warning when you try to link to an ID that doesn't exist. We'll also need to document that warning, which is only enabled when the verbose flag (`-v`) is set.
