### ISSUE TITLE
The explanation in the section `Separating Lists` on writer's guide confuses me.

### ISSUE THREAD

**Issue by crocket** [asciidoctor/asciidoctor.org#696]
I read `where the ^ is dummy text that indicates this line serves as an "end of list" marker:`

But, there is no `^` anywhere.

**Comment by mojavelinux** [comment]
Thanks for pointing this out. The description had become out of sync with the example. I just fixed it.

**Comment by mojavelinux** [comment]
If that makes sense, please close this issue as resolved.
