### ISSUE TITLE
The explanation of em dash on http://asciidoctor.org/docs/asciidoc-writers-guide/#replacements is confusing.

### ISSUE THREAD

**Issue by crocket** [asciidoctor/asciidoctor.org#697]
On http://asciidoctor.org/docs/asciidoc-writers-guide/#replacements, I read

```
When white space characters are detected on both sides of the em dash, they are replaced by thin spaces (&#8201;).
```

asciidoctor 1.5.6.1 doesn't seem to exhibit this behavior. When white space characters are detected on both sides of em dash, they are not replaced by thin spaces.

**Comment by mojavelinux** [comment]
If you create the following document:

```
text -- text
```

You should get:

```
text&#8201;&#8212;&#8201;text
```

Is that not what you're observing?

**Comment by mojavelinux** [comment]
I updated the explanation to be more clear.

**Comment by crocket** [comment]
```
text -- text
```

was converted to

![2017-08-05_sat_22 03 44](https://user-images.githubusercontent.com/748856/28999073-73786576-7a75-11e7-8a33-4db6746e9b6f.png)
