### ISSUE TITLE
http://asciidoctor.org/docs/asciidoc-writers-guide/#attaching-to-an-ancestor-list has an issue with asciidoctor 1.5.6.1

### ISSUE THREAD

**Issue by crocket** [asciidoctor/asciidoctor.org#698]
According to http://asciidoctor.org/docs/asciidoc-writers-guide/#attaching-to-an-ancestor-list

```
* grandparent list item
** parent list item
*** child list item

+
paragraph attached to grandparent list item
```

should make `paragraph attached to grandparent list item` a sibling of `child list item`.
But, with asciidoctor 1.5.6.1, it is a sibling of `parent list item`.

With asciidoctor 1.5.6.1, the following exerpt doesn't seem to make sense.

> Each blank line that precedes the list continuation signals a move up one level of nesting.

The following document illustrates the issue more conspicuously.

```
* grandparent list item
** parent list item
*** child list item
**** grandchild

+
paragraph attached to grandparent list item
```

**Comment by mojavelinux** [comment]
That assumption is not correct. The blank line followed by the list continuation graduates the paragraph one level. So in your first example, the paragraph would be attached to the parent list item.

In order to attach to the grandparent list item, you need another blank line.

```
* grandparent list item
** parent list item
*** child list item


+
paragraph attached to grandparent list item
```

**Comment by crocket** [comment]
The problem is that one blank line graduates the attached block two levels in the example below.

![2017-08-05_sat_01 38 01](https://user-images.githubusercontent.com/748856/28991889-43ea4960-79ca-11e7-9654-5c0877da8129.png)

```
* grandparent list item
** parent list item
*** child list item

+
paragraph attached to grandparent list item
```

**Comment by mojavelinux** [comment]
Oops, my mistake. I see what you are saying.

I did a quick test and it looks like this has always been the behavior of Asciidoctor. So it has never worked the way it is supposed to, I guess.

The problem is, listing parsing is just done incorrectly. Until we fix the list parsing, it's almost impossible to fix this issue. So the way forward is to change how lists are parse so we can do the right thing. It will also make it much more robust.

**Comment by mojavelinux** [comment]
This bug needs to be reported in core (which is https://github.com/asciidoctor/asciidoctor/issues). I'll associate it with the effort to redo the list parsing.

**Comment by mojavelinux** [comment]
The workaround is to use an open block:

```
* grandparent list item
** parent list item
+
--
* child list item
--
+
paragraph attached to parent list item
```

**Comment by mojavelinux** [comment]
Please direct further comments to the linked issue.
