### ISSUE TITLE
The last example on http://asciidoctor.org/docs/asciidoc-writers-guide/#target-window-and-role-attributes-for-links doesn't compile properly.

### ISSUE THREAD

**Issue by crocket** [asciidoctor/asciidoctor.org#699]
The example is 

```
Chat with other Asciidoctor users in the irc://irc.freenode.org/#asciidoctor[Asciidoctor IRC channel] or on the http://discuss.asciidoctor.org/[*mailing list*^, role="green"].
```

It is rendered by asciidoctor 1.5.6.1 as

Chat with other Asciidoctor users in the Asciidoctor IRC channel or on the **mailing list**^, role="green".

```
Chat with other Asciidoctor users in the irc://irc.freenode.org/#asciidoctor[Asciidoctor IRC channel] or on the http://discuss.asciidoctor.org[mailing list, window="_blank"].
```

is rendered as

Chat with other Asciidoctor users in the Asciidoctor IRC channel or on the mailing list, window="_blank".

**Comment by mojavelinux** [comment]
That's because you need to enable the `linkattrs` document attribute, which is not enabled by default. So the full example would be:

```
:linkattrs:

Chat with other Asciidoctor users in the irc://irc.freenode.org/#asciidoctor[Asciidoctor IRC channel] or on the http://discuss.asciidoctor.org/[*mailing list*^, role="green"].
```

I can add a note about this.

**Comment by crocket** [comment]
Ouch, I forgot to add `:linkattrs:`.

**Comment by mojavelinux** [comment]
I can see how it wasn't clear. I went ahead and made it more explicit. I'm sure it can still be improved, but that change should help.
