### ISSUE TITLE
What is "master" on http://asciidoctor.org/docs/user-manual/#inter-document-cross-references?

### ISSUE THREAD

**Issue by crocket** [asciidoctor/asciidoctor.org#702]
On http://asciidoctor.org/docs/user-manual/#inter-document-cross-references, I read

> If document-b.adoc is included in the same master as document-a.doc, then the document will be dropped in the link target and look like the output of a normal cross reference

What is master?

**Comment by mojavelinux** [comment]
This is just worded poorly. I have an idea for how to rephrase. See https://github.com/asciidoctor/asciidoctor.org/commit/6a7ab9608528771d1fc5b498ff75c528ba8fe15c.

**Comment by crocket** [comment]
Did you mean `the same master document`?

**Comment by mojavelinux** [comment]
Yes, I meant the same master document. However, in this context "document" is understood to mean the document we are building. So I think we can just drop the term "master".

**Comment by crocket** [comment]
I think the meaning is clear.
