### ISSUE TITLE
The example on http://asciidoctor.org/docs/user-manual/#navigating-between-source-files is outdated.

### ISSUE THREAD

**Issue by crocket** [asciidoctor/asciidoctor.org#703]
Github doesn't require

```
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
```

in `.adoc` files anymore.

On github, setting `:outfilesuffix:` is not required to make `<<README#,README>>` refer to `README.adoc`.

**Comment by mojavelinux** [comment]
Right you are!

**Comment by mojavelinux** [comment]
I made a note about this. It's still required in GitHub-like environments (environments that rely on github/markup), so I just pointed that out.
