### ISSUE TITLE
Broken link for Ruby API documentation

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor.org#709]
In http://asciidoctor.org/docs/#references-and-developer-resources when I click on "Asciidoctor Ruby API Documentation" I get a 404, it refers to http://asciidoctor.org/rdoc/Asciidoctor.html

**Comment by danyill** [comment]
While I'm there, the AsciidoctorJ documentation refers to 1.5.4.

Perhaps it would be better to link to http://www.javadoc.io/doc/org.asciidoctor/asciidoctorj/?

**Comment by mojavelinux** [comment]
We were publishing the Ruby API doc to the site at one time, but we have since stopped. The link should point to http://www.rubydoc.info/gems/asciidoctor.

**Comment by danyill** [comment]
Excellent, thankyou sir!

**Comment by mojavelinux** [comment]
The AsciidoctorJ page needs the remote include treatment like we do with the Asciidoctor Diagram page. This way, it is not duplicated. I think the reason we hadn't done it yet is that there were some improvements to the page on the asciidoctor.org site that didn't get pushed upstream. I can do a quick review to see what is worth salvaging, then switch over to the remote include.

**Comment by mojavelinux** [comment]
Oh, I see which AsciidoctorJ link you are talking about. Yes, that should point to the link you mentioned.

Would you like to update those two links?

**Comment by mojavelinux** [comment]
(We still need to update the AsciidoctorJ page, but that's a separate issue than what you are talking about).
