### ISSUE TITLE
Broken link at the end of sec. 40.9

### ISSUE THREAD

**Issue by andrewcarver** [asciidoctor/asciidoctor.org#715]
The link to "macro and block passthroughs" at the end of User Manual sec. 40.9 is broken:

Change the link as follows:
http://asciidoctor.org/docs/user-manual/#passthru 
  -->
http://asciidoctor.org/docs/user-manual/#passthroughs

**Comment by mojavelinux** [comment]
Thanks for reporting. Would you be willing to submit a pull request?

**Comment by andrewcarver** [comment]
I'm definitely willing -- but a newbie to GitHub (all I've done so far is the first, newbie-tutorial), so bear with me for the next (few?) almost certainly stupid question(s):
- When the request is pursuant to an Issue (like this), do I have to create a "branch" first, and do a "commit", before I can do a "pull request"?

**Comment by andrewcarver** [comment]
Hahaha -- only a newbie can ask such an (innocently) ignorant question, right? But the good news is, I'm learning!
So, the next thing I'll do is go to https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc and try opening a branch (while praying, of course, that my computer does not at that very moment disintegrate!).

**Comment by andrewcarver** [comment]
Well, I found the page (although the section-numbering surprised me by being one section off: 39 instead of 40); 
but I was unable to create the branch in the way the tutorial demonstrated. Do I instead click on the little pencil that says "Fork this project and edit the file"? (I've never "forked"... but I'm open to suggestions :)

**Comment by andrewcarver** [comment]
P.S. I'm on a PC, so any forking-advice you can give re that platform (Git clients or whatever) would be helpful (& appreciated :) .

**Comment by andrewcarver** [comment]
Am now finding the stuff I should already have been reading ;)
Will do the fork and pull request as soon as I've digested it! Thanks.

**Comment by mojavelinux** [comment]
You are doing an excellent job. I see the PR. Nice work!

**Comment by mojavelinux** [comment]
I'll admit that finding the document that goes with the section right now can be tricky. It started out simple, but as things tend to do, it became overly complex. We're in the process of designing a new system where each section will be associated more clearly to its source file.
