### ISSUE TITLE
Spin off a more basic AsciiDoc syntax quick reference

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#72]
Currently, the AsciiDoc syntax quick reference is trying to serve both newcomers and veteran users. The more complete it becomes, the more intimidating it makes the AsciiDoc syntax seem for newcomers.

Spin off a more basic AsciiDoc syntax quick reference that has the scope of a Markdown reference (specifically a Markdown variant, like Kramdown, that supports the most common extras).

**Comment by jaredmorgs** [comment]
Do you feel it still is too complex, @mojavelinux ?

If so, we should collaborate on a fix.

**Comment by mojavelinux** [comment]
Yes, I still think we need something simpler. We should focus on a scope. Something like "the first 5 to 10 minutes with AsciiDoc" or "AsciiDoc essentials" or "most common AsciiDoc you need to know".

**Comment by jaredmorgs** [comment]
Adding the label above because we are probably going to create bespoke, terse content for this quick ref, and then link off to the more verbose content in the user-guide.adoc

**Comment by mojavelinux** [comment]
I like it.
