### ISSUE TITLE
Clarify meaning of, by renaming, the "Header" row in Secs. 40.2-5 tables

### ISSUE THREAD

**Issue by andrewcarver** [asciidoctor/asciidoctor.org#735]
In each of the tables entitled "Elements subject to <this or that sort of> text substitution", in  Sections 40.2-40.5, there is a row named "Header".

That row-name evokes the identical row-names in the two tables entitled "Substitution groups", in Secs. 20.4 and 40. However, whether or not that substitution-group is the intent in 40.2-40.5, the result is unfortunately, more or less, ambiguity and confusion:

* _If the intent is to evoke thus the "Header substitution group",_ then the reader wants to know why there are also, in each of these tables, rows indicating whether the substitution in view occurs in "Attribute Entry Values", which are themselves categorized as part of the "Header substitution group"?
* If instead, the intended sense was *not* the "Header substitution group", then the actual intended sense (a surmise about which we offer below) gets unfortunately obscured, by this row-label "Header" (which, as we've mentioned, evokes the "Header" substitution-group rows in those other two tables).

An additional reason to think these rows do *not* refer to the "Header substitution group", is that _none of the many other rows_ in these 40.2-40.5 tables refers to any established substitution group. Thus the table shows no intent to say something about how substitution groups behave.

On the assumption, then, that the "Header" substitution group was *not* the intended referent here, probably what *was* intended was the other **sub**-part of that substitution group, which comprises just the "implicit Author" and "implicit Revision" lines of the Header. 

Such an intent would be made clearer, IMHO, by changing the rows' name, from "Header" to ... uh ... something like:

* Implicit Metadata, or
* Implicit Metadata Lines, or
* Implicit Author / Revision, or
* <something better that we've not yet thought of>

Feedback? Suggestions? Corrections?

P.S. In the interest of "full disclosure": In Secs. 40.5 and 40.6, we recently emended the values in column 2 of these rows, which previously had the same (incorrect), affirmative tick-marks as were also in the "Attribute Value" (now "Attribute Entry Value") rows. (See PR #731.) Those edits did not beg the question at issue here, though, because those tick-marks were incorrect whether you take the row as referring to the Header substitution group as a whole, or as referring to just a sub-part of that group.

**Comment by mojavelinux** [comment]
I'd like to move this forward. In light of recent changes to the docs, do you feel like this is still unaddressed?

In general, there's a concept of the document header, and for various reasons, it gets its own substitution group. As you have identified, the content subject to that substitution group includes:

* The implicit author and revision lines
* The value of any attribute entry (even if not in the header)

However, the doctitle itself gets title substitutions (because, it just does).

I agree it's still a bit vague to group these as "Header". That's terminology is just historical.

But intent was definitely "header substitution group".

**Comment by mojavelinux** [comment]
Perhaps this was resolved by https://github.com/asciidoctor/asciidoctor.org/pull/732?

**Comment by andrewcarver** [comment]
Thanks for asking, Dan, and for the elucidation. Yes, I think the docs are clear on this now.

My memory is somewhat hazy, but I suspect my good cheer with [the Table in 37.5](https://asciidoctor.org/docs/user-manual/#subs-mac) might have been thrown off by my not grasping that inline pass macros work **not** in the Header as such, but only in attribute entries (and even then, only when they enclose the whole entry). 

In any case, now that I'm clear on that, there seems surely nothing better to call this row, than simply "Header". Thanks again, and Good Work clearing up this whole subject!

**Comment by mojavelinux** [comment]
Excellent! Thanks for following up. And thank you for helping get this subject cleaner up. The more we put our heads together, the clearer is all gets. :beers:
