### ISSUE TITLE
On website, some of Sec. 12's backticks being handled as in AsciiDoc, not AsciiDoctor

### ISSUE THREAD

**Issue by andrewcarver** [asciidoctor/asciidoctor.org#738]
This is another case like #737 except that I'm not sure this whole section is suffering AsciiDoc-style handling of its backticks. But here are two places it is, for sure:

- the table "Constrained or Unconstrained?", in Sec. 12.3: column 1's values have 'plus' passthrough macros surrounded by backticks that are preventing substitution on the macros (so the plus signs pass thru too)
- the sentence in Sec. 12.4 which reads, in the raw, ``That only gives you "`endpoints`", since the backticks are contributing to the enclosing smart quotes.``

**Comment by mojavelinux** [comment]
This was caused by a misconfiguration in the site generator.
