### ISSUE TITLE
More places where backticks are preventing 'plus' pass macro from being substituted

### ISSUE THREAD

**Issue by andrewcarver** [asciidoctor/asciidoctor.org#739]
This is like the cases in #738 where values have 'plus' passthrough macros surrounded by backticks that are somehow preventing substitution on the macros (so the plus signs pass thru too).

These are all cases of `` `+*+` `` or `` `+^+` `` ...

(The section nrs. are according to how the content appears on the website.)

- Sec. 26.2: ``The multiplier operator (`+*+`) is used when you want`` ...
- Sec. 26.2: ``The `+*+` operator ensures that the default layout and style`` ...
- Sec. 26.2: ``Content can be horizontally aligned left (`<`), center (`+^+`), or right (`>`).``
- Sec. 26.2: ``To horizontally center the content in all of the columns, add the `+^+` operator`` ...
- Sec. 26.2: ``Assign the default styles to the preceding columns, and `+^+` to the last colum`` ...
- Sec. 26.2: ``Content can be vertically aligned to the top (`<`), middle (`+^+`), or bottom (`>`)`` ...
- Sec. 26.2: ... ``in all of the columns, add a `.` and then the `+^+` operator after the multiplier.``
- Sec. 26.3: ... ``prefix the `|` with the multiplication factor and the `+*+` operator.``
- Sec. 27.1:  ... ``only 3 repeating characters (`-` or `+*+`) are recognized.``
- Sec. 29: ``Just end the link text with a caret (`+^+`):``
- Sec. 73: ``To save some typing, you can use the glob operator (`+*+`) to match`` ...
- Sec. 73: ... ``pass all AsciiDoc files inside direct subfolders using the glob operator (`+*+`)`` ...

**Comment by mojavelinux** [comment]
As it turns out, this was caused by a misconfiguration in the site generator.
