### ISSUE TITLE
Displaying new lines in stem environment doesn't work

### ISSUE THREAD

**Issue by hgiesel** [asciidoctor/asciidoctor.org#744]
What I wrote:

```
= My file
:stem:

[stem]
++++
a^{2} + b^{2} = c^{2} \\
(a + b)^\frac{1}{2} = c
++++
```

My expection: both equations are displayed on separate lines. 
What I got: Both are displayed on the same line.

**Comment by hgiesel** [comment]
Sorry this went into the wrong repository...

**Comment by mojavelinux** [comment]
Thanks.

See https://github.com/asciidoctor/asciidoctor/issues/2484.
