### ISSUE TITLE
Clarify which substitutions take place in attribute list

### ISSUE THREAD

**Issue by andrewcarver** [asciidoctor/asciidoctor.org#745]
There needs to be a better attempt at explaining, in Secs. 10.5.1 and 10.5.2, exactly what substitutions take place within Attribute Lists' values. If you're looking for an example of what I mean, please see the crystal-clear explanation of this topic in the AsciiDoc User Guide, [Sec. 14.1](http://asciidoc.org/asciidoc.css-embedded.html#_attribute_value_substitution).

It goes without saying, that a user of AsciiDoctor should not have to go to the AsciiDoc User Guide to get an explanation of how AsciiDoctor works--not least because it's not about AsciiDoctor. So, I won't stoop to mentioning it. :D

**Comment by mojavelinux** [comment]
The main issue at hand is that there is no section dedicated to covering block attributes. Block attributes are treated sort of like an extension to document attributes, but they're profoundly different. How they are defined is different and how they get used is different. The only real relationship between them is that certain block attributes inherit a default value from a document attribute, but that's not very common and may be deprecated in all be special cases.

**Comment by andrewcarver** [comment]
Ah-- I believe you've smacked the nail on the head. (Sec. 10.5 is, I take it, the section you feel is "sort of floating there"... )

I can suggest here a wee initial step: in AsciiDoc an "AttributeList" is a block element; yet, in our list of such [https://asciidoctor.org/docs/user-manual/#elements](url), we omitted it. It should be there, no?

**Comment by andrewcarver** [comment]
In my all-too-deep ignorance on this issue, which I'm trying to mitigate, please allow me float yet another take on it--which I hope you'll shoot down just as quickly, if it's likewise faulty:

Aren't you implying, that among the six types of "attributes" listed at the start of [section 10](https://asciidoctor.org/docs/user-manual/#attributes), those called "element attributes" (for which, I take it, you prefer the name "block attributes") are so fundamentally different, as to be really a different category from the others?

**Comment by andrewcarver** [comment]
Why else would we both feel that Sec. 10.5 is out of its natural element there?

**Comment by andrewcarver** [comment]
Thus, if I'm understanding, "document attribute" and "block attribute" are the two basic kinds of attribute. And if so, it seems logical to me that we should have a top-level section for each of these.

As the [User Manual's glossary](https://asciidoctor.org/docs/user-manual/#glossary) defines them:

> **block attribute**
> an attribute associated with a delimited block or paragraph; these attributes can affect processing of the block, and are available to block processors, but cannot be referenced using an attribute reference.

> **document attribute**
> an attribute associated with the document (node); in other words, an attribute in the global document attributes dictionary; the value of these attributes can be referenced using an attribute reference; if defined in the header, the document attribute is known as a header attribute.

Am I in the general vicinity of the truth, here, or way off?

**Comment by mojavelinux** [comment]
> Thus, if I'm understanding, "document attribute" and "block attribute" are the two basic kinds of attribute. And if so, it seems logical to me that we should have a top-level section for each of these.

Spot on. That's exactly what I think needs to happen here. The manual was attempting to combine things that can't be combined.

Keep in mind that attributes can also appear on inline elements (such as an inline image). So we could group "block attributes" and "inline attributes" under the category "node attributes", where node is content node in the document tree. We have been saying "element attribute", but the proper term for a content chunk in AsciiDoc is a "node" (or content node).

A document attribute is like a shared variable, accessible and referenceable from (just about) anywhere. A content node attribute (block or inline) is really just configuration metadata for that particular node/chunk of content.

**Comment by andrewcarver** [comment]
Great. Yes, by all means, "node" improves upon "block".

But, hang on just a sec: does "node" comprehend "macro"? For I'm sure we need to support "macro attribute" in the scheme, somehow.... and it sounds like it's the same general sort of critter:

> **macro attribute**
> an attribute associated with a block or inline macro; these attributes can affect processing of the macro, and are available to macro processors, but cannot be referenced using an attribute reference

???

**Comment by andrewcarver** [comment]
Or, perhaps overall, it's really "configuration attribute" vs. "shared attribute"... or something!

**Comment by andrewcarver** [comment]
But in case I've completely obscured my question, it's this:
Are (both block and inline) macros instances of "content node"?

**Comment by mojavelinux** [comment]
I'm confident this information is now covered on the following page in the new docs: https://docs.asciidoctor.org/asciidoc/latest/attributes/element-attributes/ If you feel that there is something still missing, please click "Edit this Page" and suggest a revision.
