### ISSUE TITLE
Serve traffic for asciidoctor.org over https

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#746]
Serve all traffic for asciidoctor.org over https (tls). Not only is this a [recommended security practice](https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https) and good for our visitors, it will also help preserve the credibility / integrity of this site in search results.

This site is currently hosted on GitHub Pages using a custom domain. Unfortunately, GitHub Pages does not support https for custom domains (with no obvious plans to support it). So we can't use something like Let's Encrypt. We'll have to pursue other strategies.

One very popular strategy is to proxy traffic through CloudFlare, which will encrypt the traffic between the visitor and CloudFlare. Only the traffic from CloudFlare to GitHub Pages is unencrypted. This article describes how to set it up:

https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

If anyone has other ideas, we welcome your input and expertise.

**Comment by mojavelinux** [comment]
Another option is to leave GitHub Pages and host the files on Netlify instead. See https://www.netlify.com/docs/continuous-deployment/

**Comment by andrewcarver** [comment]
Hi Dan,

As someone with some SSL experience but no statc-site-generation experience, I guess I'm about a quarter-to-a-third expert when it comes to your question. But I waited and no **real** expert has spoken up... So maybe even my fairly "gut feeling" sort of response might not be totally out of place ;)

If the Netlify sort of setup and the CloudFlare sort of setup are your only architectural choices, I'd say you definitely want to work towards the Netlify sort of setup as your long-term solution. The Cloudflare approach is too much of a chewing-gum-and-baling-wire fix -- and doesn't even solve the security problem, really, except to give the surface APPEARANCE of a secure site.

My hope in this is that you'd be able to do all you currently do or need to do, with just the free Netlify service. (It did look pretty capable, on my brief and uneducated perusal...) Assuming that, and that it would not be too much immediate work to take on the Netlify sort of setup, I'd recommend you go directly to that. But if you need to do more research, to find a Netlify substitute, or need more time to do the setup, the Cloudflare thing might be a good provisional fix.

If you should find you have any SSL-specific questions, I'd certainly try to help. Good luck!

Cheers,
Andy

**Comment by Mogztter** [comment]
Netlify seems a good idea. 
@mojavelinux how can I help to make this happen ?

**Comment by mojavelinux** [comment]
> If the Netlify sort of setup and the CloudFlare sort of setup are your only architectural choices, I'd say you definitely want to work towards the Netlify sort of setup as your long-term solution.

Thanks for the recommendation! Let's do it!

> @mojavelinux how can I help to make this happen ?

I'll get the ball rolling and add you as an admin. I'll then get the domain settings and cert set up.

**Comment by Mogztter** [comment]
@mojavelinux Thanks! I've received the invitation on Netlify.

Now we have to update the DNS for `asciidoctor.org` and `www.asciidoctor.org`. Once the DNS is setup up, SSL/TLS certificates will be enabled automatically.

**Comment by mojavelinux** [comment]
Yep, working on those now.

**Comment by mojavelinux** [comment]
I've poked at all the screens now, so I'm ready to go through the transfer process. But I want to wait until I have a whole afternoon in front of me to deal with any issues that arise.

**Comment by Mogztter** [comment]
👌
https is coming!

**Comment by mojavelinux** [comment]
I almost have this setup with Netlify managing the TLS certificate managed by Let's Encrypt.

There are two open questions.

First, do we still use Travis CI? I think we should continue to use Travis CI to run the lint step. That will help in reviewing PRs. I'm not entirely sure how the interaction works between Netlify and PRs yet, so we'll have to feel that out a bit.

Second, what do we do with the gh-pages branch? We could either delete it, or we could continue to update it for reference even though it won't be used. I'm on the fence about what to do here.

**Comment by mojavelinux** [comment]
We should probably add something about Netlify to the footer, perhaps under the credit to Awestruct and Asciidoctor.

**Comment by mojavelinux** [comment]
Here are the public deploy logs from Netlify.

https://app.netlify.com/sites/asciidoctor/deploys

**Comment by mojavelinux** [comment]
There's an option in Netlify to force https. I'm not sure I'm comfortable with enabling that just yet. (We could just do a JavaScript bounce from http to https until we're sure everything is stable).

More info about forcing https on Netlify: https://www.netlify.com/docs/ssl

**Comment by mojavelinux** [comment]
Don't freak out, but I have a surprise for you.

https://asciidoctor.org/

:guitar:

**Comment by mojavelinux** [comment]
One feature we lost by switching to Netlify is the automatic assignment of publication date for a blog post. I'll open a separate issue to track that.

**Comment by andrewcarver** [comment]
Great work!! I agree, don't rush going to https-forcing, make sure everything's stable first. But then, yes, that's where you'll want to finish up.

**Comment by andrewcarver** [comment]
Hi Dan, I notice you've now closed this issue, so I thought I should mention a remnant issue: The User Manual is, at the moment, getting "mixed content" warnings from Chrome and Firefox. Both of them are giving me the same warning, however:

Mixed Content: The page at 'https://asciidoctor.org/docs/user-manual/' was loaded over HTTPS, but requested an insecure image 'http://upload.wikimedia.org/wikipedia/commons/3/35/Tux.svg'. This content should also be served over HTTPS.

Fortunately, that SVG is accessible by HTTPS (seems to be forced to it, in fact); so all we need to do, I think, to please these finicky browsers is to locate that embedded link and change the "http://" to "https://".

**Comment by andrewcarver** [comment]
P.S. Remember that this URL is linked twice--in Sec. 32.1.1, anyway--which would explain why Chrome gives the warning twice.

**Comment by mojavelinux** [comment]
Thanks for reporting @andrewcarver. I took care of it.
