### ISSUE TITLE
Replace stylesheet factory doc with RawGit to main README

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor.org#760]
I saw that `docs/produce-custom-themes-using-asciidoctor-stylesheet-factory.adoc` is a bit outdated and I suspect is an old copy of the original README.
Does it make sense to replace it with a RawGit import same as the maven/gradle plugins?

On a side note: the new readme does not include link to the styles showcase. Imnho, it should be added.

**Comment by mojavelinux** [comment]
Yes, I agree. This needs to be synced up. The version on the website has diverged a bit, so we just need ot make sure we're not losing any information.

**Comment by mojavelinux** [comment]
We're using the rawgit links as an interim step in the migration to Antora. The first step is to get the content out of asciidoctor.org so that we can switch to Antora's multi-repository content model.

**Comment by abelsromero** [comment]
> migration to Antora

You are getting some ppl pretty hyped up about that.

**Comment by mojavelinux** [comment]
The stylesheet factory is now deprecated and so are the docs for it. The docs have been replaced with docs on how to apply a custom stylesheet. https://docs.asciidoctor.org/asciidoctor/latest/html-backend/custom-stylesheet/
