### ISSUE TITLE
slideshow example is broken and recommends deckjs

### ISSUE THREAD

**Issue by 0xaf1f** [asciidoctor/asciidoctor.org#765]
at <http://asciidoctor.org/docs/user-manual/#backend-and-deck-js-installation>, it reads

 > Download or `git clone` the [Asciidoctor backends](https://github.com/asciidoctor/asciidoctor-backends) repository.
>
>    `$ git clone git://github.com/asciidoctor/asciidoctor-backends.git`

but then building the example presentation later gives this error:

```
/usr/lib/ruby/vendor_ruby/asciidoctor/converter/composite.rb:52:in `find_converter': Could not find a converter to handle transform: document (RuntimeError)
```
and it turns out that a `deck.js` presentation should be using https://github.com/asciidoctor/asciidoctor-deck.js instead of https://github.com/asciidoctor/asciidoctor-backends.

Now, I'm not sure if you just want to change the link, or if you want to also add a pointer to asciidoctor-backends as a reference for other non-deck.js slideshows.

**Comment by mojavelinux** [comment]
I actually have plans to remove the deckjs information from asciidoctor.org. deckjs is not the recommended slideshow to use with Asciidoctor and I don't want to advertise it on asciidoctor.org. We recommend using either [bespoke](https://github.com/asciidoctor/asciidoctor-bespoke) or [reveal.js](https://github.com/asciidoctor/asciidoctor-reveal.js).

**Comment by 0xaf1f** [comment]
Maybe until that gets updated, I'd suggest putting a little notice or a link to this issue in that tutorial so that new people coming to learn about Asciidoctor slideshows don't fall into the same hole I did.

**Comment by mojavelinux** [comment]
Those pages are now purged.
