### ISSUE TITLE
Warn if missing lines before a section block

### ISSUE THREAD

**Issue by vogella** [asciidoctor/asciidoctor.org#766]
Would be possible to add a warning if we have missing line breaks before a section?

Example:
````
== Testing

This is a test
== More Testing
````

Results in the following output:

````
Testing 

This is a test ==More Testing
````

**Comment by mojavelinux** [comment]
This would be the roll of a validator. It's not the job of the processor (parser+converter) to look for syntax that isn't there, or might be there. That would considerably slow down the processor and distract it from the job it's supposed to do.

Let's continue the discussion here: https://github.com/asciidoctor/asciidoctor/issues/2892 Feel free to add this as an idea (and any others you might have).
