### ISSUE TITLE
Upload demo of deck.js slides showcasing attributes

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#77]
This is almost done, I just need to polish it and pick a picture.
- Add link in deck.js guide

**Comment by jaredmorgs** [comment]
The actual action item from the discuss thread is http://discuss.asciidoctor.org/Including-Vimeo-videos-in-a-document-tp492p519.html

This is pretty old now, so I wonder if we can close it off.

**Comment by mojavelinux** [comment]
I would like all attention to be focused on either Bespoke (preferred) or Reveal. I am now actively discouraging people from using Deck because it is too outdated.

**Comment by jaredmorgs** [comment]
Should we then remove reference to deck.js in the user guide, and let
people "discover" it by searching for the repo?

And perhaps update the deck.js README with the caveat that the better
technologies are now Bespoke and then Reveal?

On Tue, 26 Jan 2016 at 10:30 Dan Allen <notifications@github.com> wrote:

> I would like all attention to be focused on either Bespoke (preferred) or
> Reveal. I am now actively discouraging people from using Deck because it is
> too outdated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/77#issuecomment-174746735>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
I'd say yes (as soon as I have an alpha release of the Bespoke converter, which should happen this week). We don't want to be encouraging bad practices and I consider making a slide deck with Deck.js to be a bad practice.

We should move forward with Bespoke and Reveal. As Bespoke matures, we may even phase out Reveal, but some good work has gone into that converter and I don't want to discount that. Besides, it's good to have two options.

**Comment by mojavelinux** [comment]
@jaredmorgs Could you open a similar issues for Bespoke and Reveal? Then we'll close this one.

Note that the Bespoke example will be a bit different because Bespoke works as a full project, complete with a build tool (gulp). The tutorial will likely explain how to use yeoman to generate a Bespoke project and create your first slide deck (similar to https://github.com/bespokejs/bespoke#creating-a-presentation). Likely the example files will live somewhere else, but the tutorial should certainly be on the asciidoctor.org site.

**Comment by jaredmorgs** [comment]
Just to ensure I file the bugs as you expect @mojavelinux, you want me to
create an "upload a demo of [bespoke.js|reveal.js] slides showcasing
attributes.

I'll do this this evening.

On Wed, 27 Jan 2016 at 07:34 Dan Allen <notifications@github.com> wrote:

> @jaredmorgs <https://github.com/jaredmorgs> Could you open a similar
> issues for Bespoke and Reveal? Then we'll close this one.
>
> Note that the Bespoke example will be a bit different because Bespoke
> works as a full project, complete with a build tool (gulp). The tutorial
> will likely explain how to use yeoman to generate a Bespoke project and
> create your first slide deck (similar to
> https://github.com/bespokejs/bespoke#creating-a-presentation). Likely the
> example files will live somewhere else, but the tutorial should certainly
> be on the asciidoctor.org site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/77#issuecomment-175241386>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Maybe not "update". Let's just say "provide" since we'll have to determine how exactly we'll do the providing.

**Comment by jaredmorgs** [comment]
ACK. Will do tonight. :D

On Wed, 27 Jan 2016 at 08:25 Dan Allen <notifications@github.com> wrote:

> Maybe not "update". Let's just say "provide" since we'll have to determine
> how exactly we'll do the providing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/77#issuecomment-175265255>
> .
>
-- 

Sent from Mobile.
