### ISSUE TITLE
Incorporate default Asciidoctor stylesheet into website

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#78]
The styles on asciidoctor.org are similar to the ones from the default Asciidoctor stylesheet, but does not share a common build. That means every change to the default Asciidoctor stylesheet also has to be made to the website.

Incorporate the default Asciidoctor stylesheet into the website so that the website can inherit the styles needed for styling HTML generated by Asciidoctor.

**Comment by jaredmorgs** [comment]
I'm sure this has been done but just hasn't been closed off @mojavelinux .

**Comment by mojavelinux** [comment]
Not yet. This is all part of https://github.com/asciidoctor/asciidoctor-stylesheet-factory/issues/18. One snowy day I need to bite the bullet and get that done because a lot of things depend on it.

**Comment by mojavelinux** [comment]
We've decided not to pursue this idea.
