### ISSUE TITLE
TOCtree

### ISSUE THREAD

**Issue by lxsli** [asciidoctor/asciidoctor.org#786]
How can I get something like this please?
http://www.sphinx-doc.org/en/stable/markup/toctree.html

Manually generating toctrees is unnecessary labour and a recipe for merge conflicts.

**Comment by lxsli** [comment]
I don't think so - I want to be able to form a TOC of multiple files,
whereas iirc TOC only works within a file.

**Comment by mojavelinux** [comment]
That's outside the scope of the Asciidoctor processor. The processor only knows about the current file it's processing. But there's where [Antora](https://antora.org) comes in. Antora operates on a catalog of files and thus has the necessary scope to make such a thing. It's also possible to achieve something like this using other site generators such as Jekyll or Middleman. But Antora is the one designed specifically for AsciiDoc.

**Comment by lxsli** [comment]
Hmm ok, thanks
