### ISSUE TITLE
Document acceptable formats for video macro

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#79]
Not all video formats can be used with the video tag. Make a note of this in the documentation / writer's guide. Something along the lines of:

> The HTML 5 video tag does not support the Quicktime/Sorenson format for video. It first needs to be converted to a "web-friendly" video format. That explains why nothing happens when you press the play button.
> 
> The following article is an excellent resource for explaining how to prepare video for an HTML 5 page.
> 
> http://www.htmlgoodies.com/html5/client/how-to-embed-video-using-html5.html#fbid=ensvc_rW_lt
> 
> You can ignore the parts about the HTML elements since Asciidoctor is already generates that. What's important are the video formats.
> 
> \* While there are ways to embed Quicktime/Sorenson using object/embed tags, these are considered deprecated and using a web-friendly video format is strongly recommended.

**Comment by jaredmorgs** [comment]
http://asciidoctor.org/docs/user-manual/#video is where this content should go. It is currently not mentioned explicitly, so this guidance needs to be added.

**Comment by mojavelinux** [comment]
Support for video formats depends on the browser and the year. The best strategy here is to link to a resource that maintains and updates such information. MDN comes to mind. https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by jaredmorgs** [comment]
Sounds like a good approach. I'll likely take this one once I finish
reading all the other responses from my ticket spam. :P

On Tue, 26 Jan 2016 at 10:33 Dan Allen <notifications@github.com> wrote:

> Support for video formats depends on the browser and the year. The best
> strategy here is to link to a resource that maintains and updates such
> information. MDN comes to mind.
> https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/79#issuecomment-174747265>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
Thanks @jaredmorgs!

**Comment by mojavelinux** [comment]
Btw, I love MDN. I think we should take notes from that site and model some of our own docs on their practices. I practically live at MDN these days.

**Comment by mojavelinux** [comment]
Merged as 7298fd1ccc18307d9236559821f7533abad35f30.

I did some minor revisions on the intro and I moved to recommendation to use a hosted service into a TIP.

**Comment by mojavelinux** [comment]
See http://asciidoctor.org/docs/user-manual/#video.
