### ISSUE TITLE
Correct typo describing 'concealed index term'

### ISSUE THREAD

**Issue by ericpierre** [asciidoctor/asciidoctor.org#790]
The [Index Terms](https://asciidoctor.org/docs/user-manual/#index-terms) section of the Asciidoctor User Manual seems to have a small typo.  

Where it says: 
> concealed index term
`indexterm:[<primary>, <secondary>, <tertiary>] or `**(**`<primary>, <secondary>, <tertiary>`**)**

It should say:
> concealed index term
`indexterm:[<primary>, <secondary>, <tertiary>] or `**(((**`<primary>, <secondary>, <tertiary>`**)))**

**Comment by mojavelinux** [comment]
Thanks for pointing that out! It turned out to be a conversion error. I corrected it.
