### ISSUE TITLE
Misleading title in section 70?

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#792]
https://asciidoctor.org/docs/user-manual/#specifying-an-output-file

But when you read it, it isn't really about specifying an output file (which is covered in https://asciidoctor.org/docs/user-manual/#document-conversion), it is about using the Asciidoctor command in a pipe.

Rename to "Using asciidoctor as a filter"?
or
"Specifying an output file when reading from STDIN"?

**Comment by mojavelinux** [comment]
Thanks for pointing this out. You're right, this section is totally confused. Let's introduce a new chapter that covers the input and output options of the CLI. Then we'll move all related content underneath it, including a new section that covers piping content through the processor.
