### ISSUE TITLE
The Asciidoctor Eclipse plugin with live preview

### ISSUE THREAD

**Issue by charleech** [asciidoctor/asciidoctor.org#797]
Hi,

I'm not sure if you're aware of  Eclipse plugin named [Asciidoctor Editor](https://marketplace.eclipse.org/content/asciidoctor-editor) or not. Their GitHub is [de-jcup/eclipse-asciidoctor-editor](https://github.com/de-jcup/eclipse-asciidoctor-editor).

I've downloaded and tested, it is very impressive as same as[ AsciidocFX](https://asciidocfx.com/).

Please correct me if I'm wrong. It would be great to add that plugin to the [Editing AsciiDoc with Live Preview](https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/)

**Comment by mojavelinux** [comment]
I agree. If you'd like to see it mentioned on that page, feel free to propose a change. Thanks!

**Comment by charleech** [comment]
Please review the #798.

**Comment by mojavelinux** [comment]
This is now live.
