### ISSUE TITLE
Sub-folders starting with underscore are not processed when using -sourcedirectory

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#800]
"In the Asciidoctor ecosystem, a leading underscore is consider a marker for a hidden file or folder (but, again, only if the segment is in the part of the path that is relative to the source directory)."
Add to cli section.

**Comment by mojavelinux** [comment]
This doesn't apply to the CLI. It's a convention used by the build plugins such as Asciidoctor Maven, Asciidoctor Gradle, and site generators such as Jekyll AsciiDoc and Middleman AsciiDoc. In contrast, the CLI just processes whatever files you tell it to process.

**Comment by mojavelinux** [comment]
The Build Integrations and Implementations chapter (https://asciidoctor.org/docs/user-manual/#build-integrations-and-implementations) needs an introduction. This is where we might be able to slide this tidbit. It can talk about how the build plugins are designed for processing a suite of AsciiDoc files and related assets. One of the conventions those plugins follow is to ignore files and folders that begin with either a dot (`.`) or underscore (`_`) (aka hidden files).

**Comment by mojavelinux** [comment]
This topic is now being addressed by the Maven plugin. See https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/549
