### ISSUE TITLE
Create a page that lists / recommends editors

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#81]
People are often asking which editor they should use for AsciiDoc (phrased as "what's a good AsciiDoc editor?"). Of course, our stance is that you don't need a special editor. We can make that point, but also recommend editors that have good syntax highlighting and perhaps embedded preview.

We want to make sure to recommend open source options first, but I guess it would be biased if we didn't list non-open source editors that are know to be very good (such as Sublime).

**Comment by jaredmorgs** [comment]
The key ones are Atom and AsciidocFX.

Any other ones that spring to mind that we should mention?

Mention them in some sort of quickstart or in the front part of the Users Guide?

**Comment by mojavelinux** [comment]
Whenever we mention Atom, we should mention Brackets as well. The plugin for Brackets (https://github.com/asciidoctor/brackets-asciidoc-preview) gets just as much activity (maybe even more) as the plugin for Atom.

I think we should have a dedicated page for writers tools and these editors should be listed on that page.

There's also a plugin for LightTable. https://github.com/rundis/AsciiLight

**Comment by mojavelinux** [comment]
DocGist is starting to come around as an editor as well.

**Comment by mojavelinux** [comment]
And let's not forget the support in Eclipse (https://wiki.eclipse.org/Mylyn/WikiText/AsciiDoc) and IntelliJ IDEA (https://plugins.jetbrains.com/plugin/7391?pr=idea).

**Comment by jaredmorgs** [comment]
I've introduced a few folks to the Intellij IDEA plugin where I work.

On Tue, 26 Jan 2016 at 12:50 Dan Allen <notifications@github.com> wrote:

> And let's not forget the support in Eclipse (
> https://wiki.eclipse.org/Mylyn/WikiText/AsciiDoc) and IntelliJ IDEA (
> https://plugins.jetbrains.com/plugin/7391?pr=idea).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/issues/81#issuecomment-174789398>
> .
>
-- 

Sent from Mobile.

**Comment by mojavelinux** [comment]
We could also mention RedPen. RedPen doesn't help with AsciiDoc directly, but it understands AsciiDoc so that it can give useful feedback about content.

https://github.com/redpen-cc/redpen

**Comment by mojavelinux** [comment]
With the exception of RedPen, these are all now listed on the tooling page in the new docs. https://docs.asciidoctor.org/asciidoctor/latest/tooling/#ides-and-text-editors If you want to see another editor listed there, please submit a PR.
