### ISSUE TITLE
Using GraphViz with asciidoctor.js

### ISSUE THREAD

**Issue by Skilly** [asciidoctor/asciidoctor.org#816]
I can view plantuml successfully in Chrome with asciidoctor.js, however I'm unable to view GraphViz diagrams. I'm running on windows, have installed the GraphViz msi and have added the following environment variable:

> GRAPHVIZ_DOT=c:/bin/dot.exe

Does asciidoctor.js support GraphViz diagrams?

**Comment by mojavelinux** [comment]
Not currently, to my knowledge. In the browser preview, Asciidoctor.js is using this project, which is currently for plantuml only.

https://github.com/eshepelyuk/asciidoctor-plantuml.js

I would recommend filing an issue in that repository to get the conversation started about graphviz support. This repository is for the asciidoctor.org website, so no action will be taken here.

**Comment by Skilly** [comment]
Thanks @mojavelinux, will do

**Comment by mojavelinux** [comment]
Once you open the issue there, please mention it here then close this one. That way, others can follow the breadcrumbs.

**Comment by mojavelinux** [comment]
In the future, please ask usage questions in the community chat at https://asciidoctor.zulipchat.com.
