### ISSUE TITLE
Develop plan for decommissioning migrated/EOL documentation

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor.org#819]
As docs.asciidoctor.org comes online, we need to plan how we're going to decommission the documentation source files in this repository. Note that the documentation at asciidoctor.org/docs and docs.asciidoctor.org will both be available, simultaneously, as we ensure that all the relevant content and issues has been moved to the appropriate repositories. (and #818 is complete)

We could simply delete the files from the master branch. All the contributions and history will be preserved but the source files are "tucked" away so to speak so as to not cause confusion. Or we could tag and/or branch the asciidoctor.org repository - this may make the original source files easier to find is we need to go back and find something in them - and then remove the documentation source files from master/dev. Whatever plan we choose, we'll probably also use when the new design for asciidoctor.org is implemented.

**Comment by rockyallen** [comment]
Is it still OK to update asciidoctor/asciidoctor.org or should I wait until after the migration?

**Comment by mojavelinux** [comment]
>  Or we could tag and/or branch the asciidoctor.org repository

What we decided to do is create a docs-archive branch that has the state of the repository before the switch to Antora. We also redirect any docs pages that were on asciidoctor.org to docs.asciidoctor.org. We'll continue with this strategy for any additional files that get ported.
