### ISSUE TITLE
trouble with docinfo. and docinfo-footer

### ISSUE THREAD

**Issue by pkuenemann** [asciidoctor/asciidoctor.org#836]
Hi,

I am using AsciiDocFX with AsciiDoc Version 1.5.5 and try to insert my own footer to the generated html-files. For that I place the :docinfo: shared statement on the top of my adoc-file:

```
= Info-Letter Tattoo&Piercing-Studios
:docinfo: shared
:docinfodir: ./meta

image::../images/newsletter-yogi.jpg[align="center"]
```

And place the files docinfo.html and docinfo-footer.html in the named './meta' directory

docinfo.html:
```
<style>
.footer-text { color: rgba(255,255,255,.8); }
</style>
```
docinfo-footer.html:
```
<p class="footer-text">
<a href="https://www.kisscal.tattoo/datenschutz.html">Datenschutz</a>
<a href="https://www.kisscal.tattoo/impressum.html">Impressum</a>
</p>
```

When I now try to save the adoc file as HTML-File, nothing happenes. The file will not be created. When I change the :docinfo: to 'private' and rename the docinfo-files, the html.file can be generated but does not show my own footer.

Any ideas What I am doing wrong?

Best regards,
Peter.

**Comment by mojavelinux** [comment]
Peter, this sounds like an issue with AsciidocFx. Can you file it there? https://github.com/asciidocfx/AsciidocFX

**Comment by pkuenemann** [comment]
I did, thanx.
