### ISSUE TITLE
'stripes' attribute is missing in 23.14 section

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor.org#837]
https://asciidoctor.org/docs/user-manual/#summary-tables

`stripes` attribute is missing in provided table.

**Comment by mojavelinux** [comment]
You are correct. stripes was added in 1.5.8, but not added to the docs. I'd welcome a pull request from you to add it. Thanks!

**Comment by john-cj** [comment]
I'm going to start learn Git this weekend (never used it before, actually).

**Comment by mojavelinux** [comment]
Exciting!

**Comment by mojavelinux** [comment]
Added.
