### ISSUE TITLE
use rouge with site examples

### ISSUE THREAD

**Issue by cup** [asciidoctor/asciidoctor.org#838]
i noticed here that the example with syntax highlighting are using coderay:

https://asciidoctor.org/docs/asciidoc-syntax-quick-reference#source-code

i was concerned as i noticed coderay is no longer being actively developed:

https://github.com/rubychan/coderay

but then i notice that Rouge is also supported:

https://asciidoctor.org/docs/user-manual#available-source-highlighters

so perhaps it would make sense to redo the highlighting with rouge?

**Comment by mojavelinux** [comment]
Yes, we can make this change once Asciidoctor 2.0 is released (which features support for Rouge out of the box).

**Comment by cup** [comment]
@mojavelinux off topic - but this project is great! i notice markdown missing some feature that this fills in an then some! the commonmark spec actually made it worse as no one want to deviate from it even though its lacking

**Comment by cup** [comment]
https://github.com/asciidoctor/asciidoctor/pull/3033

**Comment by mojavelinux** [comment]
I've gone ahead and added information about Rouge wherever CodeRay is covered.

CodeRay is still being maintained, but our recommendation is still Rouge.

Since we're migrating the documentation to Antora, I won't change the syntax highlighter being used for the docs since that will change anyway.
