### ISSUE TITLE
What's the difference between "source" and "listing"?

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor.org#839]
I have carefully read the docs, but haven't found any explanation about the difference between `[source]` and `[listing]`. Here is the Asciidoctor markup and corresponding HTML:

```
[source]
----
Code source
----

[listing]
----
Code listing
----
```

```
<div class="listingblock">
<div class="content">
<pre class="highlight"><code>Code source</code></pre>
</div>
</div>

<div class="listingblock">
<div class="content">
<pre>Code listing</pre>     <-- .highlight class and <code> element disappeared
</div>
</div>
```

So, from what I see I could say that `[listing]` is reserved for monospaced computer-related text, like pseudo-tables. Not sure, though. Is it correct assumption?

```
[listing]
----
|         |        Bar        |
|   Foo   |-------------------|
|         |   Xxx   |   Yyy   |
|-----------------------------|
| ...     | ...     | ...     |
| ...     | ...     | ...     |
| ...     | ...     | ...     |
| ...     | ...     | ...     |
| ...     | ...     | ...     |
----
```

**Comment by mojavelinux** [comment]
The source block provides syntax highlighting (when a language is specified). The listing block does not.

**Comment by john-cj** [comment]
But what's the reason to have `[listing]` whereas language-less `[source]` can accomplish the same task, without any downsides?

**Comment by mojavelinux** [comment]
If the listing style is used on the listing block, it's redundant. But it can also be used on the literal style (to provide an alternate boundary syntax if the content happens to contain a line with 4 hyphens).

Langues-less source should never be used unless you have defined a global language (using the `source-language` attribute, which is the use case for that syntax).

**Comment by john-cj** [comment]
Understood, thanks.
