### ISSUE TITLE
Wrong default value for :docinfo:

### ISSUE THREAD

**Issue by ismailarilik** [asciidoctor/asciidoctor.org#845]
[Here] there is a sentence:

> Setting docinfo with no value is equivalent to setting the value to private.

But I think it is wrong. I have `index.adoc` and `index-docinfo.html` file in the same directory. `index-docinfo.html` file has this content:

```html
<script src="http://localhost:35729/livereload.js?snipver=1"></script>
```

When I tried to convert the AsciiDoc file to HTML, script was not injected.

Then I added this line to `index.adoc`:

```asciidoc
:docinfo: private-head
```

Then script was injected and worked successfully.

So I think default value changed for this directive but I don't know what it is so what I can do is opening an issue rather than fixing this and sending a PR; sorry.

[Here]: https://asciidoctor.org/docs/user-manual/#naming-docinfo-files

**Comment by mojavelinux** [comment]
We have tests to verify this behavior, so I'm confident that the cited statement is correct.

Which version of Asciidoctor are you using? How are you calling Asciidoctor? It's possible that a default value is being set somewhere in your toolchain.

**Comment by ismailarilik** [comment]
Output of `asciidoctor -v`:

```sh
Asciidoctor 1.5.8 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.1p33 (2019-01-30 revision 66950) [x64-mingw32]) (lc:IBM857 fs:Windows-1254 in:IBM857 ex:IBM857)
```

I use Asciidoctor API with Guard:

```rb
require 'asciidoctor'

guard 'shell' do
  watch(/^.*\.adoc$/) do
    Asciidoctor.convert_file 'index.adoc', safe: :safe
  end
end
```

I wrote this line to `index.adoc` file and problem was fixed:

```adoc
:docinfo: private-head
```

I removed this line and tried again. But script wasn't injected as I said before. Also with this line, corresponding livereload functionality worked, but without it this functionality didn't work.

**Comment by mojavelinux** [comment]
You always have to set the `docinfo` attribute. It's just that the value can be blank. In other words, your document needs to look like this:

```
:docinfo:

content of document
```

That's what we mean when we say that the default value (when blank) is `private`. It doesn't mean the attribute is set by default.

The other option is to pass the attribute to the API:

```rb
Asciidoctor.convert_file 'index.adoc', safe: :safe, attributes: 'docinfo'
```

**Comment by ismailarilik** [comment]
Hmm, sorry. I misunderstood. Thanks... 😄
