### ISSUE TITLE
missing "View result" button in AsciiDoc Syntax Quick Reference

### ISSUE THREAD

**Issue by nqb** [asciidoctor/asciidoctor.org#847]
For Inter-document cross references (Asciidoctor only): 

![Screenshot from 2019-03-26 09-57-55](https://user-images.githubusercontent.com/10830260/54983753-be2bf880-4fad-11e9-90bf-b11fed1fe25e.png)

**Comment by mojavelinux** [comment]
That's because these links would lead to no where since document-b.adoc is a fake document reference.

**Comment by nqb** [comment]
Thanks.
