### ISSUE TITLE
Add link to conversion script (Confluence XHTML to AsciiDoc)

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#85]
Add a link to the following script on the migrations page that converts Confluence XHTML to AsciiDoc:

https://gist.github.com/melix/6020336

**Comment by jaredmorgs** [comment]
Next action:

* create new section in https://github.com/asciidoctor/asciidoctor.org/blob/ed5e4f38159872c1dbfe2a42d8a0aef5a2d7cfb5/docs/user-manual.adoc#conversions-and-migrations.
* add link to page.
* describe what the script does in summary.

Should we also link to the Markdown to Asciidoctor script you created as well in this section @mojavelinux ?

Anything else that deserves mention here?

**Comment by mojavelinux** [comment]
Yes, add the link to https://github.com/opendevise/kramdown-asciidoc. And we might as well add a link to DocbookRx as well https://github.com/opendevise/docbookrx. We can mention that the plugin for IntelliJ IDEA has a built-in tool for converting from Markdown to AsciiDoc.

**Comment by jaredmorgs** [comment]
I'll reserve the kramdown-asciidoc fix for #462 

I need to add the DocbookRx to this commit.

**Comment by jaredmorgs** [comment]
I will now add the DocBookRx content into the guide.

**Comment by mojavelinux** [comment]
Ye-ha!

**Comment by mojavelinux** [comment]
Merged as 5288b2625fd45c64e448f6821695d39e3cd7c182 with additional revisions in 84ddece32776e35a960922edaaab32e2de428b8c.
