### ISSUE TITLE
Example is missing role?

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#850]
https://asciidoctor.org/docs/user-manual/#block-assignment
Says

````
Let’s say you want to create a blockquote from an open block and assign it an ID and role. You add quote (the block style) in front of the # (the ID) in the first attribute position, as this example shows:

[quote#roads, Dr. Emmett Brown]
____
Roads? Where we're going, we don't need roads.
____

 NOTE: The order of ID and role values in the shorthand syntax does not matter.
````
I expected to see .something in the example. Also role isnt covered until the next section, so perhaps the example is right and the text is wrong? Or I don't understand and the example needs more explanation.

**Comment by mojavelinux** [comment]
Very likely it's an incomplete thought / section. Feel free to propose a revision.

**Comment by mojavelinux** [comment]
This example has been separated into separate pages, https://docs.asciidoctor.org/asciidoc/latest/attributes/id/ and https://docs.asciidoctor.org/asciidoc/latest/attributes/role/.
