### ISSUE TITLE
Remove duplication of "troubleshooting complex URLs"

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#853]
Delete from https://asciidoctor.org/docs/user-manual/#url and leave a link to https://asciidoctor.org/docs/user-manual/#troubleshoot

**Comment by mojavelinux** [comment]
This topic now has a dedicated page and thus only appears once in the documentation. See https://docs.asciidoctor.org/asciidoc/latest/macros/complex-urls/
