### ISSUE TITLE
Section 13. Basic Document Anatomy should be level 0

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#856]
Or push the following sections down

**Comment by mojavelinux** [comment]
It would really be best if you held off on doing any more analysis of the current structure until the new site is up (which we're working to get up asap). Not only will we be aligning efforts, it will be so much easier to rearrange content in the new, Antora-based structure.

**Comment by mojavelinux** [comment]
FYI, the aforementioned migration is complete. I'm happy to report that the docs are open for analysis once again!
