### ISSUE TITLE
First paragraph is not helpful

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctor.org#857]
If I google "Asciidoctor user manual" I get straight to the manual (good). But supposing I was new to Asciidoctor, there is nothing on the first page that says "Yes, this is the reference document for the asciidoc syntax and the HTML backend. If you just want a simple syntax guide see <<>> or if you want reference information on the pdf backend see <<>>. There is lots of other documentation available on <<>>."

**Comment by mojavelinux** [comment]
Again, this is the focus of the docs overhaul. We're not investing any more information architecture into the existing manual anymore. The new site will have a clear intro page.

**Comment by mojavelinux** [comment]
Hopefully you'll agree that we finally have a proper landing page and entry point for someone new to AsciiDoc and Asciidoctor. https://docs.asciidoctor.org/ If you see areas where the text can be improved, I encourage you to click "Edit this Page" and share your ideas. Thanks!
