### ISSUE TITLE
Trivial error on User Manual page

### ISSUE THREAD

**Issue by foo-dogsquared** [asciidoctor/asciidoctor.org#862]
Hello! I've been just exploring on Asciidoctor and found an error on the [user manual page](https://asciidoctor.org/docs/user-manual/).

![asciidoctor-website](https://user-images.githubusercontent.com/34962634/57766945-e082fc80-773a-11e9-9a47-1444d96f4cd6.png)

Simply, the raw code for making a sidebar and block titles are missing and instead being generated "correctly".

**Comment by mojavelinux** [comment]
You're absolutely right! I can't believe we didn't notice that before. Good catch!
