### ISSUE TITLE
Integrator Guide link is broken 

### ISSUE THREAD

**Issue by jottinger** [asciidoctor/asciidoctor.org#865]
From various pages found via https://asciidoctor.org/docs/asciidoctorj/#writing-a-custom-converter , the Integrator Guide link is broken.

**Comment by mojavelinux** [comment]
I see what's happening. The AsciidoctorJ README now as links to other docs, so we need to set the right relative path prefix.

**Comment by mojavelinux** [comment]
Fixed! I also updated the docs to 2.1.0.

cc: @robertpanzer
