### ISSUE TITLE
27.2. Defining an Anchor doc bug in first para

### ISSUE THREAD

**Issue by mark-summerfield** [asciidoctor/asciidoctor.org#871]
The last sentence of the first para reads:

"The anchor is declared by enclosing a valid XML Name in double square brackets (e.g., ) or using the shorthand ID syntax (e.g., [#idname]) at the start of an attribute list."

Notice that there is _nothing_ between the "(e.g.," and the closing ")". I'm guessing it should show `[[idname]]` or `[#idname]`?

**Comment by mark-summerfield** [comment]
I thought that's what I'd done. I'm no github expert!

**Comment by mojavelinux** [comment]
You don't need to close. I already moved the issue (thanks to the handy feature that GitHub offers).

**Comment by mojavelinux** [comment]
This has since been fixed. See https://docs.asciidoctor.org/asciidoc/latest/attributes/ids/#anchor I think the example text was not properly escaped, which is why it was showing up empty.
