### ISSUE TITLE
Inter-document cross reference with GitLab

### ISSUE THREAD

**Issue by manheraz** [asciidoctor/asciidoctor.org#872]
GitLab sets the value of outfilesuffix to .adoc too, so the condition is no longer required.

Source: [Set Asciidoctor outfilesuffix to default .adoc ](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/17125)

Could you please update the "Navigating Between Source Files" section, please?

Thank you in advance.

**Comment by mojavelinux** [comment]
Would you like to submit a pull request to update this information?

**Comment by mojavelinux** [comment]
I have clarified this point on the following page: https://docs.asciidoctor.org/asciidoc/latest/macros/inter-document-xref/#navigating-between-source-files
