### ISSUE TITLE
where can I find an example of a custom footer?

### ISSUE THREAD

**Issue by acortcab** [asciidoctor/asciidoctor.org#880]
My goal is to customize the footer created by asciidoc because I want to add copyright and other stuff
I read the user manual and what I understood:
1- I have to add this attribute :docinfo2: in my adoc file
2- then create a file called "docinfo-footer.html" with my content

I guessed I missed something because it is not working, could anyone tell me where I can find an example with the complete code of the adoc file???

Thanks

**Comment by mojavelinux** [comment]
The following page explains how to use the docinfo feature, with an example for the head: https://docs.asciidoctor.org/asciidoctor/latest/docinfo/ The footer follows the same pattern, but requires the docinfo file to end with `-footer` plus the file extension of the output format (e.g., `-footer.html`). See https://docs.asciidoctor.org/asciidoctor/latest/docinfo/#footer

If you aren't able to achieve the result you want, please ask for help in the community chat at https://asciidoctor.zulipchat.com. Once you get it working, please consider submitting the example to the docs and we'll either integrate it or a variation of it.
