### ISSUE TITLE
Live preview with stylesheet

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor.org#882]
Currently, there are two slightly different instructions to use live preview.

* One here: https://github.com/asciidoctor/guard-asciidoc/blob/master/README.asciidoc
* And another one here: https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/

The Guard::AsciiDoc README states that there is no stylesheet option, yet.

The article on the asciidoctor.org describes the ways that doesn't use Guard::AsciiDoc, and there is a screenshot with a styled document.

![shot](https://user-images.githubusercontent.com/18004961/63639012-9396b680-c697-11e9-94d8-dc9c0ea6b952.PNG)

However, when I try to use the way described in the asciidoctor.org article, the document is still unstyled. Have I missed something?

**Comment by mojavelinux** [comment]
Yes, this page is woefully out of date. There's already an open issue to update it. See #48.

**Comment by john-cj** [comment]
Get it, thanks. But what is the way the stylesheet is working in this screenshot? I have tried to use Guard and my documents are unstyled.

**Comment by mojavelinux** [comment]
Set the safe mode, as in `safe: :unsafe`.

**Comment by john-cj** [comment]
Get it, thanks. So, the Guardfile should be something like this:

``` ruby
Bundler.require :default

guard 'shell' do
  watch(/^.+(\.adoc)$/) {|m|
    Asciidoctor.convert_file m[0], safe: :unsafe, attributes: { 'toc' => 'left' }
  }
end
```
