### ISSUE TITLE
Add LivePage extension to the list of tools

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor.org#883]
https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/#web-preview

The currently listed options to refresh the browser page are Epiphany, LiveReload (app + browser extension), and Guard::LiveReload.

There is another option: LivePage extension by Mike Rogers.

* https://chrome.google.com/webstore/detail/livepage/pilnojpmdoofaelbinaeodfpjheijkbh
* https://github.com/MikeRogers0/LivePage
* https://livepage.mikerogers.io/

Advantages:  works out of the box; open source. Limitations: Chrome only; commercial.

**Comment by mojavelinux** [comment]
I don't think recommending a commercial extension is appropriate for this site.

**Comment by john-cj** [comment]
Well, I get it.
