### ISSUE TITLE
italic words and letters - advice and example don't match

### ISSUE THREAD

**Issue by PhilipOakley** [asciidoctor/asciidoctor.org#897]
https://asciidoctor.org/docs/user-manual/#bold-and-italic

"Letters and words are italicized using one (_) or two (__) underscores."

but the example shows the other way around (and, for bold the advice is the other way as well, one char is words, two chars is letter groups)

probably should say
"_Words and letters_ are italicized using one (_) or two (__) underscores _respectively_."

**Comment by PhilipOakley** [comment]
I'd of marked up the source if I could find it..

**Comment by mojavelinux** [comment]
Resolved by 171103c9876b64ed9ab5b1ce54eb57c4f38b7978
