### ISSUE TITLE
declare a dependency to another extension

### ISSUE THREAD

**Issue by uniqueck** [asciidoctor/asciidoctor.org#900]
Hi guys,

what is the prefered way to define the dependency to another extension. I wrote an extension that generate plantuml and so i need diagram extension to generate a picture from this plantuml code.
Should I declare the dependency to asciidoctor-diagram or should i only describe it in my documentation, that this extension needs asciidoctor-diagram in version ...?

**Comment by mojavelinux** [comment]
Ultimately, that's your call. I tend to prefer documenting them to give the user the most control. But there are benefits to doing it either way.

**Comment by uniqueck** [comment]
Thanks for the intentions. So I will declare it as provided with the minimum needed version.
