### ISSUE TITLE
AsciiDoc document vs. Asciidoctor document

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor.org#909]
As I know,

* AsciiDoc is a name of the language
* Asciidoctor is a name of the parser

Thus, when we talk about a document, it will be correct to say "AsciiDoc document", not "Asciidoctor document".

This approach is used in the User Manual with a few exceptions. These exceptions may be worth to be fixed.

**Comment by mojavelinux** [comment]
You're correct in saying that it's an AsciiDoc document, not an Asciidoctor document. AsciiDoc is the language. Asciidoctor is the processor (not just parser, but processor).

There are obviously integrations that a processor can bring to the language, such as source highlighting, diagrams, equations and the like. But none of that changes the semantics of the language itself.

**Comment by itsme-narahari** [comment]
> You're correct in saying that it's an AsciiDoc document, not an Asciidoctor document. AsciiDoc is the language. Asciidoctor is the processor (not just parser, but processor).
> 
> There are obviously integrations that a processor can bring to the language, such as source highlighting, diagrams, equations and the like. But none of that changes the semantics of the language itself.

So asciidoctor, asciidoctorj, asciidoctorjs are all different variants of the processor as in different programming languages have been used to implement the asciidoc spec.

Is it safe to say the above statement ?

**Comment by mojavelinux** [comment]
Not really. Asciidoctor (Ruby), AsciidoctorJ, and Asciidoctor.js are all the same implementation of the AsciiDoc processor, Asciidoctor. That same implementation has been ported to be used on different language runtime, which is what these are. They each have their own API layer on top, but the parsing is exactly the same.

> have been used to implement the asciidoc spec.

as of yet there is no official spec. But the effort is getting underway soon. Asciidoctor will likely then become an implementation, though there will be others as well. For now, Asciidoctor is an implementation of the defacto-standard AsciiDoc.

**Comment by mojavelinux** [comment]
> it will be correct to say "AsciiDoc document", not "Asciidoctor document".

These instances have all been corrected in the new docs site at https://docs.asciidoctor.org.
