### ISSUE TITLE
"Differences" page doesn't mention backticks

### ISSUE THREAD

**Issue by ecree-solarflare** [asciidoctor/asciidoctor.org#917]
docs/asciidoc-asciidoctor-diffs.adoc does not appear to mention the changes to +plusses+ and \`backticks\` introduced in AsciiDoctor 1.5.0 (per docs/migration.adoc), which are arguably one of the most significant differences between AsciiDoc and AsciiDoctor.

**Comment by mojavelinux** [comment]
Very excellent point. That section didn't get reviewed / updated after the 1.5 and 2.0 releases. Feel free to submit a PR to add that information or link to the [migration page](https://asciidoctor.org/docs/migration/), which contains all those details.

**Comment by mojavelinux** [comment]
I now consider this topic to be covered adequately on the following page: https://docs.asciidoctor.org/asciidoctor/latest/migrate/asciidoc-py/#compatibility-mode
