### ISSUE TITLE
Broken link to Ruby API documentation

### ISSUE THREAD

**Issue by owenh000** [asciidoctor/asciidoctor.org#923]
In the [Using the Ruby API](https://asciidoctor.org/docs/user-manual/#using-the-ruby-api) section of the User Manual, there is a broken link to the "[public APIs in Asciidoctor](https://www.rubydoc.info/gems/asciidoctor/Asciidoctor)". The source is at [docs/_includes/require-asciidoctor.adoc](https://github.com/asciidoctor/asciidoctor.org/blob/73d5a07ba92912f7ac2869f0ca1a58eddbf0b2e7/docs/_includes/require-asciidoctor.adoc).

I suppose this should link to <https://www.rubydoc.info/gems/asciidoctor> instead, as in the [References and Developer Resources](https://asciidoctor.org/docs/#references-and-developer-resources) section.

**Comment by owenh000** [comment]
See pull request #924.

**Comment by owenh000** [comment]
See also related issue #925.

**Comment by mojavelinux** [comment]
I merged the PR so I think this is now resolved. Please confirm.

In the future, can you add "resolves xyz" to the start of the PR subject?

**Comment by owenh000** [comment]
>Please confirm.

It appears to be fixed now, thanks.

>add "resolves xyz" to the start of the PR subject

I'll try to remember to do that.
