### ISSUE TITLE
Country code or language code (or language tag)

### ISSUE THREAD

**Issue by 747** [asciidoctor/asciidoctor.org#933]
[75.1. Translating built-in labels](https://asciidoctor.org/docs/user-manual/#customizing-labels)
> When converting to DocBook, you can rely on the DocBook toolchain to translate (most) built-in labels. To activate this feature, simply set the `lang` attribute to a valid ***country code (which defaults to `en` for English)***.

[A.2. Built-in Attributes](https://asciidoctor.org/docs/user-manual/#builtin-attributes)
> Attribute name | Description | Default value | Allowed values | Header only | See also
> -- | -- | -- | -- | -- | --
> lang | Set the value of the lang attribute on the root element of the output document. | en | Valid XML ***country code*** | ✔ | Translating built-in labels

(emphasis by me)

The _country code_ and the _language code_ are different standards ([ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) and [ISO 639](https://en.wikipedia.org/wiki/ISO_639)), and there's no "country code for English". Moreover, there's neither "XML country code" nor "XML language code", by which I think you mean _language tag_ ([BCP 47](https://en.wikipedia.org/wiki/IETF_language_tag)), which is [the only binding standard](https://www.w3.org/TR/REC-xml/#sec-lang-tag) in the XML spec among them.

This confusion brings about actual contradictions in your assets in https://github.com/asciidoctor/asciidoctor/tree/master/data/locale, namely:

- misnomers if it means _country code_ (or locale)
  - `ar`: Argentina, not any Arabic countries
  - `ca`: Canada, not Catalonia
  - `cs`: reserved for former Serbia and Montenegro, not Czech
  - `fa`: nonexistent
  - `ja`: reserved for Jamaica, not Japan
  - `nb`: nonexistent
  - `nn`: nonexistent
  - `pt_BR`: invalid even as Portugal's subdivision
  - `sr`: Suriname, not Serbia
  - `sr_Latn`: invalid even as Suriname's subdivision
  - `sv`: El Salvador, not Sweden
  - `uk`: reserved for United Kingdom, not Ukraine
  - `zh_CN`, `zh_TW`: nonexistent

- misnomers if _language code_
  - `kr`: Kanuri, not Korean
  - `pt_BR`, `sr_Latn`, `zh_CN`, `zh_TW`: no such format

- misnomers if _language tag_
  - `kr`: Kanuri, not Korean

Strictly speaking, subtags of a _language tag_ need to be connected by **hyphen**, not **underscore**.

**Comment by mojavelinux** [comment]
The documentation has been updated to clarify that the value of the `lang` attribute must be a BCP 47 language tag. That's because the attribute value is passed directly to the lang attribute or xml:lang attribute for HTML and DocBook, respectively.

If you believe that one of the locale files is named incorrectly and needs to be changed, feel free to submit a pull request to correct it.
