### ISSUE TITLE
[%collapsible] and [%autofit] are not described in the manual

### ISSUE THREAD

**Issue by silvester747** [asciidoctor/asciidoctor.org#943]
Through various blogposts I learned about collapsible blocks with [%collapsible] and autofitting source code with [%autofit]. However, I cannot seem to find any reference to this in the manual (https://asciidoctor.org/docs/user-manual).

Should this become part of the manual? Or is there some other place where this functionality is described?

**Comment by mojavelinux** [comment]
Please reopen this as two separate issues in https://github.com/asciidoctor/asciidoc-docs. Thanks!

**Comment by mojavelinux** [comment]
The autofit option is unique to Asciidoctor PDF and is documented here: https://github.com/asciidoctor/asciidoctor-pdf#autofitting-text This is not (yet) a standard option in AsciiDoc itself.

**Comment by mojavelinux** [comment]
This request to document the collapsible option has been resubmitted as https://github.com/asciidoctor/asciidoc-docs/issues/34.
