### ISSUE TITLE
Enable flipping 'icons' attribute to correct example under 'Admonition' in User Manual

### ISSUE THREAD

**Issue by nkalvi** [asciidoctor/asciidoctor.org#947]
https://github.com/asciidoctor/asciidoctor.org/blob/8729a94926bce17e1bda12f426f4d242d143a2ff/_config/site.yml#L21

Since setting here take priority, examples under [Admonition](https://asciidoctor.org/docs/user-manual/#admonition) section 

> In the examples above, the admonition is rendered in a callout box with the style label in the gutter. You can replace the textual labels with icons by setting the icons attribute on the document. This is how the WARNING admonition paragraph renders when icons is set and assigned the font value.

display font icons instead of text labels (though source files unset the value for `icons` for the sections.)

So, shouldn't this be set to `icons: 'font@'` instead?

**Comment by mojavelinux** [comment]
Yep. I've updated the config.

**Comment by nkalvi** [comment]
Thanks!

**Comment by mojavelinux** [comment]
Thank you!

And it look like it's now fixed.
