### ISSUE TITLE
Empty API docs listed in website

### ISSUE THREAD

**Issue by sorpaas** [asciidoctor/asciidoctor.org#961]
The link of "Asciidoctor Ruby API Documentation" in https://asciidoctor.org/docs/ leads to [this page](https://www.rubydoc.info/gems/asciidoctor). However, it only contains an empty API list with only the README being there. Honestly right now I still haven't found a way to grab the API docs anywhere.

**Comment by sorpaas** [comment]
Looks like this is a known issue. For anyone encountered this as well, the 2.0.9 doc seems to be working. https://www.rubydoc.info/gems/asciidoctor/2.0.9

**Comment by mojavelinux** [comment]
Correct. We're just waiting on the 2.0.11 release now.
