### ISSUE TITLE
Setting Rouge style attributes not explained in documentation

### ISSUE THREAD

**Issue by mcp292** [asciidoctor/asciidoctor.org#964]
The `rouge-style` attribute is mentioned in [the documentation](https://asciidoctor.org/docs/user-manual/#rouge), but no usage is shown.

I tried putting this under my doc title
```
= Title
:source-highlighter: rouge
:rogue-style: thankful-eyes
```
but it has no effect.

I also tried
```
[source,c,rouge-style=thankful-eyes]
```
above the code block with and without quotes around the value.

**Comment by mojavelinux** [comment]
This is now documented here: https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/rouge/#rouge-attributes
