### ISSUE TITLE
Redirect migrated docs to the new docs site

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#981]
Redirect the migrated docs to the new docs site at docs.asciidoctor.org when available. Use a JavaScript based router to redirect deep links to the appropriate page.

The top-level pages are as follows:

* Asciidoctor user manual
* AsciiDoc syntax quick reference
* Migration page
* Install pages

The first two are the most important. The second two can be done a bit later.

**Comment by graphitefriction** [comment]
### Pages on asciidoctor.org that can be redirected to new docs pages

https://asciidoctor.org/docs/what-is-asciidoctor/ -> https://docs.asciidoctor.org/home/ **OR** https://docs.asciidoctor.org/asciidoctor/latest/

https://asciidoctor.org/docs/what-is-asciidoctor/#whats-unique-about-the-asciidoctor-implementation -> https://docs.asciidoctor.org/asciidoctor/latest/features/

https://asciidoctor.org/docs/what-is-asciidoctor/#system-requirements -> https://docs.asciidoctor.org/asciidoctor/latest/install/supported-platforms/

https://asciidoctor.org/docs/asciidoc-vs-markdown/ -> https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/

https://asciidoctor.org/docs/install-toolchain/ -> https://docs.asciidoctor.org/asciidoctor/latest/install/

https://asciidoctor.org/docs/install-toolchain/#system-requirements -> https://docs.asciidoctor.org/asciidoctor/latest/install/supported-platforms/

https://asciidoctor.org/docs/install-toolchain/#installing-the-asciidoctor-rubygem -> https://docs.asciidoctor.org/asciidoctor/latest/install/ruby-packaging/

https://asciidoctor.org/docs/install-toolchain/#install-using-yum-or-dnf-on-fedora, https://asciidoctor.org/docs/install-toolchain/#install-using-apt-get-on-debian-or-ubuntu, https://asciidoctor.org/docs/install-toolchain/#install-using-apk-on-alpine-linux -> https://docs.asciidoctor.org/asciidoctor/latest/install/linux-packaging/

https://asciidoctor.org/docs/install-toolchain/#upgrading-the-asciidoctor-ruby-gem -> https://docs.asciidoctor.org/asciidoctor/latest/install/

https://asciidoctor.org/docs/install-toolchain/#text-editors-and-syntax-highlighting -> https://docs.asciidoctor.org/asciidoctor/latest/tooling/

https://asciidoctor.org/docs/convert-documents/, https://asciidoctor.org/docs/convert-documents/#selecting-an-output-format, https://asciidoctor.org/docs/convert-documents/#converting-a-document-to-html, https://asciidoctor.org/docs/convert-documents/#using-the-command-line-tool, https://asciidoctor.org/docs/convert-documents/#using-the-ruby-api -> https://docs.asciidoctor.org/asciidoctor/latest/get-started/

https://asciidoctor.org/docs/convert-documents/#styling-the-html-with-css -> https://docs.asciidoctor.org/asciidoctor/latest/html-backend/stylesheet-modes/

https://asciidoctor.org/docs/convert-documents/#managing-images -> https://docs.asciidoctor.org/asciidoctor/latest/html-backend/manage-images/

https://asciidoctor.org/docs/convert-documents/#coderay-and-pygments-stylesheets -> https://docs.asciidoctor.org/asciidoctor/latest/html-backend/source-highlighting-stylesheets/

https://asciidoctor.org/docs/convert-documents/#converting-a-document-to-docbook -> https://docs.asciidoctor.org/asciidoctor/latest/docbook-backend/

https://asciidoctor.org/docs/asciidoctor-revealjs/ -> https://docs.asciidoctor.org/reveal.js-converter/latest/

https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/ -> https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/ (and all the deeplinks on it) -> https://docs.asciidoctor.org/asciidoctor/latest/tooling/

https://asciidoctor.org/docs/migrating-from-msword/ -> https://docs.asciidoctor.org/asciidoctor/latest/migrate/ms-word/

### Brief wait before enabling redirect

https://asciidoctor.org/docs/install-asciidoctor-macos/ <- I have to do a quick confirmation to ensure the most up-to-date Mac instructions have been migrated before we add the redirect

https://asciidoctor.org/docs/migration/ <- This page needs another pass through as there are chunks of content I'm not sure we've made final decisions on.

### Pages that haven't had their content migrated 

Or even evaluated on whether or not they should be migrated and therefore redirected....

- https://asciidoctor.org/docs/what-is-asciidoc/
- https://asciidoctor.org/docs/asciidoc-asciidoctor-diffs/

These two pages :arrow_up:  has some sections on it that aren't accounted for so we're not ready to redirect it but it should be evaluated fairly soon.

- https://asciidoctor.org/#authors

This deep link :arrow_up: (which is accessed from Who created Asciidoctor? on asciidoctor.org/docs) might be redirected to the history/timeline file or an authors/contributor file in the community docs component.

- https://asciidoctor.org/docs/produce-custom-themes-using-asciidoctor-stylesheet-factory/
- https://asciidoctor.org/docs/asciidoc-writers-guide/
- https://asciidoctor.org/docs/asciidoc-recommended-practices/
- https://asciidoctor.org/docs/asciidoc-article/

**Comment by graphitefriction** [comment]
### URLs to redirect with project maintainers :+1: 

https://asciidoctor.org/docs/asciidoctorj/ -> https://docs.asciidoctor.org/asciidoctorj/latest/
https://asciidoctor.org/docs/asciidoctor.js/ -> https://docs.asciidoctor.org/asciidoctor.js/latest/
https://asciidoctor.org/docs/asciidoctor-revealjs/ -> https://docs.asciidoctor.org/reveal.js-converter/latest/
https://asciidoctor.org/docs/asciidoctor-maven-plugin/ -> https://docs.asciidoctor.org/maven-tools/latest/
https://asciidoctor.org/docs/hack-asciidoctor-maven-plugin/ -> https://docs.asciidoctor.org/maven-tools/latest/project/contributing/
https://asciidoctor.org/docs/asciidoclet/ -> https://docs.asciidoctor.org/asciidoclet/latest/

**Comment by mojavelinux** [comment]
I'm not sure we're ready to redirect the project URLs yet. The supposed purpose of those pages is to be a landing page for the projects themselves, not necessarily the docs. If we continue to build those pages from the README files, then they will truly become discrete from the docs. On the other hand, we could redesign the pages to actually look like landing pages. I think we need to discuss what the purpose and fate of these pages are in the grand scheme of things, then determine what action to take.

**Comment by mojavelinux** [comment]
> asciidoctor.org/docs/install-asciidoctor-macos <- I have to do a quick confirmation to ensure the most up-to-date Mac instructions have been migrated before we add the redirect

I'm pretty sure we haven't reconciled this page yet. It's also possible it contains outdated information. We need to examine both pages, see what aligns with current installation methods for macOS, and determine what the authoritative information is.

**Comment by graphitefriction** [comment]
> I'm pretty sure we haven't reconciled this page yet. It's also possible it contains outdated information. We need to examine both pages, see what aligns with current installation methods for macOS, and determine what the authoritative information is.

I agree, there needs to be a final reconciliation between that page, the README, and what's in the docs to determine what's the correct information.
