### ISSUE TITLE
The `theme showcase` link is broken

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/asciidoctor.org#983]
Hi all,

In the official docs, at section number 72 `Stylesheet Factory`, there is a link to `theme showcase`, this link is broken, it leads to somewhere else (looks like some old doc about AsciiDoc) and not to theme showcase.

Thanks.

**Comment by mojavelinux** [comment]
The user manual is soon to be replaced with the new docs at docs.asciidoctor.org. The stylesheet factory is no longer mentioned in the docs since it is considered deprecated. Therefore, I'm not going to spend time fixing this one.
