### ISSUE TITLE
User Manual is showing 404 Page Not Found

### ISSUE THREAD

**Issue by chuck-confluent** [asciidoctor/asciidoctor.org#991]
As of this moment, https://asciidoctor.org/docs/user-manual/ is showing 404 page not found. Is this expected?

**Comment by mojavelinux** [comment]
Thanks for the heads up, @chuck-confluent! There was a misunderstanding about the role that page was playing in the deployment of the client-side URL router. I've restored the stub for that page (and other pages with the same problem) so the behavior of the URL router is restored. It should be all good now!

Resolved by ada540d0f1e2dc3d8d611e719161c0ffae603faf
