### ISSUE TITLE
Redirect asciidoctor.org/docs/asciidoctor-revealjs to docs.asciidoctor.org/reveal.js-converter/

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.org#993]
As the title says :wink:

**Comment by mojavelinux** [comment]
@Mogztter Do you plan to submit a PR to add this to the URL router?

Keep in mind that you do have to leave an empty page behind so that the URL router has something to attach to.

**Comment by Mogztter** [comment]
@mojavelinux Yes, it just slipped off my list, sorry :sweat_smile:

**Comment by mojavelinux** [comment]
No worries. I just happened to be grooming the asciidoctor.org repo looking for docs issues to fix ;)
